In [1]:
from tensorflow.keras.models import load_model

In [2]:
from scipy import io
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from sklearn.metrics import roc_curve, auc

In [3]:
cnt = 0

i = 1
j = 1
z = 1
for i in range(1,3):
    print('---------------------------------')
    for j in range(1,4):
        print('---------------------------------')
        for z in range(1,16):
            if(z < 10 and z > 0):
                mat_file = io.loadmat(f'./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f0{z}-data.mat')
                print(mat_file.get(f'melexisG{i}{j}f0{z}').shape)
                cnt += mat_file.get(f'melexisG{i}{j}f0{z}').shape[0]
            else:
                mat_file = io.loadmat(f'./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f{z}-data.mat')
                print(mat_file.get(f'melexisG{i}{j}f{z}').shape)
                cnt += mat_file.get(f'melexisG{i}{j}f{z}').shape[0]
           
                
            
#mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f01-data.mat')

---------------------------------
---------------------------------
(880, 768)
(1000, 768)
(1420, 768)
(930, 768)
(1340, 768)
(1410, 768)
(1270, 768)
(930, 768)
(950, 768)
(940, 768)
(1100, 768)
(1110, 768)
(1160, 768)
(1020, 768)
(1230, 768)
---------------------------------
(2900, 768)
(1730, 768)
(1970, 768)
(1380, 768)
(1250, 768)
(1100, 768)
(980, 768)
(1250, 768)
(990, 768)
(1290, 768)
(980, 768)
(1260, 768)
(1050, 768)
(1210, 768)
(1150, 768)
---------------------------------
(1010, 768)
(960, 768)
(1100, 768)
(910, 768)
(1015, 768)
(1069, 768)
(1290, 768)
(940, 768)
(1239, 768)
(1240, 768)
(1005, 768)
(1130, 768)
(1240, 768)
(1215, 768)
(1614, 768)
---------------------------------
---------------------------------
(760, 768)
(850, 768)
(680, 768)
(840, 768)
(1230, 768)
(1200, 768)
(1000, 768)
(830, 768)
(810, 768)
(870, 768)
(1090, 768)
(810, 768)
(740, 768)
(1001, 768)
(970, 768)
---------------------------------
(710, 768)
(760, 768)
(620, 768)
(510, 768)
(1110, 768)
(920, 7

In [4]:
model = load_model('./savecnnminmax2.h5')

In [5]:
from scipy import io
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from sklearn.metrics import roc_curve, auc
import tensorflow as tf

In [6]:
def data_merge(data,x1, x2, x3, x4, x5, x6,x7, x8, x9, x10):
    data.loc[0:x1-1,'label'] = 0
    data.loc[x1:x2,'label'] = 1
    data.loc[x2+1:x3-1,'label'] = 0 
    data.loc[x3:x4,'label'] = 1 
    data.loc[x4+1:x5-1,'label'] = 0 
    data.loc[x5:x6,'label'] = 1
    data.loc[x6+1:x7-1,'label'] = 0 
    data.loc[x7:x8,'label'] = 1
    data.loc[x8+1:x9-1,'label'] = 0 
    data.loc[x9:x10,'label'] = 1
    data.loc[x10 +1:,'label'] = 0
    return data

def data_merge2(data,x1, x2, x3, x4, x5, x6,x7, x8, x9, x10,x11,x12):
    data.loc[0:x1-1,'label'] = 0
    data.loc[x1:x2,'label'] = 1
    data.loc[x2+1:x3-1,'label'] = 0 
    data.loc[x3:x4,'label'] = 1 
    data.loc[x4+1:x5-1,'label'] = 0 
    data.loc[x5:x6,'label'] = 1
    data.loc[x6+1:x7-1,'label'] = 0 
    data.loc[x7:x8,'label'] = 1
    data.loc[x8+1:x9-1,'label'] = 0 
    data.loc[x9:x10,'label'] = 1
    data.loc[x10 +1:x11-1,'label'] = 0
    data.loc[x11:x12,'label'] = 1
    data.loc[x12 +1:,'label'] = 0
    return data

In [7]:
import pandas as pd
import csv

mat_file_G11_io = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f01-data.mat')
print(mat_file_G11_io.get('melexisG11f01'))
print(mat_file_G11_io.get('melexisG11f01')[0][0])
G11data1 = pd.DataFrame(mat_file_G11_io.get('melexisG11f01'))
G11data1 = data_merge(G11data1,154, 195, 300, 336, 466, 493, 580, 666, 764, 823)

mat_file_G11_io2 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f02-data.mat')
G11data2 = pd.DataFrame(mat_file_G11_io2.get('melexisG11f02'))
G11data2 = data_merge(G11data2,47, 127, 260, 334, 439, 500, 662, 725, 880, 951)

mat_file_G11_io3 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f03-data.mat')
G11data3 = pd.DataFrame(mat_file_G11_io3.get('melexisG11f03'))
G11data3 = data_merge(G11data3,209, 289, 411, 466, 873, 930, 1130, 1184, 1292, 1340)

mat_file_G11_io4 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f04-data.mat')
G11data4 = pd.DataFrame(mat_file_G11_io4.get('melexisG11f04'))
G11data4 = data_merge(G11data4,212, 255, 371, 411, 496, 548, 673, 718, 812, 873)

mat_file_G11_io5 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f05-data.mat')
G11data5 = pd.DataFrame(mat_file_G11_io5.get('melexisG11f05'))
G11data5 = data_merge(G11data5,176, 212, 366, 415, 510, 556, 815, 873, 1070, 1143)

mat_file_G11_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f06-data.mat')
G11data6 = pd.DataFrame(mat_file_G11_io6.get('melexisG11f06'))
G11data6 = data_merge2(G11data6,20, 66, 440, 503, 670, 721, 928, 988, 1104, 1151,1301,1409)

mat_file_G11_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f07-data.mat')
G11data7 = pd.DataFrame(mat_file_G11_io7.get('melexisG11f07'))
G11data7 = data_merge(G11data7,148, 199, 414, 459, 608, 668, 976, 1010, 1175, 1269)

mat_file_G11_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f08-data.mat')
G11data8 = pd.DataFrame(mat_file_G11_io8.get('melexisG11f08'))
G11data8 = data_merge(G11data8,212, 270, 372, 414, 505, 557, 645, 719, 830, 881)

mat_file_G11_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f09-data.mat')
G11data9 = pd.DataFrame(mat_file_G11_io9.get('melexisG11f09'))
G11data9 = data_merge(G11data9,186, 231, 378, 417, 512, 565, 701, 749, 863, 938)

mat_file_G11_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f10-data.mat')
G11data10 = pd.DataFrame(mat_file_G11_io10.get('melexisG11f10'))
G11data10 = data_merge(G11data10,147, 196, 320, 350, 484, 525, 655, 700, 825, 900)

mat_file_G11_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f11-data.mat')
G11data11 = pd.DataFrame(mat_file_G11_io11.get('melexisG11f11'))
G11data11 = data_merge(G11data11,321, 360, 484, 519, 613, 639, 763, 810, 979, 1036)

mat_file_G11_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f12-data.mat')
G11data12 = pd.DataFrame(mat_file_G11_io12.get('melexisG11f12'))
G11data12 = data_merge(G11data12,228, 275, 434, 475, 625, 670, 833, 873, 940, 1048)

mat_file_G11_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f13-data.mat')
G11data13 = pd.DataFrame(mat_file_G11_io13.get('melexisG11f13'))
G11data13 = data_merge(G11data13,197, 232, 404, 453, 636, 684, 841, 904, 1075, 1140)

mat_file_G11_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f14-data.mat')
G11data14 = pd.DataFrame(mat_file_G11_io14.get('melexisG11f14'))
G11data14 = data_merge(G11data14,265, 307, 408, 465, 585, 630, 739, 794, 943, 1019)

mat_file_G11_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f15-data.mat')
G11data15 = pd.DataFrame(mat_file_G11_io15.get('melexisG11f15'))
G11data15 = data_merge(G11data15,198, 250, 457, 494, 654, 694, 859, 921, 1108, 1229)

#result = pd.concat([data, data2,data3, data4, data5, data6, data7, data8, data9])

#print(y)
# print(df)
# f = open('./melexisG11f01.csv', 'w', encoding='utf-8', newline='')
# wr = csv.writer(f)
# wr.writerow(df, 0)
# f.close()

[[17.81 17.69 18.23 ... 20.01 18.87 19.17]
 [17.77 17.77 18.17 ... 20.03 21.55 19.19]
 [17.91 17.85 18.13 ... 20.07 20.83 19.07]
 ...
 [17.75 18.07 18.31 ... 19.67 18.79 17.57]
 [17.79 18.09 18.37 ... 19.73 18.79 17.91]
 [17.81 18.17 18.35 ... 19.71 18.77 18.17]]
17.81


In [8]:
G11dataf1 = G11data1[:760]
G11data1_test = G11data1[760:]
G11dataf2 = G11data2[:856]
G11data2_test = G11data2[856:]
G11dataf3 = G11data3[:1292]
G11data3_test = G11data3[1292:]
G11dataf4 = G11data4[:812]
G11data4_test = G11data4[812:]
G11dataf5 = G11data5[:1070]
G11data5_test = G11data5[1070:]
G11dataf6 = G11data6[:1192]
G11data6_test = G11data6[1192:]
G11dataf7 = G11data7[:1080]
G11data7_test = G11data7[1080:]
G11dataf8 = G11data8[:826]
G11data8_test = G11data8[826:]
G11dataf9 = G11data9[:798]
G11data9_test = G11data9[798:]
G11dataf10 = G11data10[:788]
G11data10_test = G11data10[788:]
G11dataf11 = G11data11[:984]
G11data11_test = G11data11[984:]
G11dataf12 = G11data12[:884]
G11data12_test = G11data12[884:]
G11dataf13 = G11data13[:1028]
G11data13_test = G11data13[1028:]
G11dataf14 = G11data14[:866]
G11data14_test = G11data14[866:]
G11dataf15 = G11data15[:986]
G11data15_test = G11data15[986:]
print(G11data1_test.shape)
print(G11data2_test.shape)
print(G11data3_test.shape)
print(G11data4_test.shape)

(120, 769)
(144, 769)
(128, 769)
(118, 769)


In [9]:
mat_file_G12_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f01-data.mat')
print(mat_file_G12_io.get('melexisG12f01'))
print(mat_file_G12_io.get('melexisG12f01')[0][0])
G12data1 = pd.DataFrame(mat_file_G12_io.get('melexisG12f01'))
G12data1 = data_merge(G12data1,673, 738, 1418, 1489, 1725, 1814, 2341, 2454, 2796, 2899)
mat_file_G12_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f02-data.mat')
G12data2 = pd.DataFrame(mat_file_G12_io2.get('melexisG12f02'))
G12data2 = data_merge(G12data2,240, 290, 533, 610, 920, 974, 1240, 1320, 1600, 1729)

mat_file_G12_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f03-data.mat')
G12data3 = pd.DataFrame(mat_file_G12_io3.get('melexisG12f03'))
G12data3 = data_merge(G12data3,217, 279, 510, 660, 1097, 1191, 1559, 1622, 1880, 1969)

mat_file_G12_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f04-data.mat')
G12data4 = pd.DataFrame(mat_file_G12_io4.get('melexisG12f04'))
G12data4 = data_merge(G12data4,449, 499, 700, 734, 893, 955, 1091, 1150, 1310, 1379)

mat_file_G12_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f05-data.mat')
G12data5 = pd.DataFrame(mat_file_G12_io5.get('melexisG12f05'))
G12data5 = data_merge(G12data5,310, 363, 539, 579, 712, 765, 902, 952, 1136, 1204)

mat_file_G12_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f06-data.mat')
G12data6 = pd.DataFrame(mat_file_G12_io6.get('melexisG12f06'))
G12data6 = data_merge(G12data6, 156, 259, 415, 469, 658, 717, 823, 950, 1040, 1099)

mat_file_G12_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f07-data.mat')
G12data7 = pd.DataFrame(mat_file_G12_io7.get('melexisG12f07'))
G12data7 = data_merge(G12data7,143, 193, 346, 388, 530, 600, 704, 759, 896, 967)

mat_file_G12_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f08-data.mat')
G12data8 = pd.DataFrame(mat_file_G12_io8.get('melexisG12f08'))
G12data8 = data_merge(G12data8,245,307,470,556,717,771,940,998,1164,1249)

mat_file_G12_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f09-data.mat')
G12data9 = pd.DataFrame(mat_file_G12_io9.get('melexisG12f09'))
G12data9 = data_merge(G12data9,155,228,340,400,511,591,704,767,934,989)

mat_file_G12_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f10-data.mat')
G12data10 = pd.DataFrame(mat_file_G12_io10.get('melexisG12f10'))
G12data10 = data_merge(G12data10,160,251,381,440,603,665,934,1005,1215,1277)

mat_file_G12_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f11-data.mat')
G12data11 = pd.DataFrame(mat_file_G12_io11.get('melexisG12f11'))
G12data11 = data_merge(G12data11,221,278,400,456,568,634,726,775,894,979)

mat_file_G12_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f12-data.mat')
G12data12 = pd.DataFrame(mat_file_G12_io12.get('melexisG12f12'))
G12data12 = data_merge(G12data12,485,570,675,720,820,870,1000,1070,1180,1259)

mat_file_G12_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f13-data.mat')
G12data13 = pd.DataFrame(mat_file_G12_io13.get('melexisG12f13'))
G12data13 = data_merge(G12data13,198,269,427,507,628,680,780,835,957,1049)

mat_file_G12_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f14-data.mat')
G12data14 = pd.DataFrame(mat_file_G12_io14.get('melexisG12f14'))
G12data14 = data_merge(G12data14,182,274,555,620,770,828,961,1030,1140,1209)

mat_file_G12_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f15-data.mat')
G12data15 = pd.DataFrame(mat_file_G12_io15.get('melexisG12f15'))
G12data15 = data_merge(G12data15,137,188,394,440,598,650,815,865,1075,1149)

[[18.73 18.79 19.11 ... 20.01 19.67 19.45]
 [18.67 18.79 19.07 ... 19.99 19.71 19.47]
 [18.63 18.73 19.05 ... 19.91 19.53 19.49]
 ...
 [18.11 18.07 18.65 ... 20.13 19.23 19.33]
 [18.05 18.07 18.59 ... 20.25 19.31 19.39]
 [18.03 18.05 18.55 ... 20.29 19.51 19.47]]
18.73


In [10]:
G12dataf1 = G12data1[:2692]
G12data1_test = G12data1[2692:]
G12dataf2 = G12data2[:1470]
G12data2_test = G12data2[1470:]
G12dataf3 = G12data3[:1790]
G12data3_test = G12data3[1790:]
G12dataf4 = G12data4[:1240]
G12data4_test = G12data4[1240:]
G12dataf5 = G12data5[:1112]
G12data5_test = G12data5[1112:]
G12dataf6 = G12data6[:980]
G12data6_test = G12data6[980:]
G12dataf7 = G12data7[:836]
G12data7_test = G12data7[836:]
G12dataf8 = G12data8[:1078]
G12data8_test = G12data8[1078:]
G12dataf9 = G12data9[:878]
G12data9_test = G12data9[878:]
G12dataf10 = G12data10[:1164]
G12data10_test = G12data10[1164:]
G12dataf11 = G12data11[:808]
G12data11_test = G12data11[808:]
G12dataf12 = G12data12[:1100]
G12data12_test = G12data12[1100:]
G12dataf13 = G12data13[:864]
G12data13_test = G12data13[864:]
G12dataf14 = G12data14[:1070]
G12data14_test = G12data14[1070:]
G12dataf15 = G12data15[:1000]
G12data15_test = G12data15[1000:]

In [11]:
mat_file_G13_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f01-data.mat')
print(mat_file_G13_io.get('melexisG13f01'))
print(mat_file_G13_io.get('melexisG13f01')[0][0])
G13data1 = pd.DataFrame(mat_file_G13_io.get('melexisG13f01'))
G13data1 = data_merge(G13data1,122, 180, 288, 380, 478, 580, 680, 794, 892, 982)

mat_file_G13_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f02-data.mat')
G13data2 = pd.DataFrame(mat_file_G13_io2.get('melexisG13f02'))
G13data2 = data_merge(G13data2,100, 155, 298, 372, 510, 570, 712, 774, 880, 943)

mat_file_G13_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f03-data.mat')
G13data3 = pd.DataFrame(mat_file_G13_io3.get('melexisG13f03'))
G13data3 = data_merge(G13data3,78, 150, 304, 364, 583, 670, 834, 880, 1028, 1090)

mat_file_G13_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f04-data.mat')
G13data4 = pd.DataFrame(mat_file_G13_io4.get('melexisG13f04'))
G13data4 = data_merge(G13data4,79, 140, 279, 320, 443, 497, 615, 662, 824, 873)

mat_file_G13_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f05-data.mat')
G13data5 = pd.DataFrame(mat_file_G13_io5.get('melexisG13f05'))
G13data5 = data_merge(G13data5,109, 159, 317, 377, 511, 565, 743, 805, 920, 988)

mat_file_G13_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f06-data.mat')
G13data6 = pd.DataFrame(mat_file_G13_io6.get('melexisG13f06'))
G13data6 = data_merge(G13data6, 114, 194, 354, 410, 570, 620, 762, 799, 978, 1040)

mat_file_G13_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f07-data.mat')
G13data7 = pd.DataFrame(mat_file_G13_io7.get('melexisG13f07'))
G13data7 = data_merge(G13data7,80, 200, 296, 338, 525, 573, 748, 803, 1200, 1260)

mat_file_G13_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f08-data.mat')
G13data8 = pd.DataFrame(mat_file_G13_io8.get('melexisG13f08'))
G13data8 = data_merge(G13data8,88, 134, 247, 289, 451, 510, 668, 730, 833, 884)

mat_file_G13_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f09-data.mat')
G13data9 = pd.DataFrame(mat_file_G13_io9.get('melexisG13f09'))
G13data9 = data_merge(G13data9,119, 189, 342, 408, 555, 629, 869, 922, 1084, 1144)

mat_file_G13_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f10-data.mat')
G13data10 = pd.DataFrame(mat_file_G13_io10.get('melexisG13f10'))
G13data10 = data_merge(G13data10,118, 190, 350, 420, 560, 660, 873, 973, 1087, 1166)

mat_file_G13_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f11-data.mat')
G13data11 = pd.DataFrame(mat_file_G13_io11.get('melexisG13f11'))
G13data11 = data_merge(G13data11,63, 120, 290, 333, 530, 590, 718, 770, 911, 968)

mat_file_G13_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f12-data.mat')
G13data12 = pd.DataFrame(mat_file_G13_io12.get('melexisG13f12'))
G13data12 = data_merge(G13data12,144, 230, 450, 520, 655, 730, 863, 928, 1047, 1114)

mat_file_G13_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f13-data.mat')
G13data13 = pd.DataFrame(mat_file_G13_io13.get('melexisG13f13'))
G13data13 = data_merge(G13data13,169, 246, 410, 535, 692, 750, 905, 970, 1157, 1220)

mat_file_G13_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f14-data.mat')
G13data14 = pd.DataFrame(mat_file_G13_io14.get('melexisG13f14'))
G13data14 = data_merge(G13data14,121, 197, 372, 434, 588, 651, 794, 861, 1037, 1131)

mat_file_G13_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f15-data.mat')
G13data15 = pd.DataFrame(mat_file_G13_io15.get('melexisG13f15'))
G13data15 = data_merge(G13data15,194, 272, 644, 679, 960, 1023, 1234, 1303, 1518, 1590)

[[18.97 18.83 18.85 ... 20.45 20.09 19.43]
 [18.97 18.85 18.85 ... 20.37 20.01 19.49]
 [18.97 18.87 19.05 ... 20.51 20.01 19.49]
 ...
 [18.87 18.91 19.01 ... 20.21 19.37 20.29]
 [18.83 18.99 18.99 ... 20.35 19.41 20.33]
 [18.79 18.95 18.95 ... 20.31 19.43 20.35]]
18.97


In [12]:
G13dataf1 = G13data1[:828]
G13data1_test = G13data1[828:]
G13dataf2 = G13data2[:832]
G13data2_test = G13data2[832:]
G13dataf3 = G13data3[:974]
G13data3_test = G13data3[974:]
G13dataf4 = G13data4[:810]
G13data4_test = G13data4[810:]
G13dataf5 = G13data5[:877]
G13data5_test = G13data5[877:]
G13dataf6 = G13data6[:943]
G13data6_test = G13data6[943:]
G13dataf7 = G13data7[:1168]
G13data7_test = G13data7[1168:]
G13dataf8 = G13data8[:836]
G13data8_test = G13data8[836:]
G13dataf9 = G13data9[:1084]
G13data9_test = G13data9[1084:]
G13dataf10 = G13data10[:1080]
G13data10_test = G13data10[1080:]
G13dataf11 = G13data11[:889]
G13data11_test = G13data11[889:]
G13dataf12 = G13data12[:994]
G13data12_test = G13data12[994:]
G13dataf13 = G13data13[:1112]
G13data13_test = G13data13[1112:]
G13dataf14 = G13data14[:1025]
G13data14_test = G13data14[1025:]
G13dataf15 = G13data15[:1468]
G13data15_test = G13data15[1468:]
print(G13data2_test.shape)

(128, 769)


In [13]:
mat_file_G21_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f01-data.mat')
print(mat_file_G21_io.get('melexisG21f01'))
print(mat_file_G21_io.get('melexisG21f01')[0][0])
G21data1 = pd.DataFrame(mat_file_G21_io.get('melexisG21f01'))
G21data1 = data_merge(G21data1,57, 120, 218, 290, 408, 465, 566, 609, 719, 759)

mat_file_G21_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f02-data.mat')
G21data2 = pd.DataFrame(mat_file_G21_io2.get('melexisG21f02'))
G21data2 = data_merge(G21data2,147,192, 321,360, 471,510, 639,680, 809,849)

mat_file_G21_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f03-data.mat')
G21data3 = pd.DataFrame(mat_file_G21_io3.get('melexisG21f03'))
G21data3 = data_merge(G21data3,45, 90, 190, 239, 330, 375, 480, 523, 631, 679)

mat_file_G21_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f04-data.mat')
G21data4 = pd.DataFrame(mat_file_G21_io4.get('melexisG21f04'))
G21data4 = data_merge(G21data4,125, 160, 283, 331, 439, 486, 604, 666, 760, 839)

mat_file_G21_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f05-data.mat')
G21data5 = pd.DataFrame(mat_file_G21_io5.get('melexisG21f05'))
G21data5 = data_merge(G21data5,150, 213, 420, 462, 698, 752, 991, 1027, 1189, 1222)

mat_file_G21_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f06-data.mat')
G21data6 = pd.DataFrame(mat_file_G21_io6.get('melexisG21f06'))
G21data6 = data_merge(G21data6, 148, 193, 390, 437, 637, 680, 887, 925, 1117, 1188)

mat_file_G21_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f07-data.mat')
G21data7 = pd.DataFrame(mat_file_G21_io7.get('melexisG21f07'))
G21data7 = data_merge(G21data7,89, 135, 300, 347, 483, 525, 716, 751, 933, 985)

mat_file_G21_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f08-data.mat')
G21data8 = pd.DataFrame(mat_file_G21_io8.get('melexisG21f08'))
G21data8 = data_merge(G21data8,131, 181, 281, 305, 451, 481, 611, 665, 776, 829)

mat_file_G21_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f09-data.mat')
G21data9 = pd.DataFrame(mat_file_G21_io9.get('melexisG21f09'))
G21data9 = data_merge(G21data9,160, 197, 323, 376, 475, 503, 617, 658, 751, 791)

mat_file_G21_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f10-data.mat')
G21data10 = pd.DataFrame(mat_file_G21_io10.get('melexisG21f10'))
G21data10 = data_merge(G21data10,41, 100, 240, 287, 447, 480, 630, 672, 800, 840)

mat_file_G21_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f11-data.mat')
G21data11 = pd.DataFrame(mat_file_G21_io11.get('melexisG21f11'))
G21data11 = data_merge(G21data11,136, 182, 321, 341, 562, 603, 741, 780, 1004, 1072)

mat_file_G21_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f12-data.mat')
G21data12 = pd.DataFrame(mat_file_G21_io12.get('melexisG21f12'))
G21data12 = data_merge(G21data12,79, 112, 250, 302, 435, 483, 581, 640, 752, 809)

mat_file_G21_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f13-data.mat')
G21data13 = pd.DataFrame(mat_file_G21_io13.get('melexisG21f13'))
G21data13 = data_merge(G21data13,40, 92, 194, 269, 348, 415, 522, 579, 682, 727)

mat_file_G21_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f14-data.mat')
G21data14 = pd.DataFrame(mat_file_G21_io14.get('melexisG21f14'))
G21data14 = data_merge(G21data14,148, 191, 319, 374, 495, 546, 691, 752, 892, 945)

mat_file_G21_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f15-data.mat')
G21data15 = pd.DataFrame(mat_file_G21_io15.get('melexisG21f15'))
G21data15 = data_merge(G21data15,120, 141, 348, 389, 548, 584, 736, 767, 915, 957)

[[17.97 18.07 17.79 ... 19.89 18.61 18.41]
 [18.01 18.07 17.87 ... 19.77 18.57 18.39]
 [18.03 18.09 17.97 ... 19.65 18.55 18.35]
 ...
 [17.79 18.01 17.79 ... 19.31 18.47 18.11]
 [17.87 17.93 17.85 ... 19.33 18.39 18.05]
 [17.79 17.87 17.77 ... 19.27 18.15 18.19]]
17.97


In [14]:
G21dataf1 = G21data1[:678]
G21data1_test = G21data1[678:]
G21dataf2 = G21data2[:774]
G21data2_test = G21data2[774:]
G21dataf3 = G21data3[:595]
G21data3_test = G21data3[595:]
G21dataf4 = G21data4[:682]
G21data4_test = G21data4[682:]
G21dataf5 = G21data5[:1162]
G21data5_test = G21data5[1162:]
G21dataf6 = G21data6[:1060]
G21data6_test = G21data6[1060:]
G21dataf7 = G21data7[:911]
G21data7_test = G21data7[911:]
G21dataf8 = G21data8[:727]
G21data8_test = G21data8[727:]
G21dataf9 = G21data9[:729]
G21data9_test = G21data9[729:]
G21dataf10 = G21data10[:803]
G21data10_test = G21data10[803:]
G21dataf11 = G21data11[:952]
G21data11_test = G21data11[952:]
G21dataf12 = G21data12[:694]
G21data12_test = G21data12[694:]
G21dataf13 = G21data13[:648]
G21data13_test = G21data13[648:]
G21dataf14 = G21data14[:893]
G21data14_test = G21data14[893:]
G21dataf15 = G21data15[:884]
G21data15_test = G21data15[884:]

In [15]:
mat_file_G22_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f01-data.mat')
print(mat_file_G22_io.get('melexisG22f01'))
print(mat_file_G22_io.get('melexisG22f01')[0][0])
G22data1 = pd.DataFrame(mat_file_G22_io.get('melexisG22f01'))
G22data1 = data_merge(G22data1,90, 112, 228, 254, 382, 401, 525, 550, 660, 699)

mat_file_G22_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f02-data.mat')
G22data2 = pd.DataFrame(mat_file_G22_io2.get('melexisG22f02'))
G22data2 = data_merge(G22data2,102, 138, 230, 257, 365, 391, 496, 526, 699, 727)

mat_file_G22_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f03-data.mat')
G22data3 = pd.DataFrame(mat_file_G22_io3.get('melexisG22f03'))
G22data3 = data_merge(G22data3,65, 89, 177, 207, 325, 365, 426, 448, 572, 614)

mat_file_G22_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f04-data.mat')
G22data4 = pd.DataFrame(mat_file_G22_io4.get('melexisG22f04'))
G22data4 = data_merge(G22data4,66, 89, 171, 199, 259, 285, 367, 389, 476, 509)

mat_file_G22_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f05-data.mat')
G22data5 = pd.DataFrame(mat_file_G22_io5.get('melexisG22f05'))
G22data5 = data_merge(G22data5,0, 33, 142, 250, 550, 586, 705, 743, 1007, 1080)

mat_file_G22_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f06-data.mat')
G22data6 = pd.DataFrame(mat_file_G22_io6.get('melexisG22f06'))
G22data6 = data_merge(G22data6, 47, 88, 260, 282, 465, 498, 620, 671, 847, 888)

mat_file_G22_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f07-data.mat')
G22data7 = pd.DataFrame(mat_file_G22_io7.get('melexisG22f07'))
G22data7 = data_merge(G22data7,235, 274, 398, 430, 578, 608, 806, 840, 992, 1043)

mat_file_G22_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f08-data.mat')
G22data8 = pd.DataFrame(mat_file_G22_io8.get('melexisG22f08'))
G22data8 = data_merge(G22data8,172, 210, 347, 380, 462, 485, 577, 600, 678, 708)

mat_file_G22_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f09-data.mat')
G22data9 = pd.DataFrame(mat_file_G22_io9.get('melexisG22f09'))
G22data9 = data_merge(G22data9,100, 130, 218, 243, 332, 373, 428, 458, 527, 559)

mat_file_G22_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f10-data.mat')
G22data10 = pd.DataFrame(mat_file_G22_io10.get('melexisG22f10'))
G22data10 = data_merge(G22data10,54, 84, 208, 240, 350, 370, 490, 513, 610, 637)

mat_file_G22_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f11-data.mat')
G22data11 = pd.DataFrame(mat_file_G22_io11.get('melexisG22f11'))
G22data11 = data_merge(G22data11,20, 57, 179, 214, 385, 430, 631, 679, 870, 925)

mat_file_G22_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f12-data.mat')
G22data12 = pd.DataFrame(mat_file_G22_io12.get('melexisG22f12'))
G22data12 = data_merge(G22data12,87, 110, 213, 231, 317, 351, 454, 475, 565, 587)

mat_file_G22_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f13-data.mat')
G22data13 = pd.DataFrame(mat_file_G22_io13.get('melexisG22f13'))
G22data13 = data_merge(G22data13,145, 171, 269, 300, 405, 440, 529, 563, 647, 689)

mat_file_G22_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f14-data.mat')
G22data14 = pd.DataFrame(mat_file_G22_io14.get('melexisG22f14'))
G22data14 = data_merge(G22data14,67, 88, 192, 220, 330, 354, 454, 481, 577, 600)

mat_file_G22_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f15-data.mat')
G22data15 = pd.DataFrame(mat_file_G22_io15.get('melexisG22f15'))
G22data15 = data_merge(G22data15,77, 110, 224, 254, 388, 416, 540, 571, 683, 729)

[[17.85 17.83 17.93 ... 18.95 18.01 17.81]
 [17.83 17.83 17.95 ... 18.99 18.11 17.75]
 [17.79 17.73 17.95 ... 19.01 18.07 17.67]
 ...
 [17.51 17.67 17.51 ... 19.17 18.09 18.33]
 [17.37 17.69 17.49 ... 19.11 18.07 18.31]
 [17.39 17.71 17.47 ... 19.07 18.07 18.53]]
17.85


In [16]:
G22dataf1 = G22data1[:635]
G22data1_test = G22data1[635:]
G22dataf2 = G22data2[:709]
G22data2_test = G22data2[709:]
G22dataf3 = G22data3[:534]
G22data3_test = G22data3[534:]
G22dataf4 = G22data4[:453]
G22data4_test = G22data4[453:]
G22dataf5 = G22data5[:1052]
G22data5_test = G22data5[1052:]
G22dataf6 = G22data6[:858]
G22data6_test = G22data6[858:]
G22dataf7 = G22data7[:992]
G22data7_test = G22data7[992:]
G22dataf8 = G22data8[:688]
G22data8_test = G22data8[688:]
G22dataf9 = G22data9[:492]
G22data9_test = G22data9[492:]
G22dataf10 = G22data10[:610]
G22data10_test = G22data10[610:]
G22dataf11 = G22data11[:818]
G22data11_test = G22data11[818:]
G22dataf12 = G22data12[:566]
G22data12_test = G22data12[566:]
G22dataf13 = G22data13[:604]
G22data13_test = G22data13[604:]
G22dataf14 = G22data14[:587]
G22data14_test = G22data14[587:]
G22dataf15 = G22data15[:636]
G22data15_test = G22data15[636:]

In [17]:
mat_file_G23_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f01-data.mat')
print(mat_file_G23_io.get('melexisG23f01'))
print(mat_file_G23_io.get('melexisG23f01')[0][0])
G23data1 = pd.DataFrame(mat_file_G23_io.get('melexisG23f01'))
G23data1 = data_merge(G23data1,98, 194, 337, 430, 538, 600, 736, 793, 925, 999)

mat_file_G23_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f02-data.mat')
G23data2 = pd.DataFrame(mat_file_G23_io2.get('melexisG23f02'))
G23data2 = data_merge(G23data2,76, 132, 261, 312, 447, 497, 630, 682, 790, 838)

mat_file_G23_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f03-data.mat')
G23data3 = pd.DataFrame(mat_file_G23_io3.get('melexisG23f03'))
G23data3 = data_merge(G23data3,67, 136, 230, 310, 431, 500, 609, 672, 789, 850)

mat_file_G23_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f04-data.mat')
G23data4 = pd.DataFrame(mat_file_G23_io4.get('melexisG23f04'))
G23data4 = data_merge(G23data4,86, 150, 265, 320, 414, 463, 585, 642, 718, 759)

mat_file_G23_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f05-data.mat')
G23data5 = pd.DataFrame(mat_file_G23_io5.get('melexisG23f05'))
G23data5 = data_merge(G23data5,144, 176, 341, 374, 626, 675, 902, 941, 1185, 1243)

mat_file_G23_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f06-data.mat')
G23data6 = pd.DataFrame(mat_file_G23_io6.get('melexisG23f06'))
G23data6 = data_merge(G23data6, 56, 158, 463, 501, 746, 820, 1004, 1070, 1215, 1269)

mat_file_G23_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f07-data.mat')
G23data7 = pd.DataFrame(mat_file_G23_io7.get('melexisG23f07'))
G23data7 = data_merge(G23data7,94, 145, 325, 377, 552, 594, 723, 790, 950, 999)

mat_file_G23_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f08-data.mat')
G23data8 = pd.DataFrame(mat_file_G23_io8.get('melexisG23f08'))
G23data8 = data_merge(G23data8,32, 92, 228, 267, 380, 436, 542, 595, 711, 759)

mat_file_G23_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f09-data.mat')
G23data9 = pd.DataFrame(mat_file_G23_io9.get('melexisG23f09'))
G23data9 = data_merge(G23data9,148,204, 330, 396, 571, 626, 749, 799, 917, 969)

mat_file_G23_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f10-data.mat')
G23data10 = pd.DataFrame(mat_file_G23_io10.get('melexisG23f10'))
G23data10 = data_merge(G23data10,49, 140, 289, 365, 458, 530, 634, 695, 834, 889)

mat_file_G23_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f11-data.mat')
G23data11 = pd.DataFrame(mat_file_G23_io11.get('melexisG23f11'))
G23data11 = data_merge(G23data11,64, 140, 254, 311, 476, 554, 664, 733, 912, 969)

mat_file_G23_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f12-data.mat')
G23data12 = pd.DataFrame(mat_file_G23_io12.get('melexisG23f12'))
G23data12 = data_merge(G23data12,56, 101, 204, 262, 366, 430, 517, 580, 666, 719)

mat_file_G23_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f13-data.mat')
G23data13 = pd.DataFrame(mat_file_G23_io13.get('melexisG23f13'))
G23data13 = data_merge(G23data13,75, 160, 315, 393, 510, 580, 678, 744, 857, 909)

mat_file_G23_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f14-data.mat')
G23data14 = pd.DataFrame(mat_file_G23_io14.get('melexisG23f14'))
G23data14 = data_merge(G23data14,79, 126, 250, 304, 443, 492, 608, 677, 804, 869)

mat_file_G23_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f15-data.mat')
G23data15 = pd.DataFrame(mat_file_G23_io15.get('melexisG23f15'))
G23data15 = data_merge(G23data15,114, 170, 274, 325, 459, 578, 719, 797, 935, 989)

[[17.67 17.75 17.59 ... 18.83 18.13 18.57]
 [17.75 17.83 17.55 ... 18.79 18.01 18.43]
 [17.83 17.93 17.53 ... 18.77 17.93 18.33]
 ...
 [17.53 17.37 17.91 ... 19.03 17.65 15.91]
 [17.49 17.41 17.91 ... 19.13 17.67 15.91]
 [17.45 17.43 17.89 ... 19.13 17.77 15.89]]
17.67


In [18]:
G23dataf1 = G23data1[:850]
G23data1_test = G23data1[850:]
G23dataf2 = G23data2[:772]
G23data2_test = G23data2[772:]
G23dataf3 = G23data3[:736]
G23data3_test = G23data3[736:]
G23dataf4 = G23data4[:676]
G23data4_test = G23data4[676:]
G23dataf5 = G23data5[:1132]
G23data5_test = G23data5[1132:]
G23dataf6 = G23data6[:1160]
G23data6_test = G23data6[1160:]
G23dataf7 = G23data7[:900]
G23data7_test = G23data7[900:]
G23dataf8 = G23data8[:660]
G23data8_test = G23data8[660:]
G23dataf9 = G23data9[:850]
G23data9_test = G23data9[850:]
G23dataf10 = G23data10[:780]
G23data10_test = G23data10[780:]
G23dataf11 = G23data11[:860]
G23data11_test = G23data11[860:]
G23dataf12 = G23data12[:610]
G23data12_test = G23data12[610:]
G23dataf13 = G23data13[:800]
G23data13_test = G23data13[800:]
G23dataf14 = G23data14[:740]
G23data14_test = G23data14[740:]
G23dataf15 = G23data15[:880]
G23data15_test = G23data15[880:]
print(G23data15_test.shape)

(110, 769)


In [19]:
result = pd.concat([G11dataf1, G11dataf2,G11dataf3, G11dataf4, G11dataf5, G11dataf6, G11dataf7, G11dataf8, G11dataf9, G11dataf10,
                    G11dataf11, G11dataf12, G11dataf13, G11dataf14, G11dataf15,G12dataf1, G12dataf2,G12dataf3, G12dataf4, G12dataf5, 
                    G12dataf6, G12dataf7, G12dataf8, G12dataf9, G12dataf10, G12dataf11, G12dataf12, G12dataf13, G12dataf14, G12dataf15,
                    G13dataf1, G13dataf2,G13dataf3, G13dataf4, G13dataf5, G13dataf6, G13dataf7, G13dataf8, G13dataf9, G13dataf10,
                    G13dataf11, G13dataf12,G13dataf13, G13dataf14, G13dataf15,G21dataf1, G21dataf2,G21dataf3, G21dataf4, G21dataf5, 
                    G21dataf6, G21dataf7, G21dataf8, G21dataf9, G21dataf10, G21dataf11, G21dataf12, G21dataf13, G21dataf14, G21dataf15,
                    G22dataf1, G22dataf2,G22dataf3, G22dataf4, G22dataf5, G22dataf6, G22dataf7, G22dataf8, G22dataf9, G22dataf10,
                    G22dataf11, G22dataf12, G22dataf13, G22dataf14, G22dataf15,G23dataf1, G23dataf2,G23dataf3, G23dataf4, G23dataf5, 
                    G23dataf6, G23dataf7, G23dataf8, G23dataf9, G23dataf10, G23dataf11, G23dataf12, G23dataf13, G23dataf14, G23dataf15])
print(result.shape)
X, y = result.drop(['label'], axis=1), result['label']
print(X.shape)
print(y.shape)

(82056, 769)
(82056, 768)
(82056,)


In [20]:
result_test = pd.concat([G11data1_test, G11data2_test,G11data3_test, G11data4_test, G11data5_test, G11data6_test, G11data7_test, G11data8_test, G11data9_test, G11data10_test, G11data11_test, G11data12_test, 
                    G11data13_test, G11data14_test, G11data15_test,G12data1_test, G12data2_test,G12data3_test, G12data4_test, G12data5_test, G12data6_test, G12data7_test, G12data8_test, G12data9_test, 
                    G12data10_test, G12data11_test, G12data12_test,G12data13_test, G12data14_test, G12data15_test,G13data1_test, G13data2_test,G13data3_test, G13data4_test, G13data5_test, G13data6_test, 
                    G13data7_test, G13data8_test, G13data9_test, G13data10_test, G13data11_test, G13data12_test,G13data13_test, G13data14_test, G13data15_test,G21data1_test, G21data2_test,G21data3_test, 
                    G21data4_test, G21data5_test, G21data6_test, G21data7_test, G21data8_test, G21data9_test, G21data10_test, G21data11_test, G21data12_test,G21data13_test, G21data14_test, G21data15_test,
                   G22data1_test, G22data2_test,G22data3_test, G22data4_test, G22data5_test, G22data6_test, G22data7_test, G22data8_test, G22data9_test, G22data10_test, G22data11_test, G22data12_test,
                    G22data13_test, G22data14_test, G22data15_test,G23data1_test, G23data2_test,G23data3_test, G23data4_test, G23data5_test, G23data6_test, G23data7_test, G23data8_test, G23data9_test, 
                    G23data10_test, G23data11_test, G23data12_test, G23data13_test, G23data14_test, G23data15_test])
X_test, y_test = result_test.drop(['label'],axis=1), result_test['label']
print(X_test.shape)
print(y_test.shape)
print(result_test.shape)

(11112, 768)
(11112,)
(11112, 769)


In [21]:
X = X.where(pd.notnull(X), X.mean(), axis='columns')
print(X.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
763    0
764    0
765    0
766    0
767    0
Length: 768, dtype: int64


In [22]:
G11data1_test=G11data1_test.where(pd.notnull(G11data1_test),G11data1_test.mean(), axis='columns')
G11data2_test=G11data2_test.where(pd.notnull(G11data2_test),G11data2_test.mean(), axis='columns')
G11data3_test=G11data3_test.where(pd.notnull(G11data3_test),G11data3_test.mean(), axis='columns')
G11data4_test=G11data4_test.where(pd.notnull(G11data4_test),G11data4_test.mean(), axis='columns')
G11data5_test=G11data5_test.where(pd.notnull(G11data5_test),G11data5_test.mean(), axis='columns')
G11data6_test=G11data6_test.where(pd.notnull(G11data6_test),G11data6_test.mean(), axis='columns')
G11data7_test=G11data7_test.where(pd.notnull(G11data7_test),G11data7_test.mean(), axis='columns')
G11data8_test=G11data8_test.where(pd.notnull(G11data8_test),G11data8_test.mean(), axis='columns')
G11data9_test=G11data9_test.where(pd.notnull(G11data9_test),G11data9_test.mean(), axis='columns')
G11data10_test=G11data10_test.where(pd.notnull(G11data10_test),G11data10_test.mean(), axis='columns')
G11data11_test=G11data11_test.where(pd.notnull(G11data11_test),G11data11_test.mean(), axis='columns')
G11data12_test=G11data12_test.where(pd.notnull(G11data12_test),G11data12_test.mean(), axis='columns')
G11data13_test=G11data13_test.where(pd.notnull(G11data13_test),G11data13_test.mean(), axis='columns')
G11data14_test=G11data14_test.where(pd.notnull(G11data14_test),G11data14_test.mean(), axis='columns')
G11data15_test=G11data15_test.where(pd.notnull(G11data15_test),G11data15_test.mean(), axis='columns')
G12data1_test=G12data1_test.where(pd.notnull(G12data1_test),G12data1_test.mean(), axis='columns')
G12data2_test=G12data2_test.where(pd.notnull(G12data2_test),G12data2_test.mean(), axis='columns')
G12data3_test=G12data3_test.where(pd.notnull(G12data3_test),G12data3_test.mean(), axis='columns')
G12data4_test=G12data4_test.where(pd.notnull(G12data4_test),G12data4_test.mean(), axis='columns')
G12data5_test=G12data5_test.where(pd.notnull(G12data5_test),G12data5_test.mean(), axis='columns')
G12data6_test=G12data6_test.where(pd.notnull(G12data6_test),G12data6_test.mean(), axis='columns')
G12data7_test=G12data7_test.where(pd.notnull(G12data7_test),G12data7_test.mean(), axis='columns')
G12data8_test=G12data8_test.where(pd.notnull(G12data8_test),G12data8_test.mean(), axis='columns')
G12data9_test=G12data9_test.where(pd.notnull(G12data9_test),G12data9_test.mean(), axis='columns')
G12data10_test=G12data10_test.where(pd.notnull(G12data10_test),G12data10_test.mean(), axis='columns')
G12data11_test=G12data11_test.where(pd.notnull(G12data11_test),G12data11_test.mean(), axis='columns')
G12data12_test=G12data12_test.where(pd.notnull(G12data12_test),G12data12_test.mean(), axis='columns')
G12data13_test=G12data13_test.where(pd.notnull(G12data13_test),G12data13_test.mean(), axis='columns')
G12data14_test=G12data14_test.where(pd.notnull(G12data14_test),G12data14_test.mean(), axis='columns')
G12data15_test=G12data15_test.where(pd.notnull(G12data15_test),G12data15_test.mean(), axis='columns')
G13data1_test=G13data1_test.where(pd.notnull(G13data1_test),G13data1_test.mean(), axis='columns')
G13data2_test=G13data2_test.where(pd.notnull(G13data2_test),G13data2_test.mean(), axis='columns')
G13data3_test=G13data3_test.where(pd.notnull(G13data3_test),G13data3_test.mean(), axis='columns')
G13data4_test=G13data4_test.where(pd.notnull(G13data4_test),G13data4_test.mean(), axis='columns')
G13data5_test=G13data5_test.where(pd.notnull(G13data5_test),G13data5_test.mean(), axis='columns')
G13data6_test=G13data6_test.where(pd.notnull(G13data6_test),G13data6_test.mean(), axis='columns')
G13data7_test=G13data7_test.where(pd.notnull(G13data7_test),G13data7_test.mean(), axis='columns')
G13data8_test=G13data8_test.where(pd.notnull(G13data8_test),G13data8_test.mean(), axis='columns')
G13data9_test=G13data9_test.where(pd.notnull(G13data9_test),G13data9_test.mean(), axis='columns')
G13data10_test=G13data10_test.where(pd.notnull(G13data10_test),G13data10_test.mean(), axis='columns')
G13data11_test=G13data11_test.where(pd.notnull(G13data11_test),G13data11_test.mean(), axis='columns')
G13data12_test=G13data12_test.where(pd.notnull(G13data12_test),G13data12_test.mean(), axis='columns')
G13data13_test=G13data13_test.where(pd.notnull(G13data13_test),G13data13_test.mean(), axis='columns')
G13data14_test=G13data14_test.where(pd.notnull(G13data14_test),G13data14_test.mean(), axis='columns')
G13data15_test=G13data15_test.where(pd.notnull(G13data15_test),G13data15_test.mean(), axis='columns')
G21data1_test=G21data1_test.where(pd.notnull(G21data1_test),G21data1_test.mean(), axis='columns')
G21data2_test=G21data2_test.where(pd.notnull(G21data2_test),G21data2_test.mean(), axis='columns')
G21data3_test=G21data3_test.where(pd.notnull(G21data3_test),G21data3_test.mean(), axis='columns')
G21data4_test=G21data4_test.where(pd.notnull(G21data4_test),G21data4_test.mean(), axis='columns')
G21data5_test=G21data5_test.where(pd.notnull(G21data5_test),G21data5_test.mean(), axis='columns')
G21data6_test=G21data6_test.where(pd.notnull(G21data6_test),G21data6_test.mean(), axis='columns')
G21data7_test=G21data7_test.where(pd.notnull(G21data7_test),G21data7_test.mean(), axis='columns')
G21data8_test=G21data8_test.where(pd.notnull(G21data8_test),G21data8_test.mean(), axis='columns')
G21data9_test=G21data9_test.where(pd.notnull(G21data9_test),G21data9_test.mean(), axis='columns')
G21data10_test=G21data10_test.where(pd.notnull(G21data10_test),G21data10_test.mean(), axis='columns')
G21data11_test=G21data11_test.where(pd.notnull(G21data11_test),G21data11_test.mean(), axis='columns')
G21data12_test=G21data12_test.where(pd.notnull(G21data12_test),G21data12_test.mean(), axis='columns')
G21data13_test=G21data13_test.where(pd.notnull(G21data13_test),G21data13_test.mean(), axis='columns')
G21data14_test=G21data14_test.where(pd.notnull(G21data14_test),G21data14_test.mean(), axis='columns')
G21data15_test=G21data15_test.where(pd.notnull(G21data15_test),G21data15_test.mean(), axis='columns')
G22data1_test=G22data1_test.where(pd.notnull(G22data1_test),G22data1_test.mean(), axis='columns')
G22data2_test=G22data2_test.where(pd.notnull(G22data2_test),G22data2_test.mean(), axis='columns')
G22data3_test=G22data3_test.where(pd.notnull(G22data3_test),G22data3_test.mean(), axis='columns')
G22data4_test=G22data4_test.where(pd.notnull(G22data4_test),G22data4_test.mean(), axis='columns')
G22data5_test=G22data5_test.where(pd.notnull(G22data5_test),G22data5_test.mean(), axis='columns')
G22data6_test=G22data6_test.where(pd.notnull(G22data6_test),G22data6_test.mean(), axis='columns')
G22data7_test=G22data7_test.where(pd.notnull(G22data7_test),G22data7_test.mean(), axis='columns')
G22data8_test=G22data8_test.where(pd.notnull(G22data8_test),G22data8_test.mean(), axis='columns')
G22data9_test=G22data9_test.where(pd.notnull(G22data9_test),G22data9_test.mean(), axis='columns')
G22data10_test=G22data10_test.where(pd.notnull(G22data10_test),G22data10_test.mean(), axis='columns')
G22data11_test=G22data11_test.where(pd.notnull(G22data11_test),G22data11_test.mean(), axis='columns')
G22data12_test=G22data12_test.where(pd.notnull(G22data12_test),G22data12_test.mean(), axis='columns')
G22data13_test=G22data13_test.where(pd.notnull(G22data13_test),G22data13_test.mean(), axis='columns')
G22data14_test=G22data14_test.where(pd.notnull(G22data14_test),G22data14_test.mean(), axis='columns')
G22data15_test=G22data15_test.where(pd.notnull(G22data15_test),G22data15_test.mean(), axis='columns')
G23data1_test=G23data1_test.where(pd.notnull(G23data1_test),G23data1_test.mean(), axis='columns')
G23data2_test=G23data2_test.where(pd.notnull(G23data2_test),G23data2_test.mean(), axis='columns')
G23data3_test=G23data3_test.where(pd.notnull(G23data3_test),G23data3_test.mean(), axis='columns')
G23data4_test=G23data4_test.where(pd.notnull(G23data4_test),G23data4_test.mean(), axis='columns')
G23data5_test=G23data5_test.where(pd.notnull(G23data5_test),G23data5_test.mean(), axis='columns')
G23data6_test=G23data6_test.where(pd.notnull(G23data6_test),G23data6_test.mean(), axis='columns')
G23data7_test=G23data7_test.where(pd.notnull(G23data7_test),G23data7_test.mean(), axis='columns')
G23data8_test=G23data8_test.where(pd.notnull(G23data8_test),G23data8_test.mean(), axis='columns')
G23data9_test=G23data9_test.where(pd.notnull(G23data9_test),G23data9_test.mean(), axis='columns')
G23data10_test=G23data10_test.where(pd.notnull(G23data10_test),G23data10_test.mean(), axis='columns')
G23data11_test=G23data11_test.where(pd.notnull(G23data11_test),G23data11_test.mean(), axis='columns')
G23data12_test=G23data12_test.where(pd.notnull(G23data12_test),G23data12_test.mean(), axis='columns')
G23data13_test=G23data13_test.where(pd.notnull(G23data13_test),G23data13_test.mean(), axis='columns')
G23data14_test=G23data14_test.where(pd.notnull(G23data14_test),G23data14_test.mean(), axis='columns')
G23data15_test=G23data15_test.where(pd.notnull(G23data15_test),G23data15_test.mean(), axis='columns')

In [23]:
X = X.where(pd.notnull(X), X.mean(), axis='columns')
print(X.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
763    0
764    0
765    0
766    0
767    0
Length: 768, dtype: int64


In [24]:
X_test = X_test.where(pd.notnull(X_test), X_test.mean(), axis='columns')

In [25]:
X_train, y_train = X, y

In [26]:
np.set_printoptions(threshold=100000)

In [27]:
X_train.reset_index(drop=True, inplace= True)

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train[:] = scaler.fit_transform(X_train[:])
X_test[:] = scaler.transform(X_test[:])

In [29]:
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()

In [30]:
X_train= X_train.reshape(82056, 24, 32, 1)
X_test = X_test.reshape(11112, 24, 32, 1)

In [63]:
pre_list22 = model.predict(X_train)

In [64]:
pre_list22

array([[2.07623270e-05],
       [1.54401096e-05],
       [2.51416041e-05],
       [2.01778003e-05],
       [1.26752275e-05],
       [9.28468125e-06],
       [7.39380766e-06],
       [6.33270292e-06],
       [5.62386549e-06],
       [4.39129826e-06],
       [2.67603900e-06],
       [2.66710140e-06],
       [2.74887407e-06],
       [2.96536632e-06],
       [4.00236058e-06],
       [3.03738443e-06],
       [3.41012083e-06],
       [2.75641287e-06],
       [2.60675210e-06],
       [2.14107740e-06],
       [1.63823120e-06],
       [1.17015429e-06],
       [8.27633187e-07],
       [1.04888261e-06],
       [1.08175152e-06],
       [1.00687350e-06],
       [1.08298616e-06],
       [1.35654045e-06],
       [1.04812261e-06],
       [1.13418162e-06],
       [1.62148797e-06],
       [2.19108438e-06],
       [3.10862515e-06],
       [4.16813100e-06],
       [7.54033363e-06],
       [9.06723471e-06],
       [9.43944997e-06],
       [1.69050581e-05],
       [1.88728991e-05],
       [7.96500353e-06],


In [31]:
pre_list = model.predict_proba(X_test)

C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\sequential.py:430: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


In [32]:
pre_list = pre_list.reshape(-1)

In [33]:
pre_list

array([4.69257474e-01, 5.72943628e-01, 6.06490672e-01, 6.14297807e-01,
       6.28350019e-01, 6.84120119e-01, 7.62282252e-01, 7.92123377e-01,
       8.26123714e-01, 8.45048070e-01, 8.87668252e-01, 9.14579093e-01,
       9.37386155e-01, 9.51830626e-01, 9.63515997e-01, 9.71717060e-01,
       9.72770333e-01, 9.75702822e-01, 9.73338604e-01, 9.70867753e-01,
       9.74823892e-01, 9.68084276e-01, 9.66525376e-01, 9.63909864e-01,
       9.65825379e-01, 9.70747411e-01, 9.70136940e-01, 9.66212094e-01,
       9.62952971e-01, 9.68958259e-01, 9.66780901e-01, 9.65932488e-01,
       9.70786154e-01, 9.71845508e-01, 9.77695763e-01, 9.75534797e-01,
       9.76213574e-01, 9.77572680e-01, 9.73327875e-01, 9.68868732e-01,
       9.56674516e-01, 9.42218065e-01, 9.36549664e-01, 9.15259898e-01,
       9.11380053e-01, 9.13415790e-01, 9.03237343e-01, 8.73785317e-01,
       8.50731552e-01, 8.22422683e-01, 8.23629260e-01, 8.16189289e-01,
       8.37441921e-01, 8.36091816e-01, 8.37758958e-01, 8.31630290e-01,
      

In [34]:
for i in pre_list:
     print("{:.5f}".format(float(i)))

0.46926
0.57294
0.60649
0.61430
0.62835
0.68412
0.76228
0.79212
0.82612
0.84505
0.88767
0.91458
0.93739
0.95183
0.96352
0.97172
0.97277
0.97570
0.97334
0.97087
0.97482
0.96808
0.96653
0.96391
0.96583
0.97075
0.97014
0.96621
0.96295
0.96896
0.96678
0.96593
0.97079
0.97185
0.97770
0.97553
0.97621
0.97757
0.97333
0.96887
0.95667
0.94222
0.93655
0.91526
0.91138
0.91342
0.90324
0.87379
0.85073
0.82242
0.82363
0.81619
0.83744
0.83609
0.83776
0.83163
0.84343
0.85838
0.88806
0.93742
0.96348
0.94721
0.96192
0.98565
0.97573
0.96802
0.93553
0.95940
0.97206
0.71230
0.31046
0.22703
0.02704
0.02905
0.01220
0.00103
0.00001
0.00001
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000
0.00000


In [35]:
print(len(pre_list))

11112


In [36]:
pre_list.mean()

0.47628865

In [37]:
pre_list[:20]

array([0.46925747, 0.5729436 , 0.6064907 , 0.6142978 , 0.62835   ,
       0.6841201 , 0.76228225, 0.7921234 , 0.8261237 , 0.84504807,
       0.88766825, 0.9145791 , 0.93738616, 0.9518306 , 0.963516  ,
       0.97171706, 0.97277033, 0.9757028 , 0.9733386 , 0.97086775],
      dtype=float32)

In [38]:
# # after 
# frames = []

# for i in range(20):
#     img = np.array(mat_file.get('melexisG11f03')[i]).reshape(24,32)
#     fig = plt.rcParams['figure.figsize'] = [24, 32]
#     #ax = plt.imshow(img, vmin=17,vmax=23,cmap='viridis', interpolation='nearest')
#     #plt.colorbar(ax)
#     plt.imshow(img, vmin=17,vmax=23,cmap='viridis',animated=True ,interpolation='nearest')
#     plt.show()
#     #frames.append([plt.imshow(img, vmin=17,vmax=23,cmap='viridis',animated=True ,interpolation='nearest')])


모델이 얼마나 넘어졌는지를 보여주고 있음
근데 정확하다는 보장이 없음

사람이 한거라 신뢰성 낮음

-> 레이블링을 다시 함

일단 지금은 레이블링 대충했음

실현가능성만 확인

" 결론 : 가능성이 있어 보인다"

confidence score 를 레이블로 썼다 왜? 시간 오래 걸려서 일일이 레이블링 하기에는

In [39]:
mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f04-data.mat')
print(mat_file)
print(mat_file.get('melexisG12f04'))
print(mat_file.get('melexisG12f04').shape)
print(mat_file.get('melexisG12f04'))

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Tue Jul  2 12:12:47 2019', '__version__': '1.0', '__globals__': [], 'melexisG12f04': array([[17.87, 18.23, 18.47, ..., 20.05, 19.15, 18.83],
       [17.99, 18.27, 18.51, ..., 20.05, 19.23, 19.07],
       [18.01, 18.17, 18.55, ..., 20.05, 19.17, 19.29],
       ...,
       [17.69, 18.09, 18.21, ..., 19.83, 18.51, 18.33],
       [17.73, 18.15, 18.19, ..., 19.77, 21.03, 18.27],
       [17.73, 18.19, 18.29, ..., 19.69, 20.45, 18.35]])}
[[17.87 18.23 18.47 ... 20.05 19.15 18.83]
 [17.99 18.27 18.51 ... 20.05 19.23 19.07]
 [18.01 18.17 18.55 ... 20.05 19.17 19.29]
 ...
 [17.69 18.09 18.21 ... 19.83 18.51 18.33]
 [17.73 18.15 18.19 ... 19.77 21.03 18.27]
 [17.73 18.19 18.29 ... 19.69 20.45 18.35]]
(1380, 768)
[[17.87 18.23 18.47 ... 20.05 19.15 18.83]
 [17.99 18.27 18.51 ... 20.05 19.23 19.07]
 [18.01 18.17 18.55 ... 20.05 19.17 19.29]
 ...
 [17.69 18.09 18.21 ... 19.83 18.51 18.33]
 [17.73 18.15 18.19 ... 19.77 21.03 18.27]


In [40]:
# print(len(mat_file.get('melexisG12f04')))
# print(len(mat_file.get('melexisG12f04')[0]))
# print(mat_file.get('melexisG12f04')[0])
# for i in range(0, len(mat_file.get('melexisG12f04'))):
#     img = np.array(mat_file.get('melexisG12f04')[i]).reshape(32,24)
#     plt.rcParams['figure.figsize'] = [32, 24]
#     plt.imshow(img, cmap='hot', interpolation='nearest')
#     plt.savefig(f'{i}.png')

In [41]:
# # after 
# frames = []

# for i in range(len(mat_file.get('melexisG12f04'))):
#     img = np.array(mat_file.get('melexisG12f04')[i]).reshape(24,32)
#     fig = plt.rcParams['figure.figsize'] = [24, 32]
#     #ax = plt.imshow(img, vmin=17,vmax=23,cmap='viridis', interpolation='nearest')
#     #plt.colorbar(ax)
#     plt.imshow(img, vmin=17,vmax=23,cmap='viridis',animated=True ,interpolation='nearest')
#     plt.savefig('')

In [42]:
# file_list = []

# import os 
# for i in range(1, 4):
#     path = 'C:/Users/Flora/IR자료/IR자료최종/테스트데이터/g1{i}f01'
#     for j in range(1, 10):
#         file_list = os.listdir(path + 'g11f0{j}')

# print(sum(file_list))

In [43]:
cnt = 0
file_num = []
import os 
i = 1
j = 1
z = 1
for i in range(1,3):
    for j in range(1,4):
        for z in range(1,16):
            if(z < 10 and z > 0):
                path =f'C:/Users/Flora/IR자료/IR자료최종/테스트데이터/g{i}{j}f0{z}'
                file_list = os.listdir(path)
                file_num.append(len(file_list))
            else:
                path =f'C:/Users/Flora/IR자료/IR자료최종/테스트데이터/g{i}{j}f{z}'
                file_list = os.listdir(path)
                file_num.append(len(file_list))

In [44]:
len(file_num)

90

In [45]:
file_num

[120,
 144,
 128,
 118,
 270,
 218,
 190,
 104,
 152,
 152,
 116,
 226,
 132,
 154,
 244,
 208,
 260,
 180,
 140,
 138,
 120,
 144,
 172,
 112,
 126,
 172,
 160,
 186,
 140,
 150,
 182,
 128,
 126,
 100,
 138,
 126,
 122,
 104,
 155,
 160,
 116,
 136,
 128,
 190,
 146,
 82,
 76,
 85,
 158,
 68,
 140,
 89,
 103,
 81,
 67,
 138,
 116,
 92,
 108,
 86,
 75,
 51,
 86,
 57,
 58,
 62,
 58,
 42,
 68,
 70,
 112,
 44,
 86,
 43,
 94,
 150,
 98,
 124,
 84,
 118,
 110,
 100,
 100,
 120,
 110,
 110,
 110,
 110,
 130,
 110]

In [46]:
sum(file_num)

11112

In [47]:
print(G11data1_test.shape)

(120, 769)


In [48]:
# i = 1
# j = 1
# z = 1
# for i in range(1,3):
#     for j in range(1,4):
#         for z in range(1,16):
#             print('G{}{}data{}.shape'.format(i, j, z))

In [49]:
print(G11data1_test.shape)
print(G11data2_test.shape)
print(G11data3_test.shape)
print(G11data4_test.shape)
print(G11data5_test.shape)
print(G11data6_test.shape)
print(G11data7_test.shape)
print(G11data8_test.shape)
print(G11data9_test.shape)
print(G11data10_test.shape)
print(G11data11_test.shape)
print(G11data12_test.shape)
print(G11data13_test.shape)
print(G11data14_test.shape)
print(G11data15_test.shape)
print('--------------------------------------------')
print(G12data1_test.shape)
print(G12data2_test.shape)
print(G12data3_test.shape)
print(G12data4_test.shape)
print(G12data5_test.shape)
print(G12data6_test.shape)
print(G12data7_test.shape)
print(G12data8_test.shape)
print(G12data9_test.shape)
print(G12data10_test.shape)
print(G12data11_test.shape)
print(G12data12_test.shape)
print(G12data13_test.shape)
print(G12data14_test.shape)
print(G12data15_test.shape)
print('--------------------------------------------')
print(G13data1_test.shape)
print(G13data2_test.shape)
print(G13data3_test.shape)
print(G13data4_test.shape)
print(G13data5_test.shape)
print(G13data6_test.shape)
print(G13data7_test.shape)
print(G13data8_test.shape)
print(G13data9_test.shape)
print(G13data10_test.shape)
print(G13data11_test.shape)
print(G13data12_test.shape)
print(G13data13_test.shape)
print(G13data14_test.shape)
print(G13data15_test.shape)
print('--------------------------------------------')
print(G21data1_test.shape)
print(G21data2_test.shape)
print(G21data3_test.shape)
print(G21data4_test.shape)
print(G21data5_test.shape)
print(G21data6_test.shape)
print(G21data7_test.shape)
print(G21data8_test.shape)
print(G21data9_test.shape)
print(G21data10_test.shape)
print(G21data11_test.shape)
print(G21data12_test.shape)
print(G21data13_test.shape)
print(G21data14_test.shape)
print(G21data15_test.shape)
print('--------------------------------------------')
print(G22data1_test.shape)
print(G22data2_test.shape)
print(G22data3_test.shape)
print(G22data4_test.shape)
print(G22data5_test.shape)
print(G22data6_test.shape)
print(G22data7_test.shape)
print(G22data8_test.shape)
print(G22data9_test.shape)
print(G22data10_test.shape)
print(G22data11_test.shape)
print(G22data12_test.shape)
print(G22data13_test.shape)
print(G22data14_test.shape)
print(G22data15_test.shape)
print('--------------------------------------------')
print(G23data1_test.shape)
print(G23data2_test.shape)
print(G23data3_test.shape)
print(G23data4_test.shape)
print(G23data5_test.shape)
print(G23data6_test.shape)
print(G23data7_test.shape)
print(G23data8_test.shape)
print(G23data9_test.shape)
print(G23data10_test.shape)
print(G23data11_test.shape)
print(G23data12_test.shape)
print(G23data13_test.shape)
print(G23data14_test.shape)
print(G23data15_test.shape)

(120, 769)
(144, 769)
(128, 769)
(118, 769)
(270, 769)
(218, 769)
(190, 769)
(104, 769)
(152, 769)
(152, 769)
(116, 769)
(226, 769)
(132, 769)
(154, 769)
(244, 769)
--------------------------------------------
(208, 769)
(260, 769)
(180, 769)
(140, 769)
(138, 769)
(120, 769)
(144, 769)
(172, 769)
(112, 769)
(126, 769)
(172, 769)
(160, 769)
(186, 769)
(140, 769)
(150, 769)
--------------------------------------------
(182, 769)
(128, 769)
(126, 769)
(100, 769)
(138, 769)
(126, 769)
(122, 769)
(104, 769)
(155, 769)
(160, 769)
(116, 769)
(136, 769)
(128, 769)
(190, 769)
(146, 769)
--------------------------------------------
(82, 769)
(76, 769)
(85, 769)
(158, 769)
(68, 769)
(140, 769)
(89, 769)
(103, 769)
(81, 769)
(67, 769)
(138, 769)
(116, 769)
(92, 769)
(108, 769)
(86, 769)
--------------------------------------------
(75, 769)
(51, 769)
(86, 769)
(57, 769)
(58, 769)
(62, 769)
(58, 769)
(42, 769)
(68, 769)
(70, 769)
(112, 769)
(44, 769)
(86, 769)
(43, 769)
(94, 769)
------------------

In [50]:
G11dataf8.shape

(826, 769)

In [52]:
# i = 1
# for name in file_names:
#     src = os.path.join(file_path, name)
#     dst = str(i) + '.jpg'
#     dst = os.path.join(file_path, dst)
#     os.rename(src, dst)
#     i += 1

In [53]:
print(len(pre_list[120:264]))

144


In [54]:
f = [0, 2, 4, 1]
f[-1]

1

In [55]:
# file_num2 = [120]
# i = 0
# while (file_num[i+1] == 11112):
#     file_num2.append(file_num[i] + file_num[i+1])
#     i +=1

In [56]:
file_num2 = [120]

In [57]:
len(file_num)

90

In [58]:
for i in range(89):
    file_num2.append(file_num2[i] + file_num[i+1])

In [59]:
len(file_num2)

90

In [60]:
file_num2

[120,
 264,
 392,
 510,
 780,
 998,
 1188,
 1292,
 1444,
 1596,
 1712,
 1938,
 2070,
 2224,
 2468,
 2676,
 2936,
 3116,
 3256,
 3394,
 3514,
 3658,
 3830,
 3942,
 4068,
 4240,
 4400,
 4586,
 4726,
 4876,
 5058,
 5186,
 5312,
 5412,
 5550,
 5676,
 5798,
 5902,
 6057,
 6217,
 6333,
 6469,
 6597,
 6787,
 6933,
 7015,
 7091,
 7176,
 7334,
 7402,
 7542,
 7631,
 7734,
 7815,
 7882,
 8020,
 8136,
 8228,
 8336,
 8422,
 8497,
 8548,
 8634,
 8691,
 8749,
 8811,
 8869,
 8911,
 8979,
 9049,
 9161,
 9205,
 9291,
 9334,
 9428,
 9578,
 9676,
 9800,
 9884,
 10002,
 10112,
 10212,
 10312,
 10432,
 10542,
 10652,
 10762,
 10872,
 11002,
 11112]

In [ ]:
file_num[i]:file_num2[i]

In [83]:
file_path = 'C:/Users/Flora/IR자료/IR자료최종/테스트데이터/g11f02'
file_names = os.listdir(file_path)
file_names

['856.png',
 '857.png',
 '858.png',
 '859.png',
 '860.png',
 '861.png',
 '862.png',
 '863.png',
 '864.png',
 '865.png',
 '866.png',
 '867.png',
 '868.png',
 '869.png',
 '870.png',
 '871.png',
 '872.png',
 '873.png',
 '874.png',
 '875.png',
 '876.png',
 '877.png',
 '878.png',
 '879.png',
 '880.png',
 '881.png',
 '882.png',
 '883.png',
 '884.png',
 '885.png',
 '886.png',
 '887.png',
 '888.png',
 '889.png',
 '890.png',
 '891.png',
 '892.png',
 '893.png',
 '894.png',
 '895.png',
 '896.png',
 '897.png',
 '898.png',
 '899.png',
 '900.png',
 '901.png',
 '902.png',
 '903.png',
 '904.png',
 '905.png',
 '906.png',
 '907.png',
 '908.png',
 '909.png',
 '910.png',
 '911.png',
 '912.png',
 '913.png',
 '914.png',
 '915.png',
 '916.png',
 '917.png',
 '918.png',
 '919.png',
 '920.png',
 '921.png',
 '922.png',
 '923.png',
 '924.png',
 '925.png',
 '926.png',
 '927.png',
 '928.png',
 '929.png',
 '930.png',
 '931.png',
 '932.png',
 '933.png',
 '934.png',
 '935.png',
 '936.png',
 '937.png',
 '938.png',
 '93

In [84]:
i = 0
llist = pre_list[120:]
for name in file_names:
    src = os.path.join(file_path, name)
    dst = name + '-' + str("%.3f"%llist[i]) + '.png'
    dst = os.path.join(file_path, dst)
    os.rename(src, dst)
    i += 1

3.667311e-09

In [85]:
import imageio

In [88]:
file_path = 'C:/Users/Flora/IR자료/IR자료최종/테스트데이터/g11f02'
file_names = os.listdir(file_path)
file_names

['856.png-0.000.png',
 '857.png-0.000.png',
 '858.png-0.000.png',
 '859.png-0.000.png',
 '860.png-0.000.png',
 '861.png-0.000.png',
 '862.png-0.000.png',
 '863.png-0.000.png',
 '864.png-0.000.png',
 '865.png-0.000.png',
 '866.png-0.000.png',
 '867.png-0.000.png',
 '868.png-0.000.png',
 '869.png-0.000.png',
 '870.png-0.000.png',
 '871.png-0.000.png',
 '872.png-0.001.png',
 '873.png-0.032.png',
 '874.png-0.162.png',
 '875.png-0.307.png',
 '876.png-0.756.png',
 '877.png-0.820.png',
 '878.png-0.870.png',
 '879.png-0.894.png',
 '880.png-0.933.png',
 '881.png-0.962.png',
 '882.png-0.979.png',
 '883.png-0.985.png',
 '884.png-0.984.png',
 '885.png-0.984.png',
 '886.png-0.982.png',
 '887.png-0.980.png',
 '888.png-0.983.png',
 '889.png-0.984.png',
 '890.png-0.986.png',
 '891.png-0.989.png',
 '892.png-0.991.png',
 '893.png-0.992.png',
 '894.png-0.993.png',
 '895.png-0.994.png',
 '896.png-0.995.png',
 '897.png-0.995.png',
 '898.png-0.996.png',
 '899.png-0.996.png',
 '900.png-0.996.png',
 '901.png-

In [94]:
pwd

'C:\\Users\\Flora\\IR자료\\IR자료최종'

In [95]:
os.chdir('C:/Users/Flora/IR자료/IR자료최종/테스트데이터/g11f02')

In [96]:
pwd

'C:\\Users\\Flora\\IR자료\\IR자료최종\\테스트데이터\\g11f02'

In [97]:
filenames_gif = file_names[9:60]
img_gif = []
for filename_g in filenames_gif:
    img_gif.append(imageio.imread(filename_g))

In [99]:
imageio.mimsave('기울기.gif', img_gif, 'GIF', duration = 0.032)