In [1]:
from tensorflow.keras.models import load_model

In [2]:
from scipy import io
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from sklearn.metrics import roc_curve, auc

In [3]:
cnt = 0

i = 1
j = 1
z = 1
for i in range(1,3):
    print('---------------------------------')
    for j in range(1,4):
        print('---------------------------------')
        for z in range(1,16):
            if(z < 10 and z > 0):
                mat_file = io.loadmat(f'./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f0{z}-data.mat')
                print(mat_file.get(f'melexisG{i}{j}f0{z}').shape)
                cnt += mat_file.get(f'melexisG{i}{j}f0{z}').shape[0]
            else:
                mat_file = io.loadmat(f'./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f{z}-data.mat')
                print(mat_file.get(f'melexisG{i}{j}f{z}').shape)
                cnt += mat_file.get(f'melexisG{i}{j}f{z}').shape[0]
           
                
            
#mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f01-data.mat')

---------------------------------
---------------------------------
(880, 768)
(1000, 768)
(1420, 768)
(930, 768)
(1340, 768)
(1410, 768)
(1270, 768)
(930, 768)
(950, 768)
(940, 768)
(1100, 768)
(1110, 768)
(1160, 768)
(1020, 768)
(1230, 768)
---------------------------------
(2900, 768)
(1730, 768)
(1970, 768)
(1380, 768)
(1250, 768)
(1100, 768)
(980, 768)
(1250, 768)
(990, 768)
(1290, 768)
(980, 768)
(1260, 768)
(1050, 768)
(1210, 768)
(1150, 768)
---------------------------------
(1010, 768)
(960, 768)
(1100, 768)
(910, 768)
(1015, 768)
(1069, 768)
(1290, 768)
(940, 768)
(1239, 768)
(1240, 768)
(1005, 768)
(1130, 768)
(1240, 768)
(1215, 768)
(1614, 768)
---------------------------------
---------------------------------
(760, 768)
(850, 768)
(680, 768)
(840, 768)
(1230, 768)
(1200, 768)
(1000, 768)
(830, 768)
(810, 768)
(870, 768)
(1090, 768)
(810, 768)
(740, 768)
(1001, 768)
(970, 768)
---------------------------------
(710, 768)
(760, 768)
(620, 768)
(510, 768)
(1110, 768)
(920, 7

In [4]:
model = load_model('./savecnnminmax2.h5')

In [5]:
from scipy import io
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from sklearn.metrics import roc_curve, auc
import tensorflow as tf

In [6]:
def data_merge(data,x1, x2, x3, x4, x5, x6,x7, x8, x9, x10):
    data.loc[0:x1-1,'label'] = 0
    data.loc[x1:x2,'label'] = 1
    data.loc[x2+1:x3-1,'label'] = 0 
    data.loc[x3:x4,'label'] = 1 
    data.loc[x4+1:x5-1,'label'] = 0 
    data.loc[x5:x6,'label'] = 1
    data.loc[x6+1:x7-1,'label'] = 0 
    data.loc[x7:x8,'label'] = 1
    data.loc[x8+1:x9-1,'label'] = 0 
    data.loc[x9:x10,'label'] = 1
    data.loc[x10 +1:,'label'] = 0
    return data

def data_merge2(data,x1, x2, x3, x4, x5, x6,x7, x8, x9, x10,x11,x12):
    data.loc[0:x1-1,'label'] = 0
    data.loc[x1:x2,'label'] = 1
    data.loc[x2+1:x3-1,'label'] = 0 
    data.loc[x3:x4,'label'] = 1 
    data.loc[x4+1:x5-1,'label'] = 0 
    data.loc[x5:x6,'label'] = 1
    data.loc[x6+1:x7-1,'label'] = 0 
    data.loc[x7:x8,'label'] = 1
    data.loc[x8+1:x9-1,'label'] = 0 
    data.loc[x9:x10,'label'] = 1
    data.loc[x10 +1:x11-1,'label'] = 0
    data.loc[x11:x12,'label'] = 1
    data.loc[x12 +1:,'label'] = 0
    return data

In [7]:
import pandas as pd
import csv

mat_file_G11_io = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f01-data.mat')
print(mat_file_G11_io.get('melexisG11f01'))
print(mat_file_G11_io.get('melexisG11f01')[0][0])
G11data1 = pd.DataFrame(mat_file_G11_io.get('melexisG11f01'))
G11data1 = data_merge(G11data1,154, 195, 300, 336, 466, 493, 580, 666, 764, 823)

mat_file_G11_io2 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f02-data.mat')
G11data2 = pd.DataFrame(mat_file_G11_io2.get('melexisG11f02'))
G11data2 = data_merge(G11data2,47, 127, 260, 334, 439, 500, 662, 725, 880, 951)

mat_file_G11_io3 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f03-data.mat')
G11data3 = pd.DataFrame(mat_file_G11_io3.get('melexisG11f03'))
G11data3 = data_merge(G11data3,209, 289, 411, 466, 873, 930, 1130, 1184, 1292, 1340)

mat_file_G11_io4 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f04-data.mat')
G11data4 = pd.DataFrame(mat_file_G11_io4.get('melexisG11f04'))
G11data4 = data_merge(G11data4,212, 255, 371, 411, 496, 548, 673, 718, 812, 873)

mat_file_G11_io5 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f05-data.mat')
G11data5 = pd.DataFrame(mat_file_G11_io5.get('melexisG11f05'))
G11data5 = data_merge(G11data5,176, 212, 366, 415, 510, 556, 815, 873, 1070, 1143)

mat_file_G11_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f06-data.mat')
G11data6 = pd.DataFrame(mat_file_G11_io6.get('melexisG11f06'))
G11data6 = data_merge2(G11data6,20, 66, 440, 503, 670, 721, 928, 988, 1104, 1151,1301,1409)

mat_file_G11_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f07-data.mat')
G11data7 = pd.DataFrame(mat_file_G11_io7.get('melexisG11f07'))
G11data7 = data_merge(G11data7,148, 199, 414, 459, 608, 668, 976, 1010, 1175, 1269)

mat_file_G11_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f08-data.mat')
G11data8 = pd.DataFrame(mat_file_G11_io8.get('melexisG11f08'))
G11data8 = data_merge(G11data8,212, 270, 372, 414, 505, 557, 645, 719, 830, 881)

mat_file_G11_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f09-data.mat')
G11data9 = pd.DataFrame(mat_file_G11_io9.get('melexisG11f09'))
G11data9 = data_merge(G11data9,186, 231, 378, 417, 512, 565, 701, 749, 863, 938)

mat_file_G11_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f10-data.mat')
G11data10 = pd.DataFrame(mat_file_G11_io10.get('melexisG11f10'))
G11data10 = data_merge(G11data10,147, 196, 320, 350, 484, 525, 655, 700, 825, 900)

mat_file_G11_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f11-data.mat')
G11data11 = pd.DataFrame(mat_file_G11_io11.get('melexisG11f11'))
G11data11 = data_merge(G11data11,321, 360, 484, 519, 613, 639, 763, 810, 979, 1036)

mat_file_G11_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f12-data.mat')
G11data12 = pd.DataFrame(mat_file_G11_io12.get('melexisG11f12'))
G11data12 = data_merge(G11data12,228, 275, 434, 475, 625, 670, 833, 873, 940, 1048)

mat_file_G11_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f13-data.mat')
G11data13 = pd.DataFrame(mat_file_G11_io13.get('melexisG11f13'))
G11data13 = data_merge(G11data13,197, 232, 404, 453, 636, 684, 841, 904, 1075, 1140)

mat_file_G11_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f14-data.mat')
G11data14 = pd.DataFrame(mat_file_G11_io14.get('melexisG11f14'))
G11data14 = data_merge(G11data14,265, 307, 408, 465, 585, 630, 739, 794, 943, 1019)

mat_file_G11_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f15-data.mat')
G11data15 = pd.DataFrame(mat_file_G11_io15.get('melexisG11f15'))
G11data15 = data_merge(G11data15,198, 250, 457, 494, 654, 694, 859, 921, 1108, 1229)

#result = pd.concat([data, data2,data3, data4, data5, data6, data7, data8, data9])

#print(y)
# print(df)
# f = open('./melexisG11f01.csv', 'w', encoding='utf-8', newline='')
# wr = csv.writer(f)
# wr.writerow(df, 0)
# f.close()

[[17.81 17.69 18.23 ... 20.01 18.87 19.17]
 [17.77 17.77 18.17 ... 20.03 21.55 19.19]
 [17.91 17.85 18.13 ... 20.07 20.83 19.07]
 ...
 [17.75 18.07 18.31 ... 19.67 18.79 17.57]
 [17.79 18.09 18.37 ... 19.73 18.79 17.91]
 [17.81 18.17 18.35 ... 19.71 18.77 18.17]]
17.81


In [8]:
mat_file_G12_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f01-data.mat')
print(mat_file_G12_io.get('melexisG12f01'))
print(mat_file_G12_io.get('melexisG12f01')[0][0])
G12data1 = pd.DataFrame(mat_file_G12_io.get('melexisG12f01'))
G12data1 = data_merge(G12data1,673, 738, 1418, 1489, 1725, 1814, 2341, 2454, 2796, 2899)
mat_file_G12_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f02-data.mat')
G12data2 = pd.DataFrame(mat_file_G12_io2.get('melexisG12f02'))
G12data2 = data_merge(G12data2,240, 290, 533, 610, 920, 974, 1240, 1320, 1600, 1729)

mat_file_G12_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f03-data.mat')
G12data3 = pd.DataFrame(mat_file_G12_io3.get('melexisG12f03'))
G12data3 = data_merge(G12data3,217, 279, 510, 660, 1097, 1191, 1559, 1622, 1880, 1969)

mat_file_G12_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f04-data.mat')
G12data4 = pd.DataFrame(mat_file_G12_io4.get('melexisG12f04'))
G12data4 = data_merge(G12data4,449, 499, 700, 734, 893, 955, 1091, 1150, 1310, 1379)

mat_file_G12_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f05-data.mat')
G12data5 = pd.DataFrame(mat_file_G12_io5.get('melexisG12f05'))
G12data5 = data_merge(G12data5,310, 363, 539, 579, 712, 765, 902, 952, 1136, 1204)

mat_file_G12_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f06-data.mat')
G12data6 = pd.DataFrame(mat_file_G12_io6.get('melexisG12f06'))
G12data6 = data_merge(G12data6, 156, 259, 415, 469, 658, 717, 823, 950, 1040, 1099)

mat_file_G12_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f07-data.mat')
G12data7 = pd.DataFrame(mat_file_G12_io7.get('melexisG12f07'))
G12data7 = data_merge(G12data7,143, 193, 346, 388, 530, 600, 704, 759, 896, 967)

mat_file_G12_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f08-data.mat')
G12data8 = pd.DataFrame(mat_file_G12_io8.get('melexisG12f08'))
G12data8 = data_merge(G12data8,245,307,470,556,717,771,940,998,1164,1249)

mat_file_G12_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f09-data.mat')
G12data9 = pd.DataFrame(mat_file_G12_io9.get('melexisG12f09'))
G12data9 = data_merge(G12data9,155,228,340,400,511,591,704,767,934,989)

mat_file_G12_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f10-data.mat')
G12data10 = pd.DataFrame(mat_file_G12_io10.get('melexisG12f10'))
G12data10 = data_merge(G12data10,160,251,381,440,603,665,934,1005,1215,1277)

mat_file_G12_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f11-data.mat')
G12data11 = pd.DataFrame(mat_file_G12_io11.get('melexisG12f11'))
G12data11 = data_merge(G12data11,221,278,400,456,568,634,726,775,894,979)

mat_file_G12_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f12-data.mat')
G12data12 = pd.DataFrame(mat_file_G12_io12.get('melexisG12f12'))
G12data12 = data_merge(G12data12,485,570,675,720,820,870,1000,1070,1180,1259)

mat_file_G12_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f13-data.mat')
G12data13 = pd.DataFrame(mat_file_G12_io13.get('melexisG12f13'))
G12data13 = data_merge(G12data13,198,269,427,507,628,680,780,835,957,1049)

mat_file_G12_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f14-data.mat')
G12data14 = pd.DataFrame(mat_file_G12_io14.get('melexisG12f14'))
G12data14 = data_merge(G12data14,182,274,555,620,770,828,961,1030,1140,1209)

mat_file_G12_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f15-data.mat')
G12data15 = pd.DataFrame(mat_file_G12_io15.get('melexisG12f15'))
G12data15 = data_merge(G12data15,137,188,394,440,598,650,815,865,1075,1149)

[[18.73 18.79 19.11 ... 20.01 19.67 19.45]
 [18.67 18.79 19.07 ... 19.99 19.71 19.47]
 [18.63 18.73 19.05 ... 19.91 19.53 19.49]
 ...
 [18.11 18.07 18.65 ... 20.13 19.23 19.33]
 [18.05 18.07 18.59 ... 20.25 19.31 19.39]
 [18.03 18.05 18.55 ... 20.29 19.51 19.47]]
18.73


In [9]:
mat_file_G13_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f01-data.mat')
print(mat_file_G13_io.get('melexisG13f01'))
print(mat_file_G13_io.get('melexisG13f01')[0][0])
G13data1 = pd.DataFrame(mat_file_G13_io.get('melexisG13f01'))
G13data1 = data_merge(G13data1,122, 180, 288, 380, 478, 580, 680, 794, 892, 982)

mat_file_G13_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f02-data.mat')
G13data2 = pd.DataFrame(mat_file_G13_io2.get('melexisG13f02'))
G13data2 = data_merge(G13data2,100, 155, 298, 372, 510, 570, 712, 774, 880, 943)

mat_file_G13_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f03-data.mat')
G13data3 = pd.DataFrame(mat_file_G13_io3.get('melexisG13f03'))
G13data3 = data_merge(G13data3,78, 150, 304, 364, 583, 670, 834, 880, 1028, 1090)

mat_file_G13_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f04-data.mat')
G13data4 = pd.DataFrame(mat_file_G13_io4.get('melexisG13f04'))
G13data4 = data_merge(G13data4,79, 140, 279, 320, 443, 497, 615, 662, 824, 873)

mat_file_G13_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f05-data.mat')
G13data5 = pd.DataFrame(mat_file_G13_io5.get('melexisG13f05'))
G13data5 = data_merge(G13data5,109, 159, 317, 377, 511, 565, 743, 805, 920, 988)

mat_file_G13_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f06-data.mat')
G13data6 = pd.DataFrame(mat_file_G13_io6.get('melexisG13f06'))
G13data6 = data_merge(G13data6, 114, 194, 354, 410, 570, 620, 762, 799, 978, 1040)

mat_file_G13_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f07-data.mat')
G13data7 = pd.DataFrame(mat_file_G13_io7.get('melexisG13f07'))
G13data7 = data_merge(G13data7,80, 200, 296, 338, 525, 573, 748, 803, 1200, 1260)

mat_file_G13_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f08-data.mat')
G13data8 = pd.DataFrame(mat_file_G13_io8.get('melexisG13f08'))
G13data8 = data_merge(G13data8,88, 134, 247, 289, 451, 510, 668, 730, 833, 884)

mat_file_G13_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f09-data.mat')
G13data9 = pd.DataFrame(mat_file_G13_io9.get('melexisG13f09'))
G13data9 = data_merge(G13data9,119, 189, 342, 408, 555, 629, 869, 922, 1084, 1144)

mat_file_G13_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f10-data.mat')
G13data10 = pd.DataFrame(mat_file_G13_io10.get('melexisG13f10'))
G13data10 = data_merge(G13data10,118, 190, 350, 420, 560, 660, 873, 973, 1087, 1166)

mat_file_G13_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f11-data.mat')
G13data11 = pd.DataFrame(mat_file_G13_io11.get('melexisG13f11'))
G13data11 = data_merge(G13data11,63, 120, 290, 333, 530, 590, 718, 770, 911, 968)

mat_file_G13_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f12-data.mat')
G13data12 = pd.DataFrame(mat_file_G13_io12.get('melexisG13f12'))
G13data12 = data_merge(G13data12,144, 230, 450, 520, 655, 730, 863, 928, 1047, 1114)

mat_file_G13_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f13-data.mat')
G13data13 = pd.DataFrame(mat_file_G13_io13.get('melexisG13f13'))
G13data13 = data_merge(G13data13,169, 246, 410, 535, 692, 750, 905, 970, 1157, 1220)

mat_file_G13_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f14-data.mat')
G13data14 = pd.DataFrame(mat_file_G13_io14.get('melexisG13f14'))
G13data14 = data_merge(G13data14,121, 197, 372, 434, 588, 651, 794, 861, 1037, 1131)

mat_file_G13_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f15-data.mat')
G13data15 = pd.DataFrame(mat_file_G13_io15.get('melexisG13f15'))
G13data15 = data_merge(G13data15,194, 272, 644, 679, 960, 1023, 1234, 1303, 1518, 1590)

[[18.97 18.83 18.85 ... 20.45 20.09 19.43]
 [18.97 18.85 18.85 ... 20.37 20.01 19.49]
 [18.97 18.87 19.05 ... 20.51 20.01 19.49]
 ...
 [18.87 18.91 19.01 ... 20.21 19.37 20.29]
 [18.83 18.99 18.99 ... 20.35 19.41 20.33]
 [18.79 18.95 18.95 ... 20.31 19.43 20.35]]
18.97


In [10]:
mat_file_G21_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f01-data.mat')
print(mat_file_G21_io.get('melexisG21f01'))
print(mat_file_G21_io.get('melexisG21f01')[0][0])
G21data1 = pd.DataFrame(mat_file_G21_io.get('melexisG21f01'))
G21data1 = data_merge(G21data1,57, 120, 218, 290, 408, 465, 566, 609, 719, 759)

mat_file_G21_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f02-data.mat')
G21data2 = pd.DataFrame(mat_file_G21_io2.get('melexisG21f02'))
G21data2 = data_merge(G21data2,147,192, 321,360, 471,510, 639,680, 809,849)

mat_file_G21_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f03-data.mat')
G21data3 = pd.DataFrame(mat_file_G21_io3.get('melexisG21f03'))
G21data3 = data_merge(G21data3,45, 90, 190, 239, 330, 375, 480, 523, 631, 679)

mat_file_G21_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f04-data.mat')
G21data4 = pd.DataFrame(mat_file_G21_io4.get('melexisG21f04'))
G21data4 = data_merge(G21data4,125, 160, 283, 331, 439, 486, 604, 666, 760, 839)

mat_file_G21_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f05-data.mat')
G21data5 = pd.DataFrame(mat_file_G21_io5.get('melexisG21f05'))
G21data5 = data_merge(G21data5,150, 213, 420, 462, 698, 752, 991, 1027, 1189, 1222)

mat_file_G21_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f06-data.mat')
G21data6 = pd.DataFrame(mat_file_G21_io6.get('melexisG21f06'))
G21data6 = data_merge(G21data6, 148, 193, 390, 437, 637, 680, 887, 925, 1117, 1188)

mat_file_G21_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f07-data.mat')
G21data7 = pd.DataFrame(mat_file_G21_io7.get('melexisG21f07'))
G21data7 = data_merge(G21data7,89, 135, 300, 347, 483, 525, 716, 751, 933, 985)

mat_file_G21_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f08-data.mat')
G21data8 = pd.DataFrame(mat_file_G21_io8.get('melexisG21f08'))
G21data8 = data_merge(G21data8,131, 181, 281, 305, 451, 481, 611, 665, 776, 829)

mat_file_G21_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f09-data.mat')
G21data9 = pd.DataFrame(mat_file_G21_io9.get('melexisG21f09'))
G21data9 = data_merge(G21data9,160, 197, 323, 376, 475, 503, 617, 658, 751, 791)

mat_file_G21_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f10-data.mat')
G21data10 = pd.DataFrame(mat_file_G21_io10.get('melexisG21f10'))
G21data10 = data_merge(G21data10,41, 100, 240, 287, 447, 480, 630, 672, 800, 840)

mat_file_G21_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f11-data.mat')
G21data11 = pd.DataFrame(mat_file_G21_io11.get('melexisG21f11'))
G21data11 = data_merge(G21data11,136, 182, 321, 341, 562, 603, 741, 780, 1004, 1072)

mat_file_G21_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f12-data.mat')
G21data12 = pd.DataFrame(mat_file_G21_io12.get('melexisG21f12'))
G21data12 = data_merge(G21data12,79, 112, 250, 302, 435, 483, 581, 640, 752, 809)

mat_file_G21_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f13-data.mat')
G21data13 = pd.DataFrame(mat_file_G21_io13.get('melexisG21f13'))
G21data13 = data_merge(G21data13,40, 92, 194, 269, 348, 415, 522, 579, 682, 727)

mat_file_G21_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f14-data.mat')
G21data14 = pd.DataFrame(mat_file_G21_io14.get('melexisG21f14'))
G21data14 = data_merge(G21data14,148, 191, 319, 374, 495, 546, 691, 752, 892, 945)

mat_file_G21_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f15-data.mat')
G21data15 = pd.DataFrame(mat_file_G21_io15.get('melexisG21f15'))
G21data15 = data_merge(G21data15,120, 141, 348, 389, 548, 584, 736, 767, 915, 957)

[[17.97 18.07 17.79 ... 19.89 18.61 18.41]
 [18.01 18.07 17.87 ... 19.77 18.57 18.39]
 [18.03 18.09 17.97 ... 19.65 18.55 18.35]
 ...
 [17.79 18.01 17.79 ... 19.31 18.47 18.11]
 [17.87 17.93 17.85 ... 19.33 18.39 18.05]
 [17.79 17.87 17.77 ... 19.27 18.15 18.19]]
17.97


In [11]:
mat_file_G22_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f01-data.mat')
print(mat_file_G22_io.get('melexisG22f01'))
print(mat_file_G22_io.get('melexisG22f01')[0][0])
G22data1 = pd.DataFrame(mat_file_G22_io.get('melexisG22f01'))
G22data1 = data_merge(G22data1,90, 112, 228, 254, 382, 401, 525, 550, 660, 699)

mat_file_G22_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f02-data.mat')
G22data2 = pd.DataFrame(mat_file_G22_io2.get('melexisG22f02'))
G22data2 = data_merge(G22data2,102, 138, 230, 257, 365, 391, 496, 526, 699, 727)

mat_file_G22_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f03-data.mat')
G22data3 = pd.DataFrame(mat_file_G22_io3.get('melexisG22f03'))
G22data3 = data_merge(G22data3,65, 89, 177, 207, 325, 365, 426, 448, 572, 614)

mat_file_G22_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f04-data.mat')
G22data4 = pd.DataFrame(mat_file_G22_io4.get('melexisG22f04'))
G22data4 = data_merge(G22data4,66, 89, 171, 199, 259, 285, 367, 389, 476, 509)

mat_file_G22_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f05-data.mat')
G22data5 = pd.DataFrame(mat_file_G22_io5.get('melexisG22f05'))
G22data5 = data_merge(G22data5,0, 33, 142, 250, 550, 586, 705, 743, 1007, 1080)

mat_file_G22_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f06-data.mat')
G22data6 = pd.DataFrame(mat_file_G22_io6.get('melexisG22f06'))
G22data6 = data_merge(G22data6, 47, 88, 260, 282, 465, 498, 620, 671, 847, 888)

mat_file_G22_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f07-data.mat')
G22data7 = pd.DataFrame(mat_file_G22_io7.get('melexisG22f07'))
G22data7 = data_merge(G22data7,235, 274, 398, 430, 578, 608, 806, 840, 992, 1043)

mat_file_G22_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f08-data.mat')
G22data8 = pd.DataFrame(mat_file_G22_io8.get('melexisG22f08'))
G22data8 = data_merge(G22data8,172, 210, 347, 380, 462, 485, 577, 600, 678, 708)

mat_file_G22_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f09-data.mat')
G22data9 = pd.DataFrame(mat_file_G22_io9.get('melexisG22f09'))
G22data9 = data_merge(G22data9,100, 130, 218, 243, 332, 373, 428, 458, 527, 559)

mat_file_G22_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f10-data.mat')
G22data10 = pd.DataFrame(mat_file_G22_io10.get('melexisG22f10'))
G22data10 = data_merge(G22data10,54, 84, 208, 240, 350, 370, 490, 513, 610, 637)

mat_file_G22_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f11-data.mat')
G22data11 = pd.DataFrame(mat_file_G22_io11.get('melexisG22f11'))
G22data11 = data_merge(G22data11,20, 57, 179, 214, 385, 430, 631, 679, 870, 925)

mat_file_G22_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f12-data.mat')
G22data12 = pd.DataFrame(mat_file_G22_io12.get('melexisG22f12'))
G22data12 = data_merge(G22data12,87, 110, 213, 231, 317, 351, 454, 475, 565, 587)

mat_file_G22_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f13-data.mat')
G22data13 = pd.DataFrame(mat_file_G22_io13.get('melexisG22f13'))
G22data13 = data_merge(G22data13,145, 171, 269, 300, 405, 440, 529, 563, 647, 689)

mat_file_G22_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f14-data.mat')
G22data14 = pd.DataFrame(mat_file_G22_io14.get('melexisG22f14'))
G22data14 = data_merge(G22data14,67, 88, 192, 220, 330, 354, 454, 481, 577, 600)

mat_file_G22_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f15-data.mat')
G22data15 = pd.DataFrame(mat_file_G22_io15.get('melexisG22f15'))
G22data15 = data_merge(G22data15,77, 110, 224, 254, 388, 416, 540, 571, 683, 729)

[[17.85 17.83 17.93 ... 18.95 18.01 17.81]
 [17.83 17.83 17.95 ... 18.99 18.11 17.75]
 [17.79 17.73 17.95 ... 19.01 18.07 17.67]
 ...
 [17.51 17.67 17.51 ... 19.17 18.09 18.33]
 [17.37 17.69 17.49 ... 19.11 18.07 18.31]
 [17.39 17.71 17.47 ... 19.07 18.07 18.53]]
17.85


In [12]:
mat_file_G23_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f01-data.mat')
print(mat_file_G23_io.get('melexisG23f01'))
print(mat_file_G23_io.get('melexisG23f01')[0][0])
G23data1 = pd.DataFrame(mat_file_G23_io.get('melexisG23f01'))
G23data1 = data_merge(G23data1,98, 194, 337, 430, 538, 600, 736, 793, 925, 999)

mat_file_G23_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f02-data.mat')
G23data2 = pd.DataFrame(mat_file_G23_io2.get('melexisG23f02'))
G23data2 = data_merge(G23data2,76, 132, 261, 312, 447, 497, 630, 682, 790, 838)

mat_file_G23_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f03-data.mat')
G23data3 = pd.DataFrame(mat_file_G23_io3.get('melexisG23f03'))
G23data3 = data_merge(G23data3,67, 136, 230, 310, 431, 500, 609, 672, 789, 850)

mat_file_G23_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f04-data.mat')
G23data4 = pd.DataFrame(mat_file_G23_io4.get('melexisG23f04'))
G23data4 = data_merge(G23data4,86, 150, 265, 320, 414, 463, 585, 642, 718, 759)

mat_file_G23_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f05-data.mat')
G23data5 = pd.DataFrame(mat_file_G23_io5.get('melexisG23f05'))
G23data5 = data_merge(G23data5,144, 176, 341, 374, 626, 675, 902, 941, 1185, 1243)

mat_file_G23_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f06-data.mat')
G23data6 = pd.DataFrame(mat_file_G23_io6.get('melexisG23f06'))
G23data6 = data_merge(G23data6, 56, 158, 463, 501, 746, 820, 1004, 1070, 1215, 1269)

mat_file_G23_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f07-data.mat')
G23data7 = pd.DataFrame(mat_file_G23_io7.get('melexisG23f07'))
G23data7 = data_merge(G23data7,94, 145, 325, 377, 552, 594, 723, 790, 950, 999)

mat_file_G23_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f08-data.mat')
G23data8 = pd.DataFrame(mat_file_G23_io8.get('melexisG23f08'))
G23data8 = data_merge(G23data8,32, 92, 228, 267, 380, 436, 542, 595, 711, 759)

mat_file_G23_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f09-data.mat')
G23data9 = pd.DataFrame(mat_file_G23_io9.get('melexisG23f09'))
G23data9 = data_merge(G23data9,148,204, 330, 396, 571, 626, 749, 799, 917, 969)

mat_file_G23_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f10-data.mat')
G23data10 = pd.DataFrame(mat_file_G23_io10.get('melexisG23f10'))
G23data10 = data_merge(G23data10,49, 140, 289, 365, 458, 530, 634, 695, 834, 889)

mat_file_G23_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f11-data.mat')
G23data11 = pd.DataFrame(mat_file_G23_io11.get('melexisG23f11'))
G23data11 = data_merge(G23data11,64, 140, 254, 311, 476, 554, 664, 733, 912, 969)

mat_file_G23_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f12-data.mat')
G23data12 = pd.DataFrame(mat_file_G23_io12.get('melexisG23f12'))
G23data12 = data_merge(G23data12,56, 101, 204, 262, 366, 430, 517, 580, 666, 719)

mat_file_G23_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f13-data.mat')
G23data13 = pd.DataFrame(mat_file_G23_io13.get('melexisG23f13'))
G23data13 = data_merge(G23data13,75, 160, 315, 393, 510, 580, 678, 744, 857, 909)

mat_file_G23_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f14-data.mat')
G23data14 = pd.DataFrame(mat_file_G23_io14.get('melexisG23f14'))
G23data14 = data_merge(G23data14,79, 126, 250, 304, 443, 492, 608, 677, 804, 869)

mat_file_G23_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f15-data.mat')
G23data15 = pd.DataFrame(mat_file_G23_io15.get('melexisG23f15'))
G23data15 = data_merge(G23data15,114, 170, 274, 325, 459, 578, 719, 797, 935, 989)

[[17.67 17.75 17.59 ... 18.83 18.13 18.57]
 [17.75 17.83 17.55 ... 18.79 18.01 18.43]
 [17.83 17.93 17.53 ... 18.77 17.93 18.33]
 ...
 [17.53 17.37 17.91 ... 19.03 17.65 15.91]
 [17.49 17.41 17.91 ... 19.13 17.67 15.91]
 [17.45 17.43 17.89 ... 19.13 17.77 15.89]]
17.67


In [13]:
result2 = pd.concat([G11data1, G11data2,G11data3, G11data4, G11data5, G11data6, G11data7, G11data8, G11data9, G11data10,
                    G11data11, G11data12, G11data13, G11data14, G11data15,G12data1, G12data2,G12data3, G12data4, G12data5, 
                    G12data6, G12data7, G12data8, G12data9, G12data10, G12data11, G12data12, G12data13, G12data14, G12data15,
                    G13data1, G13data2,G13data3, G13data4, G13data5, G13data6, G13data7, G13data8, G13data9, G13data10,
                    G13data11, G13data12,G13data13, G13data14, G13data15,G21data1, G21data2,G21data3, G21data4, G21data5, 
                    G21data6, G21data7, G21data8, G21data9, G21data10, G21data11, G21data12, G21data13, G21data14, G21data15,
                    G22data1, G22data2,G22data3, G22data4, G22data5, G22data6, G22data7, G22data8, G22data9, G22data10,
                    G22data11, G22data12, G22data13, G22data14, G22data15,G23data1, G23data2,G23data3, G23data4, G23data5, 
                    G23data6, G23data7, G23data8, G23data9, G23data10, G23data11, G23data12, G23data13, G23data14, G23data15])
print(result2.shape)
result2 = result2.drop(['label'], axis=1)


(93168, 769)


In [14]:
# result2 = list(result2)

In [15]:
result2= result2.where(pd.notnull(result2), result2.mean(), axis='columns')
print(result2.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
763    0
764    0
765    0
766    0
767    0
Length: 768, dtype: int64


In [16]:
np.set_printoptions(threshold=100000)

In [17]:
result2.reset_index(drop=True, inplace= True)

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
result2[:] = scaler.fit_transform(result2[:])
result2[:] = scaler.transform(result2[:])

In [19]:
result2 = result2.to_numpy()

In [20]:
result2= result2.reshape(93168, 24, 32, 1)

In [21]:
pre_list2 = model.predict_proba(result2)

C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\sequential.py:430: UserWarning: `model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.
  warnings.warn('`model.predict_proba()` is deprecated and '


In [22]:
print(len(pre_list2))

93168


In [23]:
pre_list2.mean()

0.997464

In [25]:
pre_list2[:40]

array([[0.99869233],
       [0.99879265],
       [0.9987571 ],
       [0.99869424],
       [0.9987099 ],
       [0.99866736],
       [0.9988116 ],
       [0.9988391 ],
       [0.99876934],
       [0.99870694],
       [0.9987337 ],
       [0.9988236 ],
       [0.9988104 ],
       [0.9986644 ],
       [0.998749  ],
       [0.9988985 ],
       [0.99888486],
       [0.99879175],
       [0.99884903],
       [0.99889636],
       [0.99889475],
       [0.9988187 ],
       [0.9988763 ],
       [0.99880683],
       [0.9988772 ],
       [0.99892384],
       [0.99888986],
       [0.9988116 ],
       [0.99876463],
       [0.99869186],
       [0.99867475],
       [0.9985129 ],
       [0.9987218 ],
       [0.9986375 ],
       [0.99862325],
       [0.9987488 ],
       [0.99876297],
       [0.998781  ],
       [0.99886084],
       [0.9988971 ]], dtype=float32)