In [1]:
from scipy import io
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from sklearn.metrics import roc_curve, auc
import tensorflow as tf

# 전체 mat파일 shape 읽기 

In [2]:
i = 1
j = 1
z = 1
for i in range(1,3):
    print('---------------------------------')
    for j in range(1,4):
        print('---------------------------------')
        for z in range(1,16):
            if(z < 10 and z > 0):
                mat_file = io.loadmat(f'C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f0{z}-data.mat')
                print(mat_file.get(f'melexisG{i}{j}f0{z}').shape)
            else:
                mat_file = io.loadmat(f'C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f{z}-data.mat')
                print(mat_file.get(f'melexisG{i}{j}f{z}').shape)
           
                
            
#mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f01-data.mat')

---------------------------------
---------------------------------
(880, 768)
(1000, 768)
(1420, 768)
(930, 768)
(1340, 768)
(1410, 768)
(1270, 768)
(930, 768)
(950, 768)
(940, 768)
(1100, 768)
(1110, 768)
(1160, 768)
(1020, 768)
(1230, 768)
---------------------------------
(2900, 768)
(1730, 768)
(1970, 768)
(1380, 768)
(1250, 768)
(1100, 768)
(980, 768)
(1250, 768)
(990, 768)
(1290, 768)
(980, 768)
(1260, 768)
(1050, 768)
(1210, 768)
(1150, 768)
---------------------------------
(1010, 768)
(960, 768)
(1100, 768)
(910, 768)
(1015, 768)
(1069, 768)
(1290, 768)
(940, 768)
(1239, 768)
(1240, 768)
(1005, 768)
(1130, 768)
(1240, 768)
(1215, 768)
(1614, 768)
---------------------------------
---------------------------------
(760, 768)
(850, 768)
(680, 768)
(840, 768)
(1230, 768)
(1200, 768)
(1000, 768)
(830, 768)
(810, 768)
(870, 768)
(1090, 768)
(810, 768)
(740, 768)
(1001, 768)
(970, 768)
---------------------------------
(710, 768)
(760, 768)
(620, 768)
(510, 768)
(1110, 768)
(920, 7

In [3]:
# # melexis folder save
# import os

# current_path = os.getcwd()
# os.makedirs(current_path + "/" + "melexisSensor")
# for i in range(1,3):
#     for j in range(1,4):
#         for z in range(1, 16):
#             if(z < 10 and z > 0):
#                 os.makedirs(current_path + "/melexisSensor/" + f'melexisG{i}{j}f0{z}')
                
#             else:
#                 os.makedirs(current_path + "/melexisSensor/" + f'melexisG{i}{j}f0{z}')

In [4]:
# for i in range(2,3):
#     for j in range(1,4):
#         for z in range(1,16):
#             if(z < 10 and z > 0):
#                 mat_file = io.loadmat(f'./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f0{z}-data.mat')
#                 print(mat_file.get(f'melexisG{i}{j}f0{z}').shape)
#                 fig = plt.rcParams['figure.figsize'] = [24, 32]
#                 for img in range(len(mat_file.get(f'melexisG{i}{j}f0{z}'))):
#                     melexis_img = np.array(mat_file.get(f'melexisG{i}{j}f0{z}')[img]).reshape(24,32)
#                     ax = plt.imshow(melexis_img, vmin=17,vmax=23,cmap='viridis', interpolation='nearest')
#                     plt.savefig(f'./melexisSensor/melexisG{i}{j}f0{z}/{img}.png', vmin=17,vmax=23,cmap='viridis' ,interpolation='nearest', dpi=50)
#                     plt.close()
#             else:
#                 mat_file = io.loadmat(f'./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G{i}-{j}-f{z}-data.mat')
#                 print(mat_file.get(f'melexisG{i}{j}f{z}').shape)
#                 fig = plt.rcParams['figure.figsize'] = [24, 32]
#                 for img in range(len(mat_file.get(f'melexisG{i}{j}f0{z}'))):
#                     melexis_img = np.array(mat_file.get(f'melexisG{i}{j}f0{z}')[img]).reshape(24,32)
#                     ax = plt.imshow(melexis_img, vmin=17,vmax=23,cmap='viridis', interpolation='nearest')
#                     plt.savefig(f'./melexisSensor/melexisG{i}{j}f0{z}/{img}.png', vmin=17,vmax=23,cmap='viridis' ,interpolation='nearest', dpi=50)
#                     plt.close()

# 0과 1로 구분하여 정상데이터 구분

In [5]:
def data_merge(data,x1, x2, x3, x4, x5, x6,x7, x8, x9, x10):
    data.loc[0:x1-1,'label'] = 0
    data.loc[x1:x2,'label'] = 1
    data.loc[x2+1:x3-1,'label'] = 0 
    data.loc[x3:x4,'label'] = 1 
    data.loc[x4+1:x5-1,'label'] = 0 
    data.loc[x5:x6,'label'] = 1
    data.loc[x6+1:x7-1,'label'] = 0 
    data.loc[x7:x8,'label'] = 1
    data.loc[x8+1:x9-1,'label'] = 0 
    data.loc[x9:x10,'label'] = 1
    data.loc[x10 +1:,'label'] = 0
    return data

def data_merge2(data,x1, x2, x3, x4, x5, x6,x7, x8, x9, x10,x11,x12):
    data.loc[0:x1-1,'label'] = 0
    data.loc[x1:x2,'label'] = 1
    data.loc[x2+1:x3-1,'label'] = 0 
    data.loc[x3:x4,'label'] = 1 
    data.loc[x4+1:x5-1,'label'] = 0 
    data.loc[x5:x6,'label'] = 1
    data.loc[x6+1:x7-1,'label'] = 0 
    data.loc[x7:x8,'label'] = 1
    data.loc[x8+1:x9-1,'label'] = 0 
    data.loc[x9:x10,'label'] = 1
    data.loc[x10 +1:x11-1,'label'] = 0
    data.loc[x11:x12,'label'] = 1
    data.loc[x12 +1:,'label'] = 0
    return data

## G11 지원자의 DataFrame

In [6]:
import pandas as pd
import csv

mat_file_G11_io = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f01-data.mat')
print(mat_file_G11_io.get('melexisG11f01'))
print(mat_file_G11_io.get('melexisG11f01')[0][0])
G11data1 = pd.DataFrame(mat_file_G11_io.get('melexisG11f01'))
G11data1 = data_merge(G11data1,154, 195, 300, 336, 466, 493, 580, 666, 764, 823)

mat_file_G11_io2 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f02-data.mat')
G11data2 = pd.DataFrame(mat_file_G11_io2.get('melexisG11f02'))
G11data2 = data_merge(G11data2,47, 127, 260, 334, 439, 500, 662, 725, 880, 951)

mat_file_G11_io3 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f03-data.mat')
G11data3 = pd.DataFrame(mat_file_G11_io3.get('melexisG11f03'))
G11data3 = data_merge(G11data3,209, 289, 411, 466, 873, 930, 1130, 1184, 1292, 1340)

mat_file_G11_io4 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f04-data.mat')
G11data4 = pd.DataFrame(mat_file_G11_io4.get('melexisG11f04'))
G11data4 = data_merge(G11data4,212, 255, 371, 411, 496, 548, 673, 718, 812, 873)

mat_file_G11_io5 = io.loadmat('C:/Users/Flora/IR자료/IR자료최종/sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f05-data.mat')
G11data5 = pd.DataFrame(mat_file_G11_io5.get('melexisG11f05'))
G11data5 = data_merge(G11data5,176, 212, 366, 415, 510, 556, 815, 873, 1070, 1143)

mat_file_G11_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f06-data.mat')
G11data6 = pd.DataFrame(mat_file_G11_io6.get('melexisG11f06'))
G11data6 = data_merge2(G11data6,20, 66, 440, 503, 670, 721, 928, 988, 1104, 1151,1301,1409)

mat_file_G11_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f07-data.mat')
G11data7 = pd.DataFrame(mat_file_G11_io7.get('melexisG11f07'))
G11data7 = data_merge(G11data7,148, 199, 414, 459, 608, 668, 976, 1010, 1175, 1269)

mat_file_G11_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f08-data.mat')
G11data8 = pd.DataFrame(mat_file_G11_io8.get('melexisG11f08'))
G11data8 = data_merge(G11data8,212, 270, 372, 414, 505, 557, 645, 719, 830, 881)

mat_file_G11_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f09-data.mat')
G11data9 = pd.DataFrame(mat_file_G11_io9.get('melexisG11f09'))
G11data9 = data_merge(G11data9,186, 231, 378, 417, 512, 565, 701, 749, 863, 938)

mat_file_G11_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f10-data.mat')
G11data10 = pd.DataFrame(mat_file_G11_io10.get('melexisG11f10'))
G11data10 = data_merge(G11data10,147, 196, 320, 350, 484, 525, 655, 700, 825, 900)

mat_file_G11_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f11-data.mat')
G11data11 = pd.DataFrame(mat_file_G11_io11.get('melexisG11f11'))
G11data11 = data_merge(G11data11,321, 360, 484, 519, 613, 639, 763, 810, 979, 1036)

mat_file_G11_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f12-data.mat')
G11data12 = pd.DataFrame(mat_file_G11_io12.get('melexisG11f12'))
G11data12 = data_merge(G11data12,228, 275, 434, 475, 625, 670, 833, 873, 940, 1048)

mat_file_G11_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f13-data.mat')
G11data13 = pd.DataFrame(mat_file_G11_io13.get('melexisG11f13'))
G11data13 = data_merge(G11data13,197, 232, 404, 453, 636, 684, 841, 904, 1075, 1140)

mat_file_G11_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f14-data.mat')
G11data14 = pd.DataFrame(mat_file_G11_io14.get('melexisG11f14'))
G11data14 = data_merge(G11data14,265, 307, 408, 465, 585, 630, 739, 794, 943, 1019)

mat_file_G11_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f15-data.mat')
G11data15 = pd.DataFrame(mat_file_G11_io15.get('melexisG11f15'))
G11data15 = data_merge(G11data15,198, 250, 457, 494, 654, 694, 859, 921, 1108, 1229)

#result = pd.concat([data, data2,data3, data4, data5, data6, data7, data8, data9])

#print(y)
# print(df)
# f = open('./melexisG11f01.csv', 'w', encoding='utf-8', newline='')
# wr = csv.writer(f)
# wr.writerow(df, 0)
# f.close()

[[17.81 17.69 18.23 ... 20.01 18.87 19.17]
 [17.77 17.77 18.17 ... 20.03 21.55 19.19]
 [17.91 17.85 18.13 ... 20.07 20.83 19.07]
 ...
 [17.75 18.07 18.31 ... 19.67 18.79 17.57]
 [17.79 18.09 18.37 ... 19.73 18.79 17.91]
 [17.81 18.17 18.35 ... 19.71 18.77 18.17]]
17.81


In [7]:
G11dataf1 = G11data1[:760]
G11data1_test = G11data1[760:]
G11dataf2 = G11data2[:856]
G11data2_test = G11data2[856:]
G11dataf3 = G11data3[:1292]
G11data3_test = G11data3[1292:]
G11dataf4 = G11data4[:812]
G11data4_test = G11data4[812:]
G11dataf5 = G11data5[:1070]
G11data5_test = G11data5[1070:]
G11dataf6 = G11data6[:1192]
G11data6_test = G11data6[1192:]
G11dataf7 = G11data7[:1080]
G11data7_test = G11data7[1080:]
G11dataf8 = G11data8[:826]
G11data8_test = G11data8[826:]
G11dataf9 = G11data9[:798]
G11data9_test = G11data9[798:]
G11dataf10 = G11data10[:788]
G11data10_test = G11data10[788:]
G11dataf11 = G11data11[:984]
G11data11_test = G11data11[984:]
G11dataf12 = G11data12[:884]
G11data12_test = G11data12[884:]
G11dataf13 = G11data13[:1028]
G11data13_test = G11data13[1028:]
G11dataf14 = G11data14[:866]
G11data14_test = G11data14[866:]
G11dataf15 = G11data15[:986]
G11data15_test = G11data15[986:]
print(G11data1_test.shape)
print(G11data2_test.shape)
print(G11data3_test.shape)
print(G11data4_test.shape)

(120, 769)
(144, 769)
(128, 769)
(118, 769)


## G12 지원자 DataFrame

In [8]:
mat_file_G12_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f01-data.mat')
print(mat_file_G12_io.get('melexisG12f01'))
print(mat_file_G12_io.get('melexisG12f01')[0][0])
G12data1 = pd.DataFrame(mat_file_G12_io.get('melexisG12f01'))
G12data1 = data_merge(G12data1,673, 738, 1418, 1489, 1725, 1814, 2341, 2454, 2796, 2899)
mat_file_G12_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f02-data.mat')
G12data2 = pd.DataFrame(mat_file_G12_io2.get('melexisG12f02'))
G12data2 = data_merge(G12data2,240, 290, 533, 610, 920, 974, 1240, 1320, 1600, 1729)

mat_file_G12_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f03-data.mat')
G12data3 = pd.DataFrame(mat_file_G12_io3.get('melexisG12f03'))
G12data3 = data_merge(G12data3,217, 279, 510, 660, 1097, 1191, 1559, 1622, 1880, 1969)

mat_file_G12_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f04-data.mat')
G12data4 = pd.DataFrame(mat_file_G12_io4.get('melexisG12f04'))
G12data4 = data_merge(G12data4,449, 499, 700, 734, 893, 955, 1091, 1150, 1310, 1379)

mat_file_G12_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f05-data.mat')
G12data5 = pd.DataFrame(mat_file_G12_io5.get('melexisG12f05'))
G12data5 = data_merge(G12data5,310, 363, 539, 579, 712, 765, 902, 952, 1136, 1204)

mat_file_G12_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f06-data.mat')
G12data6 = pd.DataFrame(mat_file_G12_io6.get('melexisG12f06'))
G12data6 = data_merge(G12data6, 156, 259, 415, 469, 658, 717, 823, 950, 1040, 1099)

mat_file_G12_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f07-data.mat')
G12data7 = pd.DataFrame(mat_file_G12_io7.get('melexisG12f07'))
G12data7 = data_merge(G12data7,143, 193, 346, 388, 530, 600, 704, 759, 896, 967)

mat_file_G12_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f08-data.mat')
G12data8 = pd.DataFrame(mat_file_G12_io8.get('melexisG12f08'))
G12data8 = data_merge(G12data8,245,307,470,556,717,771,940,998,1164,1249)

mat_file_G12_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f09-data.mat')
G12data9 = pd.DataFrame(mat_file_G12_io9.get('melexisG12f09'))
G12data9 = data_merge(G12data9,155,228,340,400,511,591,704,767,934,989)

mat_file_G12_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f10-data.mat')
G12data10 = pd.DataFrame(mat_file_G12_io10.get('melexisG12f10'))
G12data10 = data_merge(G12data10,160,251,381,440,603,665,934,1005,1215,1277)

mat_file_G12_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f11-data.mat')
G12data11 = pd.DataFrame(mat_file_G12_io11.get('melexisG12f11'))
G12data11 = data_merge(G12data11,221,278,400,456,568,634,726,775,894,979)

mat_file_G12_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f12-data.mat')
G12data12 = pd.DataFrame(mat_file_G12_io12.get('melexisG12f12'))
G12data12 = data_merge(G12data12,485,570,675,720,820,870,1000,1070,1180,1259)

mat_file_G12_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f13-data.mat')
G12data13 = pd.DataFrame(mat_file_G12_io13.get('melexisG12f13'))
G12data13 = data_merge(G12data13,198,269,427,507,628,680,780,835,957,1049)

mat_file_G12_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f14-data.mat')
G12data14 = pd.DataFrame(mat_file_G12_io14.get('melexisG12f14'))
G12data14 = data_merge(G12data14,182,274,555,620,770,828,961,1030,1140,1209)

mat_file_G12_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f15-data.mat')
G12data15 = pd.DataFrame(mat_file_G12_io15.get('melexisG12f15'))
G12data15 = data_merge(G12data15,137,188,394,440,598,650,815,865,1075,1149)

[[18.73 18.79 19.11 ... 20.01 19.67 19.45]
 [18.67 18.79 19.07 ... 19.99 19.71 19.47]
 [18.63 18.73 19.05 ... 19.91 19.53 19.49]
 ...
 [18.11 18.07 18.65 ... 20.13 19.23 19.33]
 [18.05 18.07 18.59 ... 20.25 19.31 19.39]
 [18.03 18.05 18.55 ... 20.29 19.51 19.47]]
18.73


In [9]:
G12dataf1 = G12data1[:2692]
G12data1_test = G12data1[2692:]
G12dataf2 = G12data2[:1470]
G12data2_test = G12data2[1470:]
G12dataf3 = G12data3[:1790]
G12data3_test = G12data3[1790:]
G12dataf4 = G12data4[:1240]
G12data4_test = G12data4[1240:]
G12dataf5 = G12data5[:1112]
G12data5_test = G12data5[1112:]
G12dataf6 = G12data6[:980]
G12data6_test = G12data6[980:]
G12dataf7 = G12data7[:836]
G12data7_test = G12data7[836:]
G12dataf8 = G12data8[:1078]
G12data8_test = G12data8[1078:]
G12dataf9 = G12data9[:878]
G12data9_test = G12data9[878:]
G12dataf10 = G12data10[:1164]
G12data10_test = G12data10[1164:]
G12dataf11 = G12data11[:808]
G12data11_test = G12data11[808:]
G12dataf12 = G12data12[:1100]
G12data12_test = G12data12[1100:]
G12dataf13 = G12data13[:864]
G12data13_test = G12data13[864:]
G12dataf14 = G12data14[:1070]
G12data14_test = G12data14[1070:]
G12dataf15 = G12data15[:1000]
G12data15_test = G12data15[1000:]

## G13 지원자 DataFrame

In [10]:
mat_file_G13_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f01-data.mat')
print(mat_file_G13_io.get('melexisG13f01'))
print(mat_file_G13_io.get('melexisG13f01')[0][0])
G13data1 = pd.DataFrame(mat_file_G13_io.get('melexisG13f01'))
G13data1 = data_merge(G13data1,122, 180, 288, 380, 478, 580, 680, 794, 892, 982)

mat_file_G13_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f02-data.mat')
G13data2 = pd.DataFrame(mat_file_G13_io2.get('melexisG13f02'))
G13data2 = data_merge(G13data2,100, 155, 298, 372, 510, 570, 712, 774, 880, 943)

mat_file_G13_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f03-data.mat')
G13data3 = pd.DataFrame(mat_file_G13_io3.get('melexisG13f03'))
G13data3 = data_merge(G13data3,78, 150, 304, 364, 583, 670, 834, 880, 1028, 1090)

mat_file_G13_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f04-data.mat')
G13data4 = pd.DataFrame(mat_file_G13_io4.get('melexisG13f04'))
G13data4 = data_merge(G13data4,79, 140, 279, 320, 443, 497, 615, 662, 824, 873)

mat_file_G13_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f05-data.mat')
G13data5 = pd.DataFrame(mat_file_G13_io5.get('melexisG13f05'))
G13data5 = data_merge(G13data5,109, 159, 317, 377, 511, 565, 743, 805, 920, 988)

mat_file_G13_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f06-data.mat')
G13data6 = pd.DataFrame(mat_file_G13_io6.get('melexisG13f06'))
G13data6 = data_merge(G13data6, 114, 194, 354, 410, 570, 620, 762, 799, 978, 1040)

mat_file_G13_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f07-data.mat')
G13data7 = pd.DataFrame(mat_file_G13_io7.get('melexisG13f07'))
G13data7 = data_merge(G13data7,80, 200, 296, 338, 525, 573, 748, 803, 1200, 1260)

mat_file_G13_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f08-data.mat')
G13data8 = pd.DataFrame(mat_file_G13_io8.get('melexisG13f08'))
G13data8 = data_merge(G13data8,88, 134, 247, 289, 451, 510, 668, 730, 833, 884)

mat_file_G13_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f09-data.mat')
G13data9 = pd.DataFrame(mat_file_G13_io9.get('melexisG13f09'))
G13data9 = data_merge(G13data9,119, 189, 342, 408, 555, 629, 869, 922, 1084, 1144)

mat_file_G13_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f10-data.mat')
G13data10 = pd.DataFrame(mat_file_G13_io10.get('melexisG13f10'))
G13data10 = data_merge(G13data10,118, 190, 350, 420, 560, 660, 873, 973, 1087, 1166)

mat_file_G13_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f11-data.mat')
G13data11 = pd.DataFrame(mat_file_G13_io11.get('melexisG13f11'))
G13data11 = data_merge(G13data11,63, 120, 290, 333, 530, 590, 718, 770, 911, 968)

mat_file_G13_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f12-data.mat')
G13data12 = pd.DataFrame(mat_file_G13_io12.get('melexisG13f12'))
G13data12 = data_merge(G13data12,144, 230, 450, 520, 655, 730, 863, 928, 1047, 1114)

mat_file_G13_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f13-data.mat')
G13data13 = pd.DataFrame(mat_file_G13_io13.get('melexisG13f13'))
G13data13 = data_merge(G13data13,169, 246, 410, 535, 692, 750, 905, 970, 1157, 1220)

mat_file_G13_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f14-data.mat')
G13data14 = pd.DataFrame(mat_file_G13_io14.get('melexisG13f14'))
G13data14 = data_merge(G13data14,121, 197, 372, 434, 588, 651, 794, 861, 1037, 1131)

mat_file_G13_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-3-f15-data.mat')
G13data15 = pd.DataFrame(mat_file_G13_io15.get('melexisG13f15'))
G13data15 = data_merge(G13data15,194, 272, 644, 679, 960, 1023, 1234, 1303, 1518, 1590)

[[18.97 18.83 18.85 ... 20.45 20.09 19.43]
 [18.97 18.85 18.85 ... 20.37 20.01 19.49]
 [18.97 18.87 19.05 ... 20.51 20.01 19.49]
 ...
 [18.87 18.91 19.01 ... 20.21 19.37 20.29]
 [18.83 18.99 18.99 ... 20.35 19.41 20.33]
 [18.79 18.95 18.95 ... 20.31 19.43 20.35]]
18.97


In [11]:
G13dataf1 = G13data1[:828]
G13data1_test = G13data1[828:]
G13dataf2 = G13data2[:832]
G13data2_test = G13data2[832:]
G13dataf3 = G13data3[:974]
G13data3_test = G13data3[974:]
G13dataf4 = G13data4[:810]
G13data4_test = G13data4[810:]
G13dataf5 = G13data5[:877]
G13data5_test = G13data5[877:]
G13dataf6 = G13data6[:943]
G13data6_test = G13data6[943:]
G13dataf7 = G13data7[:1168]
G13data7_test = G13data7[1168:]
G13dataf8 = G13data8[:836]
G13data8_test = G13data8[836:]
G13dataf9 = G13data9[:1084]
G13data9_test = G13data9[1084:]
G13dataf10 = G13data10[:1080]
G13data10_test = G13data10[1080:]
G13dataf11 = G13data11[:889]
G13data11_test = G13data11[889:]
G13dataf12 = G13data12[:994]
G13data12_test = G13data12[994:]
G13dataf13 = G13data13[:1112]
G13data13_test = G13data13[1112:]
G13dataf14 = G13data14[:1025]
G13data14_test = G13data14[1025:]
G13dataf15 = G13data15[:1468]
G13data15_test = G13data15[1468:]
print(G13data2_test.shape)

(128, 769)


## G21 지원자 DataFrame

In [12]:
mat_file_G21_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f01-data.mat')
print(mat_file_G21_io.get('melexisG21f01'))
print(mat_file_G21_io.get('melexisG21f01')[0][0])
G21data1 = pd.DataFrame(mat_file_G21_io.get('melexisG21f01'))
G21data1 = data_merge(G21data1,57, 120, 218, 290, 408, 465, 566, 609, 719, 759)

mat_file_G21_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f02-data.mat')
G21data2 = pd.DataFrame(mat_file_G21_io2.get('melexisG21f02'))
G21data2 = data_merge(G21data2,147,192, 321,360, 471,510, 639,680, 809,849)

mat_file_G21_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f03-data.mat')
G21data3 = pd.DataFrame(mat_file_G21_io3.get('melexisG21f03'))
G21data3 = data_merge(G21data3,45, 90, 190, 239, 330, 375, 480, 523, 631, 679)

mat_file_G21_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f04-data.mat')
G21data4 = pd.DataFrame(mat_file_G21_io4.get('melexisG21f04'))
G21data4 = data_merge(G21data4,125, 160, 283, 331, 439, 486, 604, 666, 760, 839)

mat_file_G21_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f05-data.mat')
G21data5 = pd.DataFrame(mat_file_G21_io5.get('melexisG21f05'))
G21data5 = data_merge(G21data5,150, 213, 420, 462, 698, 752, 991, 1027, 1189, 1222)

mat_file_G21_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f06-data.mat')
G21data6 = pd.DataFrame(mat_file_G21_io6.get('melexisG21f06'))
G21data6 = data_merge(G21data6, 148, 193, 390, 437, 637, 680, 887, 925, 1117, 1188)

mat_file_G21_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f07-data.mat')
G21data7 = pd.DataFrame(mat_file_G21_io7.get('melexisG21f07'))
G21data7 = data_merge(G21data7,89, 135, 300, 347, 483, 525, 716, 751, 933, 985)

mat_file_G21_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f08-data.mat')
G21data8 = pd.DataFrame(mat_file_G21_io8.get('melexisG21f08'))
G21data8 = data_merge(G21data8,131, 181, 281, 305, 451, 481, 611, 665, 776, 829)

mat_file_G21_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f09-data.mat')
G21data9 = pd.DataFrame(mat_file_G21_io9.get('melexisG21f09'))
G21data9 = data_merge(G21data9,160, 197, 323, 376, 475, 503, 617, 658, 751, 791)

mat_file_G21_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f10-data.mat')
G21data10 = pd.DataFrame(mat_file_G21_io10.get('melexisG21f10'))
G21data10 = data_merge(G21data10,41, 100, 240, 287, 447, 480, 630, 672, 800, 840)

mat_file_G21_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f11-data.mat')
G21data11 = pd.DataFrame(mat_file_G21_io11.get('melexisG21f11'))
G21data11 = data_merge(G21data11,136, 182, 321, 341, 562, 603, 741, 780, 1004, 1072)

mat_file_G21_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f12-data.mat')
G21data12 = pd.DataFrame(mat_file_G21_io12.get('melexisG21f12'))
G21data12 = data_merge(G21data12,79, 112, 250, 302, 435, 483, 581, 640, 752, 809)

mat_file_G21_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f13-data.mat')
G21data13 = pd.DataFrame(mat_file_G21_io13.get('melexisG21f13'))
G21data13 = data_merge(G21data13,40, 92, 194, 269, 348, 415, 522, 579, 682, 727)

mat_file_G21_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f14-data.mat')
G21data14 = pd.DataFrame(mat_file_G21_io14.get('melexisG21f14'))
G21data14 = data_merge(G21data14,148, 191, 319, 374, 495, 546, 691, 752, 892, 945)

mat_file_G21_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f15-data.mat')
G21data15 = pd.DataFrame(mat_file_G21_io15.get('melexisG21f15'))
G21data15 = data_merge(G21data15,120, 141, 348, 389, 548, 584, 736, 767, 915, 957)

[[17.97 18.07 17.79 ... 19.89 18.61 18.41]
 [18.01 18.07 17.87 ... 19.77 18.57 18.39]
 [18.03 18.09 17.97 ... 19.65 18.55 18.35]
 ...
 [17.79 18.01 17.79 ... 19.31 18.47 18.11]
 [17.87 17.93 17.85 ... 19.33 18.39 18.05]
 [17.79 17.87 17.77 ... 19.27 18.15 18.19]]
17.97


In [13]:
G21dataf1 = G21data1[:678]
G21data1_test = G21data1[678:]
G21dataf2 = G21data2[:774]
G21data2_test = G21data2[774:]
G21dataf3 = G21data3[:595]
G21data3_test = G21data3[595:]
G21dataf4 = G21data4[:682]
G21data4_test = G21data4[682:]
G21dataf5 = G21data5[:1162]
G21data5_test = G21data5[1162:]
G21dataf6 = G21data6[:1060]
G21data6_test = G21data6[1060:]
G21dataf7 = G21data7[:911]
G21data7_test = G21data7[911:]
G21dataf8 = G21data8[:727]
G21data8_test = G21data8[727:]
G21dataf9 = G21data9[:729]
G21data9_test = G21data9[729:]
G21dataf10 = G21data10[:803]
G21data10_test = G21data10[803:]
G21dataf11 = G21data11[:952]
G21data11_test = G21data11[952:]
G21dataf12 = G21data12[:694]
G21data12_test = G21data12[694:]
G21dataf13 = G21data13[:648]
G21data13_test = G21data13[648:]
G21dataf14 = G21data14[:893]
G21data14_test = G21data14[893:]
G21dataf15 = G21data15[:884]
G21data15_test = G21data15[884:]

## G22 지원자 DataFrame

In [14]:
mat_file_G22_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f01-data.mat')
print(mat_file_G22_io.get('melexisG22f01'))
print(mat_file_G22_io.get('melexisG22f01')[0][0])
G22data1 = pd.DataFrame(mat_file_G22_io.get('melexisG22f01'))
G22data1 = data_merge(G22data1,90, 112, 228, 254, 382, 401, 525, 550, 660, 699)

mat_file_G22_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f02-data.mat')
G22data2 = pd.DataFrame(mat_file_G22_io2.get('melexisG22f02'))
G22data2 = data_merge(G22data2,102, 138, 230, 257, 365, 391, 496, 526, 699, 727)

mat_file_G22_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f03-data.mat')
G22data3 = pd.DataFrame(mat_file_G22_io3.get('melexisG22f03'))
G22data3 = data_merge(G22data3,65, 89, 177, 207, 325, 365, 426, 448, 572, 614)

mat_file_G22_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f04-data.mat')
G22data4 = pd.DataFrame(mat_file_G22_io4.get('melexisG22f04'))
G22data4 = data_merge(G22data4,66, 89, 171, 199, 259, 285, 367, 389, 476, 509)

mat_file_G22_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f05-data.mat')
G22data5 = pd.DataFrame(mat_file_G22_io5.get('melexisG22f05'))
G22data5 = data_merge(G22data5,0, 33, 142, 250, 550, 586, 705, 743, 1007, 1080)

mat_file_G22_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f06-data.mat')
G22data6 = pd.DataFrame(mat_file_G22_io6.get('melexisG22f06'))
G22data6 = data_merge(G22data6, 47, 88, 260, 282, 465, 498, 620, 671, 847, 888)

mat_file_G22_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f07-data.mat')
G22data7 = pd.DataFrame(mat_file_G22_io7.get('melexisG22f07'))
G22data7 = data_merge(G22data7,235, 274, 398, 430, 578, 608, 806, 840, 992, 1043)

mat_file_G22_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f08-data.mat')
G22data8 = pd.DataFrame(mat_file_G22_io8.get('melexisG22f08'))
G22data8 = data_merge(G22data8,172, 210, 347, 380, 462, 485, 577, 600, 678, 708)

mat_file_G22_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f09-data.mat')
G22data9 = pd.DataFrame(mat_file_G22_io9.get('melexisG22f09'))
G22data9 = data_merge(G22data9,100, 130, 218, 243, 332, 373, 428, 458, 527, 559)

mat_file_G22_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f10-data.mat')
G22data10 = pd.DataFrame(mat_file_G22_io10.get('melexisG22f10'))
G22data10 = data_merge(G22data10,54, 84, 208, 240, 350, 370, 490, 513, 610, 637)

mat_file_G22_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f11-data.mat')
G22data11 = pd.DataFrame(mat_file_G22_io11.get('melexisG22f11'))
G22data11 = data_merge(G22data11,20, 57, 179, 214, 385, 430, 631, 679, 870, 925)

mat_file_G22_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f12-data.mat')
G22data12 = pd.DataFrame(mat_file_G22_io12.get('melexisG22f12'))
G22data12 = data_merge(G22data12,87, 110, 213, 231, 317, 351, 454, 475, 565, 587)

mat_file_G22_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f13-data.mat')
G22data13 = pd.DataFrame(mat_file_G22_io13.get('melexisG22f13'))
G22data13 = data_merge(G22data13,145, 171, 269, 300, 405, 440, 529, 563, 647, 689)

mat_file_G22_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f14-data.mat')
G22data14 = pd.DataFrame(mat_file_G22_io14.get('melexisG22f14'))
G22data14 = data_merge(G22data14,67, 88, 192, 220, 330, 354, 454, 481, 577, 600)

mat_file_G22_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-2-f15-data.mat')
G22data15 = pd.DataFrame(mat_file_G22_io15.get('melexisG22f15'))
G22data15 = data_merge(G22data15,77, 110, 224, 254, 388, 416, 540, 571, 683, 729)

[[17.85 17.83 17.93 ... 18.95 18.01 17.81]
 [17.83 17.83 17.95 ... 18.99 18.11 17.75]
 [17.79 17.73 17.95 ... 19.01 18.07 17.67]
 ...
 [17.51 17.67 17.51 ... 19.17 18.09 18.33]
 [17.37 17.69 17.49 ... 19.11 18.07 18.31]
 [17.39 17.71 17.47 ... 19.07 18.07 18.53]]
17.85


In [15]:
G22dataf1 = G22data1[:635]
G22data1_test = G22data1[635:]
G22dataf2 = G22data2[:709]
G22data2_test = G22data2[709:]
G22dataf3 = G22data3[:534]
G22data3_test = G22data3[534:]
G22dataf4 = G22data4[:453]
G22data4_test = G22data4[453:]
G22dataf5 = G22data5[:1052]
G22data5_test = G22data5[1052:]
G22dataf6 = G22data6[:858]
G22data6_test = G22data6[858:]
G22dataf7 = G22data7[:992]
G22data7_test = G22data7[992:]
G22dataf8 = G22data8[:688]
G22data8_test = G22data8[688:]
G22dataf9 = G22data9[:492]
G22data9_test = G22data9[492:]
G22dataf10 = G22data10[:610]
G22data10_test = G22data10[610:]
G22dataf11 = G22data11[:818]
G22data11_test = G22data11[818:]
G22dataf12 = G22data12[:566]
G22data12_test = G22data12[566:]
G22dataf13 = G22data13[:604]
G22data13_test = G22data13[604:]
G22dataf14 = G22data14[:587]
G22data14_test = G22data14[587:]
G22dataf15 = G22data15[:636]
G22data15_test = G22data15[636:]

## G23 지원자 DataFrame

In [16]:
mat_file_G23_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f01-data.mat')
print(mat_file_G23_io.get('melexisG23f01'))
print(mat_file_G23_io.get('melexisG23f01')[0][0])
G23data1 = pd.DataFrame(mat_file_G23_io.get('melexisG23f01'))
G23data1 = data_merge(G23data1,98, 194, 337, 430, 538, 600, 736, 793, 925, 999)

mat_file_G23_io2 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f02-data.mat')
G23data2 = pd.DataFrame(mat_file_G23_io2.get('melexisG23f02'))
G23data2 = data_merge(G23data2,76, 132, 261, 312, 447, 497, 630, 682, 790, 838)

mat_file_G23_io3 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f03-data.mat')
G23data3 = pd.DataFrame(mat_file_G23_io3.get('melexisG23f03'))
G23data3 = data_merge(G23data3,67, 136, 230, 310, 431, 500, 609, 672, 789, 850)

mat_file_G23_io4 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f04-data.mat')
G23data4 = pd.DataFrame(mat_file_G23_io4.get('melexisG23f04'))
G23data4 = data_merge(G23data4,86, 150, 265, 320, 414, 463, 585, 642, 718, 759)

mat_file_G23_io5 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f05-data.mat')
G23data5 = pd.DataFrame(mat_file_G23_io5.get('melexisG23f05'))
G23data5 = data_merge(G23data5,144, 176, 341, 374, 626, 675, 902, 941, 1185, 1243)

mat_file_G23_io6 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f06-data.mat')
G23data6 = pd.DataFrame(mat_file_G23_io6.get('melexisG23f06'))
G23data6 = data_merge(G23data6, 56, 158, 463, 501, 746, 820, 1004, 1070, 1215, 1269)

mat_file_G23_io7 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f07-data.mat')
G23data7 = pd.DataFrame(mat_file_G23_io7.get('melexisG23f07'))
G23data7 = data_merge(G23data7,94, 145, 325, 377, 552, 594, 723, 790, 950, 999)

mat_file_G23_io8 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f08-data.mat')
G23data8 = pd.DataFrame(mat_file_G23_io8.get('melexisG23f08'))
G23data8 = data_merge(G23data8,32, 92, 228, 267, 380, 436, 542, 595, 711, 759)

mat_file_G23_io9 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f09-data.mat')
G23data9 = pd.DataFrame(mat_file_G23_io9.get('melexisG23f09'))
G23data9 = data_merge(G23data9,148,204, 330, 396, 571, 626, 749, 799, 917, 969)

mat_file_G23_io10 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f10-data.mat')
G23data10 = pd.DataFrame(mat_file_G23_io10.get('melexisG23f10'))
G23data10 = data_merge(G23data10,49, 140, 289, 365, 458, 530, 634, 695, 834, 889)

mat_file_G23_io11 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f11-data.mat')
G23data11 = pd.DataFrame(mat_file_G23_io11.get('melexisG23f11'))
G23data11 = data_merge(G23data11,64, 140, 254, 311, 476, 554, 664, 733, 912, 969)

mat_file_G23_io12 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f12-data.mat')
G23data12 = pd.DataFrame(mat_file_G23_io12.get('melexisG23f12'))
G23data12 = data_merge(G23data12,56, 101, 204, 262, 366, 430, 517, 580, 666, 719)

mat_file_G23_io13 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f13-data.mat')
G23data13 = pd.DataFrame(mat_file_G23_io13.get('melexisG23f13'))
G23data13 = data_merge(G23data13,75, 160, 315, 393, 510, 580, 678, 744, 857, 909)

mat_file_G23_io14 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f14-data.mat')
G23data14 = pd.DataFrame(mat_file_G23_io14.get('melexisG23f14'))
G23data14 = data_merge(G23data14,79, 126, 250, 304, 443, 492, 608, 677, 804, 869)

mat_file_G23_io15 = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-3-f15-data.mat')
G23data15 = pd.DataFrame(mat_file_G23_io15.get('melexisG23f15'))
G23data15 = data_merge(G23data15,114, 170, 274, 325, 459, 578, 719, 797, 935, 989)

[[17.67 17.75 17.59 ... 18.83 18.13 18.57]
 [17.75 17.83 17.55 ... 18.79 18.01 18.43]
 [17.83 17.93 17.53 ... 18.77 17.93 18.33]
 ...
 [17.53 17.37 17.91 ... 19.03 17.65 15.91]
 [17.49 17.41 17.91 ... 19.13 17.67 15.91]
 [17.45 17.43 17.89 ... 19.13 17.77 15.89]]
17.67


In [17]:
G23dataf1 = G23data1[:850]
G23data1_test = G23data1[850:]
G23dataf2 = G23data2[:772]
G23data2_test = G23data2[772:]
G23dataf3 = G23data3[:736]
G23data3_test = G23data3[736:]
G23dataf4 = G23data4[:676]
G23data4_test = G23data4[676:]
G23dataf5 = G23data5[:1132]
G23data5_test = G23data5[1132:]
G23dataf6 = G23data6[:1160]
G23data6_test = G23data6[1160:]
G23dataf7 = G23data7[:900]
G23data7_test = G23data7[900:]
G23dataf8 = G23data8[:660]
G23data8_test = G23data8[660:]
G23dataf9 = G23data9[:850]
G23data9_test = G23data9[850:]
G23dataf10 = G23data10[:780]
G23data10_test = G23data10[780:]
G23dataf11 = G23data11[:860]
G23data11_test = G23data11[860:]
G23dataf12 = G23data12[:610]
G23data12_test = G23data12[610:]
G23dataf13 = G23data13[:800]
G23data13_test = G23data13[800:]
G23dataf14 = G23data14[:740]
G23data14_test = G23data14[740:]
G23dataf15 = G23data15[:880]
G23data15_test = G23data15[880:]
print(G23data15_test.shape)

(110, 769)


# 다 합쳐서 테스트 데이터 만듦

In [18]:
result = pd.concat([G11dataf1, G11dataf2,G11dataf3, G11dataf4, G11dataf5, G11dataf6, G11dataf7, G11dataf8, G11dataf9, G11dataf10,
                    G11dataf11, G11dataf12, G11dataf13, G11dataf14, G11dataf15,G12dataf1, G12dataf2,G12dataf3, G12dataf4, G12dataf5, 
                    G12dataf6, G12dataf7, G12dataf8, G12dataf9, G12dataf10, G12dataf11, G12dataf12, G12dataf13, G12dataf14, G12dataf15,
                    G13dataf1, G13dataf2,G13dataf3, G13dataf4, G13dataf5, G13dataf6, G13dataf7, G13dataf8, G13dataf9, G13dataf10,
                    G13dataf11, G13dataf12,G13dataf13, G13dataf14, G13dataf15,G21dataf1, G21dataf2,G21dataf3, G21dataf4, G21dataf5, 
                    G21dataf6, G21dataf7, G21dataf8, G21dataf9, G21dataf10, G21dataf11, G21dataf12, G21dataf13, G21dataf14, G21dataf15,
                    G22dataf1, G22dataf2,G22dataf3, G22dataf4, G22dataf5, G22dataf6, G22dataf7, G22dataf8, G22dataf9, G22dataf10,
                    G22dataf11, G22dataf12, G22dataf13, G22dataf14, G22dataf15,G23dataf1, G23dataf2,G23dataf3, G23dataf4, G23dataf5, 
                    G23dataf6, G23dataf7, G23dataf8, G23dataf9, G23dataf10, G23dataf11, G23dataf12, G23dataf13, G23dataf14, G23dataf15])
print(result.shape)
X, y = result.drop(['label'], axis=1), result['label']
print(X.shape)
print(y.shape)

(82056, 769)
(82056, 768)
(82056,)


In [19]:
result_test = pd.concat([G11data1_test, G11data2_test,G11data3_test, G11data4_test, G11data5_test, G11data6_test, G11data7_test, G11data8_test, G11data9_test, G11data10_test, G11data11_test, G11data12_test, 
                    G11data13_test, G11data14_test, G11data15_test,G12data1_test, G12data2_test,G12data3_test, G12data4_test, G12data5_test, G12data6_test, G12data7_test, G12data8_test, G12data9_test, 
                    G12data10_test, G12data11_test, G12data12_test,G12data13_test, G12data14_test, G12data15_test,G13data1_test, G13data2_test,G13data3_test, G13data4_test, G13data5_test, G13data6_test, 
                    G13data7_test, G13data8_test, G13data9_test, G13data10_test, G13data11_test, G13data12_test,G13data13_test, G13data14_test, G13data15_test,G21data1_test, G21data2_test,G21data3_test, 
                    G21data4_test, G21data5_test, G21data6_test, G21data7_test, G21data8_test, G21data9_test, G21data10_test, G21data11_test, G21data12_test,G21data13_test, G21data14_test, G21data15_test,
                   G22data1_test, G22data2_test,G22data3_test, G22data4_test, G22data5_test, G22data6_test, G22data7_test, G22data8_test, G22data9_test, G22data10_test, G22data11_test, G22data12_test,
                    G22data13_test, G22data14_test, G22data15_test,G23data1_test, G23data2_test,G23data3_test, G23data4_test, G23data5_test, G23data6_test, G23data7_test, G23data8_test, G23data9_test, 
                    G23data10_test, G23data11_test, G23data12_test, G23data13_test, G23data14_test, G23data15_test])
X_test, y_test = result_test.drop(['label'],axis=1), result_test['label']
print(X_test.shape)
print(y_test.shape)
print(result_test.shape)

(11112, 768)
(11112,)
(11112, 769)


In [20]:
X = X.where(pd.notnull(X), X.mean(), axis='columns')
print(X.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
763    0
764    0
765    0
766    0
767    0
Length: 768, dtype: int64


## 각 지원자 null 값 제거

In [21]:
G11data1_test=G11data1_test.where(pd.notnull(G11data1_test),G11data1_test.mean(), axis='columns')
G11data2_test=G11data2_test.where(pd.notnull(G11data2_test),G11data2_test.mean(), axis='columns')
G11data3_test=G11data3_test.where(pd.notnull(G11data3_test),G11data3_test.mean(), axis='columns')
G11data4_test=G11data4_test.where(pd.notnull(G11data4_test),G11data4_test.mean(), axis='columns')
G11data5_test=G11data5_test.where(pd.notnull(G11data5_test),G11data5_test.mean(), axis='columns')
G11data6_test=G11data6_test.where(pd.notnull(G11data6_test),G11data6_test.mean(), axis='columns')
G11data7_test=G11data7_test.where(pd.notnull(G11data7_test),G11data7_test.mean(), axis='columns')
G11data8_test=G11data8_test.where(pd.notnull(G11data8_test),G11data8_test.mean(), axis='columns')
G11data9_test=G11data9_test.where(pd.notnull(G11data9_test),G11data9_test.mean(), axis='columns')
G11data10_test=G11data10_test.where(pd.notnull(G11data10_test),G11data10_test.mean(), axis='columns')
G11data11_test=G11data11_test.where(pd.notnull(G11data11_test),G11data11_test.mean(), axis='columns')
G11data12_test=G11data12_test.where(pd.notnull(G11data12_test),G11data12_test.mean(), axis='columns')
G11data13_test=G11data13_test.where(pd.notnull(G11data13_test),G11data13_test.mean(), axis='columns')
G11data14_test=G11data14_test.where(pd.notnull(G11data14_test),G11data14_test.mean(), axis='columns')
G11data15_test=G11data15_test.where(pd.notnull(G11data15_test),G11data15_test.mean(), axis='columns')
G12data1_test=G12data1_test.where(pd.notnull(G12data1_test),G12data1_test.mean(), axis='columns')
G12data2_test=G12data2_test.where(pd.notnull(G12data2_test),G12data2_test.mean(), axis='columns')
G12data3_test=G12data3_test.where(pd.notnull(G12data3_test),G12data3_test.mean(), axis='columns')
G12data4_test=G12data4_test.where(pd.notnull(G12data4_test),G12data4_test.mean(), axis='columns')
G12data5_test=G12data5_test.where(pd.notnull(G12data5_test),G12data5_test.mean(), axis='columns')
G12data6_test=G12data6_test.where(pd.notnull(G12data6_test),G12data6_test.mean(), axis='columns')
G12data7_test=G12data7_test.where(pd.notnull(G12data7_test),G12data7_test.mean(), axis='columns')
G12data8_test=G12data8_test.where(pd.notnull(G12data8_test),G12data8_test.mean(), axis='columns')
G12data9_test=G12data9_test.where(pd.notnull(G12data9_test),G12data9_test.mean(), axis='columns')
G12data10_test=G12data10_test.where(pd.notnull(G12data10_test),G12data10_test.mean(), axis='columns')
G12data11_test=G12data11_test.where(pd.notnull(G12data11_test),G12data11_test.mean(), axis='columns')
G12data12_test=G12data12_test.where(pd.notnull(G12data12_test),G12data12_test.mean(), axis='columns')
G12data13_test=G12data13_test.where(pd.notnull(G12data13_test),G12data13_test.mean(), axis='columns')
G12data14_test=G12data14_test.where(pd.notnull(G12data14_test),G12data14_test.mean(), axis='columns')
G12data15_test=G12data15_test.where(pd.notnull(G12data15_test),G12data15_test.mean(), axis='columns')
G13data1_test=G13data1_test.where(pd.notnull(G13data1_test),G13data1_test.mean(), axis='columns')
G13data2_test=G13data2_test.where(pd.notnull(G13data2_test),G13data2_test.mean(), axis='columns')
G13data3_test=G13data3_test.where(pd.notnull(G13data3_test),G13data3_test.mean(), axis='columns')
G13data4_test=G13data4_test.where(pd.notnull(G13data4_test),G13data4_test.mean(), axis='columns')
G13data5_test=G13data5_test.where(pd.notnull(G13data5_test),G13data5_test.mean(), axis='columns')
G13data6_test=G13data6_test.where(pd.notnull(G13data6_test),G13data6_test.mean(), axis='columns')
G13data7_test=G13data7_test.where(pd.notnull(G13data7_test),G13data7_test.mean(), axis='columns')
G13data8_test=G13data8_test.where(pd.notnull(G13data8_test),G13data8_test.mean(), axis='columns')
G13data9_test=G13data9_test.where(pd.notnull(G13data9_test),G13data9_test.mean(), axis='columns')
G13data10_test=G13data10_test.where(pd.notnull(G13data10_test),G13data10_test.mean(), axis='columns')
G13data11_test=G13data11_test.where(pd.notnull(G13data11_test),G13data11_test.mean(), axis='columns')
G13data12_test=G13data12_test.where(pd.notnull(G13data12_test),G13data12_test.mean(), axis='columns')
G13data13_test=G13data13_test.where(pd.notnull(G13data13_test),G13data13_test.mean(), axis='columns')
G13data14_test=G13data14_test.where(pd.notnull(G13data14_test),G13data14_test.mean(), axis='columns')
G13data15_test=G13data15_test.where(pd.notnull(G13data15_test),G13data15_test.mean(), axis='columns')
G21data1_test=G21data1_test.where(pd.notnull(G21data1_test),G21data1_test.mean(), axis='columns')
G21data2_test=G21data2_test.where(pd.notnull(G21data2_test),G21data2_test.mean(), axis='columns')
G21data3_test=G21data3_test.where(pd.notnull(G21data3_test),G21data3_test.mean(), axis='columns')
G21data4_test=G21data4_test.where(pd.notnull(G21data4_test),G21data4_test.mean(), axis='columns')
G21data5_test=G21data5_test.where(pd.notnull(G21data5_test),G21data5_test.mean(), axis='columns')
G21data6_test=G21data6_test.where(pd.notnull(G21data6_test),G21data6_test.mean(), axis='columns')
G21data7_test=G21data7_test.where(pd.notnull(G21data7_test),G21data7_test.mean(), axis='columns')
G21data8_test=G21data8_test.where(pd.notnull(G21data8_test),G21data8_test.mean(), axis='columns')
G21data9_test=G21data9_test.where(pd.notnull(G21data9_test),G21data9_test.mean(), axis='columns')
G21data10_test=G21data10_test.where(pd.notnull(G21data10_test),G21data10_test.mean(), axis='columns')
G21data11_test=G21data11_test.where(pd.notnull(G21data11_test),G21data11_test.mean(), axis='columns')
G21data12_test=G21data12_test.where(pd.notnull(G21data12_test),G21data12_test.mean(), axis='columns')
G21data13_test=G21data13_test.where(pd.notnull(G21data13_test),G21data13_test.mean(), axis='columns')
G21data14_test=G21data14_test.where(pd.notnull(G21data14_test),G21data14_test.mean(), axis='columns')
G21data15_test=G21data15_test.where(pd.notnull(G21data15_test),G21data15_test.mean(), axis='columns')
G22data1_test=G22data1_test.where(pd.notnull(G22data1_test),G22data1_test.mean(), axis='columns')
G22data2_test=G22data2_test.where(pd.notnull(G22data2_test),G22data2_test.mean(), axis='columns')
G22data3_test=G22data3_test.where(pd.notnull(G22data3_test),G22data3_test.mean(), axis='columns')
G22data4_test=G22data4_test.where(pd.notnull(G22data4_test),G22data4_test.mean(), axis='columns')
G22data5_test=G22data5_test.where(pd.notnull(G22data5_test),G22data5_test.mean(), axis='columns')
G22data6_test=G22data6_test.where(pd.notnull(G22data6_test),G22data6_test.mean(), axis='columns')
G22data7_test=G22data7_test.where(pd.notnull(G22data7_test),G22data7_test.mean(), axis='columns')
G22data8_test=G22data8_test.where(pd.notnull(G22data8_test),G22data8_test.mean(), axis='columns')
G22data9_test=G22data9_test.where(pd.notnull(G22data9_test),G22data9_test.mean(), axis='columns')
G22data10_test=G22data10_test.where(pd.notnull(G22data10_test),G22data10_test.mean(), axis='columns')
G22data11_test=G22data11_test.where(pd.notnull(G22data11_test),G22data11_test.mean(), axis='columns')
G22data12_test=G22data12_test.where(pd.notnull(G22data12_test),G22data12_test.mean(), axis='columns')
G22data13_test=G22data13_test.where(pd.notnull(G22data13_test),G22data13_test.mean(), axis='columns')
G22data14_test=G22data14_test.where(pd.notnull(G22data14_test),G22data14_test.mean(), axis='columns')
G22data15_test=G22data15_test.where(pd.notnull(G22data15_test),G22data15_test.mean(), axis='columns')
G23data1_test=G23data1_test.where(pd.notnull(G23data1_test),G23data1_test.mean(), axis='columns')
G23data2_test=G23data2_test.where(pd.notnull(G23data2_test),G23data2_test.mean(), axis='columns')
G23data3_test=G23data3_test.where(pd.notnull(G23data3_test),G23data3_test.mean(), axis='columns')
G23data4_test=G23data4_test.where(pd.notnull(G23data4_test),G23data4_test.mean(), axis='columns')
G23data5_test=G23data5_test.where(pd.notnull(G23data5_test),G23data5_test.mean(), axis='columns')
G23data6_test=G23data6_test.where(pd.notnull(G23data6_test),G23data6_test.mean(), axis='columns')
G23data7_test=G23data7_test.where(pd.notnull(G23data7_test),G23data7_test.mean(), axis='columns')
G23data8_test=G23data8_test.where(pd.notnull(G23data8_test),G23data8_test.mean(), axis='columns')
G23data9_test=G23data9_test.where(pd.notnull(G23data9_test),G23data9_test.mean(), axis='columns')
G23data10_test=G23data10_test.where(pd.notnull(G23data10_test),G23data10_test.mean(), axis='columns')
G23data11_test=G23data11_test.where(pd.notnull(G23data11_test),G23data11_test.mean(), axis='columns')
G23data12_test=G23data12_test.where(pd.notnull(G23data12_test),G23data12_test.mean(), axis='columns')
G23data13_test=G23data13_test.where(pd.notnull(G23data13_test),G23data13_test.mean(), axis='columns')
G23data14_test=G23data14_test.where(pd.notnull(G23data14_test),G23data14_test.mean(), axis='columns')
G23data15_test=G23data15_test.where(pd.notnull(G23data15_test),G23data15_test.mean(), axis='columns')

In [22]:
print(G11data5_test.isnull().sum())

0        0
1        0
2        0
3        0
4        0
        ..
764      0
765      0
766      0
767      0
label    0
Length: 769, dtype: int64


In [23]:
y.value_counts()

0.0    62297
1.0    19759
Name: label, dtype: int64

In [24]:
y_test.value_counts()

0.0    5627
1.0    5485
Name: label, dtype: int64

In [25]:
X = X.where(pd.notnull(X), X.mean(), axis='columns')
print(X.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
763    0
764    0
765    0
766    0
767    0
Length: 768, dtype: int64


In [26]:
X_test = X_test.where(pd.notnull(X_test), X_test.mean(), axis='columns')

In [27]:
print(X_test.isnull().sum())

0      0
1      0
2      0
3      0
4      0
      ..
763    0
764    0
765    0
766    0
767    0
Length: 768, dtype: int64


In [28]:
X_train, y_train = X, y

In [29]:
# X_train, X_test,y_train, y_test = X[:70944], X[70944:], y[:70944], y[70944:]

In [30]:
def plot_roc_curve(fprs, tprs):
    """Plot the Receiver Operating Characteristic from a list
    of true positive rates and false positive rates."""
    
    # Initialize useful lists + the plot axes.
    tprs_interp = []
    aucs = []
    mean_fpr = np.linspace(0, 1, 100)
    f, ax = plt.subplots(figsize=(14,10))
    
    # Plot ROC for each K-Fold + compute AUC scores.
    for i, (fpr, tpr) in enumerate(zip(fprs, tprs)):
        tprs_interp.append(np.interp(mean_fpr, fpr, tpr))
        tprs_interp[-1][0] = 0.0
        roc_auc = auc(fpr, tpr)
        aucs.append(roc_auc)
        ax.plot(fpr, tpr, lw=1, alpha=0.3,
                 label='ROC fold %d (AUC = %0.2f)' % (i, roc_auc))
        
    # Plot the luck line.
    plt.plot([0, 1], [0, 1], linestyle='--', lw=2, color='r',
             label='Luck', alpha=.8)
    
    # Plot the mean ROC.
    mean_tpr = np.mean(tprs_interp, axis=0)
    mean_tpr[-1] = 1.0
    mean_auc = auc(mean_fpr, mean_tpr)
    std_auc = np.std(aucs)
    ax.plot(mean_fpr, mean_tpr, color='b',
             label=r'Mean ROC (AUC = %0.2f $\pm$ %0.2f)' % (mean_auc, std_auc),
             lw=2, alpha=.8)
    
    # Plot the standard deviation around the mean ROC.
    std_tpr = np.std(tprs_interp, axis=0)
    tprs_upper = np.minimum(mean_tpr + std_tpr, 1)
    tprs_lower = np.maximum(mean_tpr - std_tpr, 0)
    ax.fill_between(mean_fpr, tprs_lower, tprs_upper, color='grey', alpha=.2,
                     label=r'$\pm$ 1 std. dev.')
    
    # Fine tune and show the plot.
    ax.set_xlim([-0.05, 1.05])
    ax.set_ylim([-0.05, 1.05])
    ax.set_xlabel('False Positive Rate')
    ax.set_ylabel('True Positive Rate')
    ax.set_title('Receiver operating characteristic')
    ax.legend(loc="lower right")
    plt.show()
    return (f, ax)

def compute_roc_auc(index):
    y_predict = clf.predict_proba(X.iloc[index])[:,1]
    fpr, tpr, thresholds = roc_curve(y.iloc[index], y_predict)
    auc_score = auc(fpr, tpr)
    return fpr, tpr, auc_score

def plot_feature_importance(model):
    n_features = X.shape[1]
    plt.barh(np.arange(n_features), sorted(model.feature_importances_), align="center")
    plt.yticks(np.arange(n_features), X.columns)
    plt.xlabel("DecisionTreeClassifier Feature Importance")
    plt.ylabel("Feature")
    plt.ylim(-1, n_features)

In [31]:
X_train.shape

(82056, 768)

In [32]:
X_test.shape

(11112, 768)

In [33]:
X_train

0      1      2      3      4      5      6      7      8      9    \
0    17.81  17.69  18.23  18.29  18.39  18.11  18.55  18.39  18.53  18.49   
1    17.77  17.77  18.17  18.25  18.41  18.15  18.59  18.39  18.49  18.53   
2    17.91  17.85  18.13  18.21  18.49  18.19  18.41  18.37  18.57  18.57   
3    17.95  17.87  18.11  18.17  18.51  18.21  18.35  18.37  18.65  18.53   
4    18.21  17.87  18.07  18.13  18.59  18.23  18.37  18.37  18.77  18.55   
..     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
875  17.59  17.39  17.75  17.57  17.39  17.57  17.79  17.69  18.11  17.79   
876  17.57  17.37  17.77  17.57  17.39  17.59  17.81  17.77  18.13  17.79   
877  17.47  17.27  17.75  17.57  17.43  17.61  17.81  17.91  18.17  17.79   
878  17.43  17.25  17.75  17.55  17.47  17.57  17.71  17.87  18.19  17.77   
879  17.39  17.17  17.75  17.53  17.39  17.53  17.71  17.89  18.15  17.75   

     ...    758    759    760    761    762    763    764    765    766    767  
0    ...  18.83  18.79  18.61  18.67  19.73  19.93  20.39  20.01  18.87  19.17  
1    ...  18.87  18.79  18.45  18.61  19.75  19.93  20.43  20.03  21.55  19.19  
2    ...  18.91  18.87  18.43  18.59  19.75  19.93  20.47  20.07  20.83  19.07  
3    ...  18.89  18.87  18.43  18.57  19.71  19.93  20.51  20.03  18.27  18.95  
4    ...  18.87  18.83  18.43  18.57  19.69  19.95  20.47  20.09  18.61  18.89  
..   ...    ...    ...    ...    ...    ...    ...    ...    ...    ...    ...  
875  ...  17.65  17.95  17.89  18.53  19.13  19.35  19.35  19.01  17.77  19.25  
876  ...  17.65  17.87  17.87  18.55  19.09  19.35  19.33  19.15  17.77  19.19  
877  ...  17.65  17.87  17.85  18.49  19.05  19.23  19.31  19.03  17.65  15.95  
878  ...  17.69  17.87  17.85  18.45  19.01  19.11  19.27  18.93  17.61  15.93  
879  ...  17.73  17.79  17.83  18.45  19.05  19.07  19.37  18.93  17.57  18.45  

[82056 rows x 768 columns]

In [34]:
X_train = X_train.to_numpy()
X_test = X_test.to_numpy()

In [35]:
X_train= X_train.reshape(82056, 32, 24, 1)
X_test = X_test.reshape(11112, 32, 24, 1)

In [36]:
y_train.shape

(82056,)

In [37]:
y_train

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
875    0.0
876    0.0
877    0.0
878    0.0
879    0.0
Name: label, Length: 82056, dtype: float64

In [38]:
# y_train = tf.keras.utils.to_categorical(y_train, 10)

In [39]:
# y_test = tf.keras.utils.to_categorical(y_test, 10)

In [40]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold
from sklearn.tree import DecisionTreeClassifier #의사결정나무
from sklearn.ensemble import GradientBoostingClassifier #그래디언트 부스팅
from tqdm import tqdm
from sklearn.linear_model import LogisticRegression

In [41]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

In [42]:
clf = models.Sequential()
clf.add(layers.Conv2D(32, (3, 3), activation = 'relu', input_shape = (32, 24, 1)))
clf.add(layers.MaxPooling2D((2, 2)))
clf.add(layers.Conv2D(64, (3, 3), activation = 'relu'))
clf.add(layers.MaxPooling2D((2, 2)))
clf.add(layers.Conv2D(64, (3, 3), activation = 'relu'))
clf.add(layers.Flatten())
clf.add(layers.Dense(64, activation = 'relu'))
clf.add(layers.Dense(1, activation = 'softmax'))

In [43]:
clf.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 22, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 11, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 9, 64)         18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 4, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 2, 64)          36928     
_________________________________________________________________
flatten (Flatten)            (None, 512)               0         
_________________________________________________________________
dense (Dense)                (None, 64)                3

In [44]:
# from tensorflow.compat.v1 import ConfigProto
# from tensorflow.compat.v1 import InteractiveSession

# config = ConfigProto()
# config.gpu_options.allow_growth = True
# session = InteractiveSession(config=config)

In [45]:
clf.compile(optimizer = 'adam',
           loss = 'binary_crossentropy',
           metrics = ['accuracy'])


In [46]:
clf.fit(X_train, y_train, epochs = 10, batch_size = 200)

Epoch 1/10
411/411 [==============================] - 5s 5ms/step - loss: 0.2597 - accuracy: 0.2408
Epoch 2/10
411/411 [==============================] - 2s 4ms/step - loss: 0.1658 - accuracy: 0.2408
Epoch 3/10
411/411 [==============================] - 2s 4ms/step - loss: 0.1469 - accuracy: 0.2408
Epoch 4/10
411/411 [==============================] - 2s 4ms/step - loss: 0.1357 - accuracy: 0.2408
Epoch 5/10
411/411 [==============================] - 2s 4ms/step - loss: 0.1327 - accuracy: 0.2408
Epoch 6/10
411/411 [==============================] - 2s 5ms/step - loss: 0.1262 - accuracy: 0.2408
Epoch 7/10
411/411 [==============================] - 2s 4ms/step - loss: 0.1232 - accuracy: 0.2408
Epoch 8/10
411/411 [==============================] - 2s 4ms/step - loss: 0.1176 - accuracy: 0.2408
Epoch 9/10
411/411 [==============================] - 2s 5ms/step - loss: 0.1124 - accuracy: 0.2408
Epoch 10/10
411/411 [==============================] - 2s 4ms/step - loss: 0.1097 - accuracy: 0.2408

In [ ]:
from sklearn.metrics import accuracy_score
mypredictions = clf.predict(X_test)
print(mypredictions.shape)
print('정확도 : {0:.4f}'.format(accuracy_score(y_test, mypredictions)))

In [47]:



# clf = LogisticRegression()

cv = StratifiedKFold(n_splits=5, random_state=123, shuffle=True)
results = pd.DataFrame(columns=['training_score', 'test_score'])
fprs, tprs, scores = [], [], []



In [49]:
for (train, test), i in tqdm(zip(cv.split(X, y), range(5))):
    clf.fit(X.iloc[train], y.iloc[train])
    _, _, auc_score_train = compute_roc_auc(train)
    fpr, tpr, auc_score = compute_roc_auc(test)
    scores.append((auc_score_train, auc_score))
    fprs.append(fpr)
    tprs.append(tpr)

plot_roc_curve(fprs, tprs)
pd.DataFrame(scores, columns=['AUC Train', 'AUC Test'])

0it [00:00, ?it/s]


ValueError: in user code:

    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:855 train_function  *
        return step_function(self, iterator)
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:845 step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:1285 run
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:2833 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\distribute\distribute_lib.py:3608 _call_for_each_replica
        return fn(*args, **kwargs)
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:838 run_step  **
        outputs = model.train_step(data)
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\training.py:795 train_step
        y_pred = self(x, training=True)
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\base_layer.py:1013 __call__
        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)
    C:\Users\Flora\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\keras\engine\input_spec.py:235 assert_input_compatibility
        str(tuple(shape)))

    ValueError: Input 0 of layer sequential is incompatible with the layer: : expected min_ndim=4, found ndim=2. Full shape received: (None, 768)


In [52]:
import joblib
joblib.dump(clf, 'savecnn.pkl')

TypeError: can't pickle weakref objects

In [ ]:
load = joblib.load('./savecnn.pkl')
load.predict_proba(X_test)

In [50]:
import sklearn
sklearn.__version__

'1.0.2'

In [51]:
load.predict(X_test)

NameError: name 'load' is not defined

In [53]:
from sklearn.metrics import accuracy_score
mypredictions = clf.predict(X_test)
print(mypredictions.shape)
print('정확도 : {0:.4f}'.format(accuracy_score(y_test, mypredictions)))

(11112, 1)
정확도 : 0.4936


## 낙상 유형별 테스트 검증

In [ ]:
for i in range(1,3):
    for j in range(1,4):
        for z in range(1, 16):
            print('G' + str(i) + str(j) + 'dataF' + str(z)+'_X_test'+ ','+ 'G' + str(i)+str(j) + 'dataF' + str(z) + '_y_test'+ ' = '+ 'G' + str(i) + str(j) + 'data' + str(z) + '_test'+'.drop(['+'\''+'label'+'\''+'],axis=1),'  +'G' + str(i) + str(j) + 'data' + str(z) + '_test'+'['+'\''+'label'+'\''+']') 

            


In [ ]:
G11dataF1_X_test,G11dataF1_y_test = G11data1_test.drop(['label'],axis=1),G11data1_test['label']
G11dataF2_X_test,G11dataF2_y_test = G11data2_test.drop(['label'],axis=1),G11data2_test['label']
G11dataF3_X_test,G11dataF3_y_test = G11data3_test.drop(['label'],axis=1),G11data3_test['label']
G11dataF4_X_test,G11dataF4_y_test = G11data4_test.drop(['label'],axis=1),G11data4_test['label']
G11dataF5_X_test,G11dataF5_y_test = G11data5_test.drop(['label'],axis=1),G11data5_test['label']
G11dataF6_X_test,G11dataF6_y_test = G11data6_test.drop(['label'],axis=1),G11data6_test['label']
G11dataF7_X_test,G11dataF7_y_test = G11data7_test.drop(['label'],axis=1),G11data7_test['label']
G11dataF8_X_test,G11dataF8_y_test = G11data8_test.drop(['label'],axis=1),G11data8_test['label']
G11dataF9_X_test,G11dataF9_y_test = G11data9_test.drop(['label'],axis=1),G11data9_test['label']
G11dataF10_X_test,G11dataF10_y_test = G11data10_test.drop(['label'],axis=1),G11data10_test['label']
G11dataF11_X_test,G11dataF11_y_test = G11data11_test.drop(['label'],axis=1),G11data11_test['label']
G11dataF12_X_test,G11dataF12_y_test = G11data12_test.drop(['label'],axis=1),G11data12_test['label']
G11dataF13_X_test,G11dataF13_y_test = G11data13_test.drop(['label'],axis=1),G11data13_test['label']
G11dataF14_X_test,G11dataF14_y_test = G11data14_test.drop(['label'],axis=1),G11data14_test['label']
G11dataF15_X_test,G11dataF15_y_test = G11data15_test.drop(['label'],axis=1),G11data15_test['label']
G12dataF1_X_test,G12dataF1_y_test = G12data1_test.drop(['label'],axis=1),G12data1_test['label']
G12dataF2_X_test,G12dataF2_y_test = G12data2_test.drop(['label'],axis=1),G12data2_test['label']
G12dataF3_X_test,G12dataF3_y_test = G12data3_test.drop(['label'],axis=1),G12data3_test['label']
G12dataF4_X_test,G12dataF4_y_test = G12data4_test.drop(['label'],axis=1),G12data4_test['label']
G12dataF5_X_test,G12dataF5_y_test = G12data5_test.drop(['label'],axis=1),G12data5_test['label']
G12dataF6_X_test,G12dataF6_y_test = G12data6_test.drop(['label'],axis=1),G12data6_test['label']
G12dataF7_X_test,G12dataF7_y_test = G12data7_test.drop(['label'],axis=1),G12data7_test['label']
G12dataF8_X_test,G12dataF8_y_test = G12data8_test.drop(['label'],axis=1),G12data8_test['label']
G12dataF9_X_test,G12dataF9_y_test = G12data9_test.drop(['label'],axis=1),G12data9_test['label']
G12dataF10_X_test,G12dataF10_y_test = G12data10_test.drop(['label'],axis=1),G12data10_test['label']
G12dataF11_X_test,G12dataF11_y_test = G12data11_test.drop(['label'],axis=1),G12data11_test['label']
G12dataF12_X_test,G12dataF12_y_test = G12data12_test.drop(['label'],axis=1),G12data12_test['label']
G12dataF13_X_test,G12dataF13_y_test = G12data13_test.drop(['label'],axis=1),G12data13_test['label']
G12dataF14_X_test,G12dataF14_y_test = G12data14_test.drop(['label'],axis=1),G12data14_test['label']
G12dataF15_X_test,G12dataF15_y_test = G12data15_test.drop(['label'],axis=1),G12data15_test['label']
G13dataF1_X_test,G13dataF1_y_test = G13data1_test.drop(['label'],axis=1),G13data1_test['label']
G13dataF2_X_test,G13dataF2_y_test = G13data2_test.drop(['label'],axis=1),G13data2_test['label']
G13dataF3_X_test,G13dataF3_y_test = G13data3_test.drop(['label'],axis=1),G13data3_test['label']
G13dataF4_X_test,G13dataF4_y_test = G13data4_test.drop(['label'],axis=1),G13data4_test['label']
G13dataF5_X_test,G13dataF5_y_test = G13data5_test.drop(['label'],axis=1),G13data5_test['label']
G13dataF6_X_test,G13dataF6_y_test = G13data6_test.drop(['label'],axis=1),G13data6_test['label']
G13dataF7_X_test,G13dataF7_y_test = G13data7_test.drop(['label'],axis=1),G13data7_test['label']
G13dataF8_X_test,G13dataF8_y_test = G13data8_test.drop(['label'],axis=1),G13data8_test['label']
G13dataF9_X_test,G13dataF9_y_test = G13data9_test.drop(['label'],axis=1),G13data9_test['label']
G13dataF10_X_test,G13dataF10_y_test = G13data10_test.drop(['label'],axis=1),G13data10_test['label']
G13dataF11_X_test,G13dataF11_y_test = G13data11_test.drop(['label'],axis=1),G13data11_test['label']
G13dataF12_X_test,G13dataF12_y_test = G13data12_test.drop(['label'],axis=1),G13data12_test['label']
G13dataF13_X_test,G13dataF13_y_test = G13data13_test.drop(['label'],axis=1),G13data13_test['label']
G13dataF14_X_test,G13dataF14_y_test = G13data14_test.drop(['label'],axis=1),G13data14_test['label']
G13dataF15_X_test,G13dataF15_y_test = G13data15_test.drop(['label'],axis=1),G13data15_test['label']
G21dataF1_X_test,G21dataF1_y_test = G21data1_test.drop(['label'],axis=1),G21data1_test['label']
G21dataF2_X_test,G21dataF2_y_test = G21data2_test.drop(['label'],axis=1),G21data2_test['label']
G21dataF3_X_test,G21dataF3_y_test = G21data3_test.drop(['label'],axis=1),G21data3_test['label']
G21dataF4_X_test,G21dataF4_y_test = G21data4_test.drop(['label'],axis=1),G21data4_test['label']
G21dataF5_X_test,G21dataF5_y_test = G21data5_test.drop(['label'],axis=1),G21data5_test['label']
G21dataF6_X_test,G21dataF6_y_test = G21data6_test.drop(['label'],axis=1),G21data6_test['label']
G21dataF7_X_test,G21dataF7_y_test = G21data7_test.drop(['label'],axis=1),G21data7_test['label']
G21dataF8_X_test,G21dataF8_y_test = G21data8_test.drop(['label'],axis=1),G21data8_test['label']
G21dataF9_X_test,G21dataF9_y_test = G21data9_test.drop(['label'],axis=1),G21data9_test['label']
G21dataF10_X_test,G21dataF10_y_test = G21data10_test.drop(['label'],axis=1),G21data10_test['label']
G21dataF11_X_test,G21dataF11_y_test = G21data11_test.drop(['label'],axis=1),G21data11_test['label']
G21dataF12_X_test,G21dataF12_y_test = G21data12_test.drop(['label'],axis=1),G21data12_test['label']
G21dataF13_X_test,G21dataF13_y_test = G21data13_test.drop(['label'],axis=1),G21data13_test['label']
G21dataF14_X_test,G21dataF14_y_test = G21data14_test.drop(['label'],axis=1),G21data14_test['label']
G21dataF15_X_test,G21dataF15_y_test = G21data15_test.drop(['label'],axis=1),G21data15_test['label']
G22dataF1_X_test,G22dataF1_y_test = G22data1_test.drop(['label'],axis=1),G22data1_test['label']
G22dataF2_X_test,G22dataF2_y_test = G22data2_test.drop(['label'],axis=1),G22data2_test['label']
G22dataF3_X_test,G22dataF3_y_test = G22data3_test.drop(['label'],axis=1),G22data3_test['label']
G22dataF4_X_test,G22dataF4_y_test = G22data4_test.drop(['label'],axis=1),G22data4_test['label']
G22dataF5_X_test,G22dataF5_y_test = G22data5_test.drop(['label'],axis=1),G22data5_test['label']
G22dataF6_X_test,G22dataF6_y_test = G22data6_test.drop(['label'],axis=1),G22data6_test['label']
G22dataF7_X_test,G22dataF7_y_test = G22data7_test.drop(['label'],axis=1),G22data7_test['label']
G22dataF8_X_test,G22dataF8_y_test = G22data8_test.drop(['label'],axis=1),G22data8_test['label']
G22dataF9_X_test,G22dataF9_y_test = G22data9_test.drop(['label'],axis=1),G22data9_test['label']
G22dataF10_X_test,G22dataF10_y_test = G22data10_test.drop(['label'],axis=1),G22data10_test['label']
G22dataF11_X_test,G22dataF11_y_test = G22data11_test.drop(['label'],axis=1),G22data11_test['label']
G22dataF12_X_test,G22dataF12_y_test = G22data12_test.drop(['label'],axis=1),G22data12_test['label']
G22dataF13_X_test,G22dataF13_y_test = G22data13_test.drop(['label'],axis=1),G22data13_test['label']
G22dataF14_X_test,G22dataF14_y_test = G22data14_test.drop(['label'],axis=1),G22data14_test['label']
G22dataF15_X_test,G22dataF15_y_test = G22data15_test.drop(['label'],axis=1),G22data15_test['label']
G23dataF1_X_test,G23dataF1_y_test = G23data1_test.drop(['label'],axis=1),G23data1_test['label']
G23dataF2_X_test,G23dataF2_y_test = G23data2_test.drop(['label'],axis=1),G23data2_test['label']
G23dataF3_X_test,G23dataF3_y_test = G23data3_test.drop(['label'],axis=1),G23data3_test['label']
G23dataF4_X_test,G23dataF4_y_test = G23data4_test.drop(['label'],axis=1),G23data4_test['label']
G23dataF5_X_test,G23dataF5_y_test = G23data5_test.drop(['label'],axis=1),G23data5_test['label']
G23dataF6_X_test,G23dataF6_y_test = G23data6_test.drop(['label'],axis=1),G23data6_test['label']
G23dataF7_X_test,G23dataF7_y_test = G23data7_test.drop(['label'],axis=1),G23data7_test['label']
G23dataF8_X_test,G23dataF8_y_test = G23data8_test.drop(['label'],axis=1),G23data8_test['label']
G23dataF9_X_test,G23dataF9_y_test = G23data9_test.drop(['label'],axis=1),G23data9_test['label']
G23dataF10_X_test,G23dataF10_y_test = G23data10_test.drop(['label'],axis=1),G23data10_test['label']
G23dataF11_X_test,G23dataF11_y_test = G23data11_test.drop(['label'],axis=1),G23data11_test['label']
G23dataF12_X_test,G23dataF12_y_test = G23data12_test.drop(['label'],axis=1),G23data12_test['label']
G23dataF13_X_test,G23dataF13_y_test = G23data13_test.drop(['label'],axis=1),G23data13_test['label']
G23dataF14_X_test,G23dataF14_y_test = G23data14_test.drop(['label'],axis=1),G23data14_test['label']
G23dataF15_X_test,G23dataF15_y_test = G23data15_test.drop(['label'],axis=1),G23data15_test['label']

In [ ]:
G22dataF10_y_test.value_counts()

In [ ]:
G11dataF12_y_test.value_counts()

In [ ]:
from sklearn.metrics import accuracy_score
G11dataF1predictions = clf.predict(G11dataF1_X_test)
print(G11dataF1predictions)
print('정확도 : {0:.4f}'.format(accuracy_score(G11dataF1_y_test, G11dataF1predictions)))

In [ ]:
G11dataF5predictions=clf.predict(G11dataF5_X_test)
print('정확도 : {0:.4f}'.format(accuracy_score(G11dataF5_y_test,G11dataF5predictions)))

In [ ]:
print('=================G11Result====================')
G11dataF1predictions=clf.predict(G11dataF1_X_test)
print('f1 정확도 : {0:.4f}'.format(accuracy_score(G11dataF1_y_test,G11dataF1predictions)))
G11dataF2predictions=clf.predict(G11dataF2_X_test)
print('f2 정확도 : {0:.4f}'.format(accuracy_score(G11dataF2_y_test,G11dataF2predictions)))
G11dataF3predictions=clf.predict(G11dataF3_X_test)
print('f3 정확도 : {0:.4f}'.format(accuracy_score(G11dataF3_y_test,G11dataF3predictions)))
G11dataF4predictions=clf.predict(G11dataF4_X_test)
print('f4 정확도 : {0:.4f}'.format(accuracy_score(G11dataF4_y_test,G11dataF4predictions)))
G11dataF5predictions=clf.predict(G11dataF5_X_test)
print('f5 정확도 : {0:.4f}'.format(accuracy_score(G11dataF5_y_test,G11dataF5predictions)))
G11dataF6predictions=clf.predict(G11dataF6_X_test)
print('f6 정확도 : {0:.4f}'.format(accuracy_score(G11dataF6_y_test,G11dataF6predictions)))
G11dataF7predictions=clf.predict(G11dataF7_X_test)
print('f7 정확도 : {0:.4f}'.format(accuracy_score(G11dataF7_y_test,G11dataF7predictions)))
G11dataF8predictions=clf.predict(G11dataF8_X_test)
print('f8 정확도 : {0:.4f}'.format(accuracy_score(G11dataF8_y_test,G11dataF8predictions)))
G11dataF9predictions=clf.predict(G11dataF9_X_test)
print('f9 정확도 : {0:.4f}'.format(accuracy_score(G11dataF9_y_test,G11dataF9predictions)))
G11dataF10predictions=clf.predict(G11dataF10_X_test)
print('f10 정확도 : {0:.4f}'.format(accuracy_score(G11dataF10_y_test,G11dataF10predictions)))
G11dataF11predictions=clf.predict(G11dataF11_X_test)
print('f11 정확도 : {0:.4f}'.format(accuracy_score(G11dataF11_y_test,G11dataF11predictions)))
G11dataF12predictions=clf.predict(G11dataF12_X_test)
print('f12 정확도 : {0:.4f}'.format(accuracy_score(G11dataF12_y_test,G11dataF12predictions)))
G11dataF13predictions=clf.predict(G11dataF13_X_test)
print('f13 정확도 : {0:.4f}'.format(accuracy_score(G11dataF13_y_test,G11dataF13predictions)))
G11dataF14predictions=clf.predict(G11dataF14_X_test)
print('f14 정확도 : {0:.4f}'.format(accuracy_score(G11dataF14_y_test,G11dataF14predictions)))
G11dataF15predictions=clf.predict(G11dataF15_X_test)
print('f15 정확도 : {0:.4f}'.format(accuracy_score(G11dataF15_y_test,G11dataF15predictions)))
print('=================G12Result====================')
G12dataF1predictions=clf.predict(G12dataF1_X_test)
print('f1 정확도 : {0:.4f}'.format(accuracy_score(G12dataF1_y_test,G12dataF1predictions)))
G12dataF2predictions=clf.predict(G12dataF2_X_test)
print('f2 정확도 : {0:.4f}'.format(accuracy_score(G12dataF2_y_test,G12dataF2predictions)))
G12dataF3predictions=clf.predict(G12dataF3_X_test)
print('f3 정확도 : {0:.4f}'.format(accuracy_score(G12dataF3_y_test,G12dataF3predictions)))
G12dataF4predictions=clf.predict(G12dataF4_X_test)
print('f4 정확도 : {0:.4f}'.format(accuracy_score(G12dataF4_y_test,G12dataF4predictions)))
G12dataF5predictions=clf.predict(G12dataF5_X_test)
print('f5 정확도 : {0:.4f}'.format(accuracy_score(G12dataF5_y_test,G12dataF5predictions)))
G12dataF6predictions=clf.predict(G12dataF6_X_test)
print('f6 정확도 : {0:.4f}'.format(accuracy_score(G12dataF6_y_test,G12dataF6predictions)))
G12dataF7predictions=clf.predict(G12dataF7_X_test)
print('f7 정확도 : {0:.4f}'.format(accuracy_score(G12dataF7_y_test,G12dataF7predictions)))
G12dataF8predictions=clf.predict(G12dataF8_X_test)
print('f8 정확도 : {0:.4f}'.format(accuracy_score(G12dataF8_y_test,G12dataF8predictions)))
G12dataF9predictions=clf.predict(G12dataF9_X_test)
print('f9 정확도 : {0:.4f}'.format(accuracy_score(G12dataF9_y_test,G12dataF9predictions)))
G12dataF10predictions=clf.predict(G12dataF10_X_test)
print('f10 정확도 : {0:.4f}'.format(accuracy_score(G12dataF10_y_test,G12dataF10predictions)))
G12dataF11predictions=clf.predict(G12dataF11_X_test)
print('f11 정확도 : {0:.4f}'.format(accuracy_score(G12dataF11_y_test,G12dataF11predictions)))
G12dataF12predictions=clf.predict(G12dataF12_X_test)
print('f12 정확도 : {0:.4f}'.format(accuracy_score(G12dataF12_y_test,G12dataF12predictions)))
G12dataF13predictions=clf.predict(G12dataF13_X_test)
print('f13 정확도 : {0:.4f}'.format(accuracy_score(G12dataF13_y_test,G12dataF13predictions)))
G12dataF14predictions=clf.predict(G12dataF14_X_test)
print('f14 정확도 : {0:.4f}'.format(accuracy_score(G12dataF14_y_test,G12dataF14predictions)))
G12dataF15predictions=clf.predict(G12dataF15_X_test)
print('f15 정확도 : {0:.4f}'.format(accuracy_score(G12dataF15_y_test,G12dataF15predictions)))
print('=================G13Result====================')
G13dataF1predictions=clf.predict(G13dataF1_X_test)
print('f1 정확도 : {0:.4f}'.format(accuracy_score(G13dataF1_y_test,G13dataF1predictions)))
G13dataF2predictions=clf.predict(G13dataF2_X_test)
print('f2 정확도 : {0:.4f}'.format(accuracy_score(G13dataF2_y_test,G13dataF2predictions)))
G13dataF3predictions=clf.predict(G13dataF3_X_test)
print('f3 정확도 : {0:.4f}'.format(accuracy_score(G13dataF3_y_test,G13dataF3predictions)))
G13dataF4predictions=clf.predict(G13dataF4_X_test)
print('f4 정확도 : {0:.4f}'.format(accuracy_score(G13dataF4_y_test,G13dataF4predictions)))
G13dataF5predictions=clf.predict(G13dataF5_X_test)
print('f5 정확도 : {0:.4f}'.format(accuracy_score(G13dataF5_y_test,G13dataF5predictions)))
G13dataF6predictions=clf.predict(G13dataF6_X_test)
print('f6 정확도 : {0:.4f}'.format(accuracy_score(G13dataF6_y_test,G13dataF6predictions)))
G13dataF7predictions=clf.predict(G13dataF7_X_test)
print('f7 정확도 : {0:.4f}'.format(accuracy_score(G13dataF7_y_test,G13dataF7predictions)))
G13dataF8predictions=clf.predict(G13dataF8_X_test)
print('f8 정확도 : {0:.4f}'.format(accuracy_score(G13dataF8_y_test,G13dataF8predictions)))
G13dataF9predictions=clf.predict(G13dataF9_X_test)
print('f9 정확도 : {0:.4f}'.format(accuracy_score(G13dataF9_y_test,G13dataF9predictions)))
G13dataF10predictions=clf.predict(G13dataF10_X_test)
print('f10 정확도 : {0:.4f}'.format(accuracy_score(G13dataF10_y_test,G13dataF10predictions)))
G13dataF11predictions=clf.predict(G13dataF11_X_test)
print('f11 정확도 : {0:.4f}'.format(accuracy_score(G13dataF11_y_test,G13dataF11predictions)))
G13dataF12predictions=clf.predict(G13dataF12_X_test)
print('f12 정확도 : {0:.4f}'.format(accuracy_score(G13dataF12_y_test,G13dataF12predictions)))
G13dataF13predictions=clf.predict(G13dataF13_X_test)
print('f13 정확도 : {0:.4f}'.format(accuracy_score(G13dataF13_y_test,G13dataF13predictions)))
G13dataF14predictions=clf.predict(G13dataF14_X_test)
print('f14 정확도 : {0:.4f}'.format(accuracy_score(G13dataF14_y_test,G13dataF14predictions)))
G13dataF15predictions=clf.predict(G13dataF15_X_test)
print('f15 정확도 : {0:.4f}'.format(accuracy_score(G13dataF15_y_test,G13dataF15predictions)))
print('=================G21Result====================')
G21dataF1predictions=clf.predict(G21dataF1_X_test)
print('f1 정확도 : {0:.4f}'.format(accuracy_score(G21dataF1_y_test,G21dataF1predictions)))
G21dataF2predictions=clf.predict(G21dataF2_X_test)
print('f2 정확도 : {0:.4f}'.format(accuracy_score(G21dataF2_y_test,G21dataF2predictions)))
G21dataF3predictions=clf.predict(G21dataF3_X_test)
print('f3 정확도 : {0:.4f}'.format(accuracy_score(G21dataF3_y_test,G21dataF3predictions)))
G21dataF4predictions=clf.predict(G21dataF4_X_test)
print('f4 정확도 : {0:.4f}'.format(accuracy_score(G21dataF4_y_test,G21dataF4predictions)))
G21dataF5predictions=clf.predict(G21dataF5_X_test)
print('f5 정확도 : {0:.4f}'.format(accuracy_score(G21dataF5_y_test,G21dataF5predictions)))
G21dataF6predictions=clf.predict(G21dataF6_X_test)
print('f6 정확도 : {0:.4f}'.format(accuracy_score(G21dataF6_y_test,G21dataF6predictions)))
G21dataF7predictions=clf.predict(G21dataF7_X_test)
print('f7 정확도 : {0:.4f}'.format(accuracy_score(G21dataF7_y_test,G21dataF7predictions)))
G21dataF8predictions=clf.predict(G21dataF8_X_test)
print('f8 정확도 : {0:.4f}'.format(accuracy_score(G21dataF8_y_test,G21dataF8predictions)))
G21dataF9predictions=clf.predict(G21dataF9_X_test)
print('f9 정확도 : {0:.4f}'.format(accuracy_score(G21dataF9_y_test,G21dataF9predictions)))
G21dataF10predictions=clf.predict(G21dataF10_X_test)
print('f10 정확도 : {0:.4f}'.format(accuracy_score(G21dataF10_y_test,G21dataF10predictions)))
G21dataF11predictions=clf.predict(G21dataF11_X_test)
print('f11 정확도 : {0:.4f}'.format(accuracy_score(G21dataF11_y_test,G21dataF11predictions)))
G21dataF12predictions=clf.predict(G21dataF12_X_test)
print('f12 정확도 : {0:.4f}'.format(accuracy_score(G21dataF12_y_test,G21dataF12predictions)))
G21dataF13predictions=clf.predict(G21dataF13_X_test)
print('f13 정확도 : {0:.4f}'.format(accuracy_score(G21dataF13_y_test,G21dataF13predictions)))
G21dataF14predictions=clf.predict(G21dataF14_X_test)
print('f14 정확도 : {0:.4f}'.format(accuracy_score(G21dataF14_y_test,G21dataF14predictions)))
G21dataF15predictions=clf.predict(G21dataF15_X_test)
print('f15 정확도 : {0:.4f}'.format(accuracy_score(G21dataF15_y_test,G21dataF15predictions)))
print('=================G22Result====================')
G22dataF1predictions=clf.predict(G22dataF1_X_test)
print('f1 정확도 : {0:.4f}'.format(accuracy_score(G22dataF1_y_test,G22dataF1predictions)))
G22dataF2predictions=clf.predict(G22dataF2_X_test)
print('f2 정확도 : {0:.4f}'.format(accuracy_score(G22dataF2_y_test,G22dataF2predictions)))
G22dataF3predictions=clf.predict(G22dataF3_X_test)
print('f3 정확도 : {0:.4f}'.format(accuracy_score(G22dataF3_y_test,G22dataF3predictions)))
G22dataF4predictions=clf.predict(G22dataF4_X_test)
print('f4 정확도 : {0:.4f}'.format(accuracy_score(G22dataF4_y_test,G22dataF4predictions)))
G22dataF5predictions=clf.predict(G22dataF5_X_test)
print('f5 정확도 : {0:.4f}'.format(accuracy_score(G22dataF5_y_test,G22dataF5predictions)))
G22dataF6predictions=clf.predict(G22dataF6_X_test)
print('f6 정확도 : {0:.4f}'.format(accuracy_score(G22dataF6_y_test,G22dataF6predictions)))
G22dataF7predictions=clf.predict(G22dataF7_X_test)
print('f7 정확도 : {0:.4f}'.format(accuracy_score(G22dataF7_y_test,G22dataF7predictions)))
G22dataF8predictions=clf.predict(G22dataF8_X_test)
print('f8 정확도 : {0:.4f}'.format(accuracy_score(G22dataF8_y_test,G22dataF8predictions)))
G22dataF9predictions=clf.predict(G22dataF9_X_test)
print('f9 정확도 : {0:.4f}'.format(accuracy_score(G22dataF9_y_test,G22dataF9predictions)))
G22dataF10predictions=clf.predict(G22dataF10_X_test)
print('f10 정확도 : {0:.4f}'.format(accuracy_score(G22dataF10_y_test,G22dataF10predictions)))
G22dataF11predictions=clf.predict(G22dataF11_X_test)
print('f11 정확도 : {0:.4f}'.format(accuracy_score(G22dataF11_y_test,G22dataF11predictions)))
G22dataF12predictions=clf.predict(G22dataF12_X_test)
print('f12 정확도 : {0:.4f}'.format(accuracy_score(G22dataF12_y_test,G22dataF12predictions)))
G22dataF13predictions=clf.predict(G22dataF13_X_test)
print('f13 정확도 : {0:.4f}'.format(accuracy_score(G22dataF13_y_test,G22dataF13predictions)))
G22dataF14predictions=clf.predict(G22dataF14_X_test)
print('f14 정확도 : {0:.4f}'.format(accuracy_score(G22dataF14_y_test,G22dataF14predictions)))
G22dataF15predictions=clf.predict(G22dataF15_X_test)
print('f15 정확도 : {0:.4f}'.format(accuracy_score(G22dataF15_y_test,G22dataF15predictions)))
print('=================G23Result====================')
G23dataF1predictions=clf.predict(G23dataF1_X_test)
print('f1 정확도 : {0:.4f}'.format(accuracy_score(G23dataF1_y_test,G23dataF1predictions)))
G23dataF2predictions=clf.predict(G23dataF2_X_test)
print('f2 정확도 : {0:.4f}'.format(accuracy_score(G23dataF2_y_test,G23dataF2predictions)))
G23dataF3predictions=clf.predict(G23dataF3_X_test)
print('f3 정확도 : {0:.4f}'.format(accuracy_score(G23dataF3_y_test,G23dataF3predictions)))
G23dataF4predictions=clf.predict(G23dataF4_X_test)
print('f4 정확도 : {0:.4f}'.format(accuracy_score(G23dataF4_y_test,G23dataF4predictions)))
G23dataF5predictions=clf.predict(G23dataF5_X_test)
print('f5 정확도 : {0:.4f}'.format(accuracy_score(G23dataF5_y_test,G23dataF5predictions)))
G23dataF6predictions=clf.predict(G23dataF6_X_test)
print('f6 정확도 : {0:.4f}'.format(accuracy_score(G23dataF6_y_test,G23dataF6predictions)))
G23dataF7predictions=clf.predict(G23dataF7_X_test)
print('f7 정확도 : {0:.4f}'.format(accuracy_score(G23dataF7_y_test,G23dataF7predictions)))
G23dataF8predictions=clf.predict(G23dataF8_X_test)
print('f8 정확도 : {0:.4f}'.format(accuracy_score(G23dataF8_y_test,G23dataF8predictions)))
G23dataF9predictions=clf.predict(G23dataF9_X_test)
print('f9 정확도 : {0:.4f}'.format(accuracy_score(G23dataF9_y_test,G23dataF9predictions)))
G23dataF10predictions=clf.predict(G23dataF10_X_test)
print('f10 정확도 : {0:.4f}'.format(accuracy_score(G23dataF10_y_test,G23dataF10predictions)))
G23dataF11predictions=clf.predict(G23dataF11_X_test)
print('f11 정확도 : {0:.4f}'.format(accuracy_score(G23dataF11_y_test,G23dataF11predictions)))
G23dataF12predictions=clf.predict(G23dataF12_X_test)
print('f12 정확도 : {0:.4f}'.format(accuracy_score(G23dataF12_y_test,G23dataF12predictions)))
G23dataF13predictions=clf.predict(G23dataF13_X_test)
print('f13 정확도 : {0:.4f}'.format(accuracy_score(G23dataF13_y_test,G23dataF13predictions)))
G23dataF14predictions=clf.predict(G23dataF14_X_test)
print('f14 정확도 : {0:.4f}'.format(accuracy_score(G23dataF14_y_test,G23dataF14predictions)))
G23dataF15predictions=clf.predict(G23dataF15_X_test)
print('f15 정확도 : {0:.4f}'.format(accuracy_score(G23dataF15_y_test,G23dataF15predictions)))

In [ ]:
predict = []
print(G23dataF5_y_test)
print(G23dataF5predictions)
# print(G13dataF10predictions[0])

j = 1132
for i in range(0,len(G23dataF5predictions)):
    predict.append(j)
    predict.append(G23dataF5predictions[i])
    j = j+ 1
print(predict)

In [ ]:
mat_file_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f02-data.mat')
y_predict = []
for i in range(len(mat_file_io.get('melexisG12f02'))):
    y_predict.append(i)
    y_predict.append(clf.predict(mat_file_io.get('melexisG12f02')[i].reshape((1,-1))))
    
print(y_predict)

In [ ]:
mat_file_io = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-2-f03-data.mat')
y_predict = []
for i in range(len(mat_file_io.get('melexisG12f03'))):
    y_predict.append(i)
    y_predict.append(clf.predict(mat_file_io.get('melexisG12f03')[i].reshape((1,-1))))
    
print(y_predict)

In [ ]:
from sklearn.model_selection import cross_val_score
cross_val_score(clf, X_train, y_train, cv=3, scoring="accuracy")

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scale = scaler.fit_transform(X_train)

clf.fit(X_train_scale, y_train)
cross_val_score(clf, X_train, y_train, cv=3, scoring="accuracy")

In [ ]:
X_test_scale = scaler.fit_transform(X_test)
prediction = clf.predict(X_test_scale)
result = (prediction == y_test).mean()
print(result)

In [ ]:
# fig = plt.figure()
# random_pick = np.random.randint(low=0, high=1879, size= 10)
# print(y[random_pick])
# for i in range(10):
#     idx = random_pick[i]
#     img = np.reshape(X[idx], (24, 32))
#     plot = fig.add_subplot(1, 10, i+ 1)
#     plot.imshow(img)

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G1-1-f01-data.mat')
# print(mat_file)
# print(mat_file.get('melexisG11f01'))
# print(mat_file.get('melexisG11f01').shape)
# print(mat_file.get('melexisG11f01'))
# #print(mat_file.get('depo1')[-1])

# img = np.array(mat_file.get('melexisG11f01')[10]).reshape(24,32)
# print(img.shape)
# print(img)
# fig = plt.rcParams['figure.figsize'] = [24, 32]
# plt.imsave('./img.png',img, vmin=17,vmax=23,cmap='viridis', interpolation='nearest')
# #plt.colorbar(ax)
# #plt.savefig('./img.png')

In [ ]:
# # after 
# frames = []

# for i in range(len(mat_file.get('melexisG11f03'))):
#     img = np.array(mat_file.get('melexisG11f03')[i]).reshape(24,32)
#     fig = plt.rcParams['figure.figsize'] = [24, 32]
#     #ax = plt.imshow(img, vmin=17,vmax=23,cmap='viridis', interpolation='nearest')
#     #plt.colorbar(ax)
#     frames.append([plt.imshow(img, vmin=17,vmax=23,cmap='viridis',animated=True ,interpolation='nearest')])


In [ ]:
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG11f03'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG11f03')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG11f03.gif")

In [ ]:
# ani = animation.Animation(fig, frames, blit=True)
# ani.save('1.mp4', fps=30, extra_args=['-vcodec', 'libx264'])

In [ ]:
# for i in range(len(mat_file.get('melexisG21f01'))):
#     img = np.array(mat_file.get('melexisG21f01')[i]).reshape(24,32)
#     fig = plt.rcParams['figure.figsize'] = [24, 32]
#     ax = plt.imshow(img, vmin=17,vmax=23,cmap='viridis', interpolation='nearest')
#     ani = FuncAnimation(fig,img)
#     plt.colorbar(ax)
#     plt.show()
# # print(len(mat_file.get('melexisG21f01')))


In [ ]:
# ani = FuncAnimation(fig, frames=)

In [ ]:
# print(len(mat_file.get('melexisG11f11')))
# print(len(mat_file.get('melexisG11f11')[0]))
# print(mat_file.get('melexisG11f11')[0])
# for i in range(0, len(mat_file.get('melexisG11f11'))):
#     img = np.array(mat_file.get('melexisG11f11')[i]).reshape(32,24)
#     plt.rcParams['figure.figsize'] = [32, 24]
#     plt.imshow(img, cmap='hot', interpolation='nearest')
#     plt.savefig(f'{i}.png')
               



In [ ]:
# img = np.array(mat_file.get('melexisG11f11')[0]).reshape(32,24)
# plt.rcParams['figure.figsize'] = [32, 24]
# plt.imshow(img, cmap='hot', interpolation='nearest')
# plt.show()

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f01-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f01'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f01')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f01.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f02-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f02'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f02')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f02.gif")

In [ ]:
# # melexisG12f03 다시 만들고 melexisG13f03 생성
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f03-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f03'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f03')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f03.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f04-data.mat')

In [ ]:
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f04'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f04')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f04.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f05-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f05'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f05')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f05.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f06-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f06'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f06')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f06.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f07-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f07'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f07')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f07.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f08-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f08'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f08')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f08.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f09-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f09'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f09')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f09.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f10-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f10'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f10')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f10.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f11-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f11'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f11')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f11.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f12-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f12'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f12')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f12.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f13-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f13'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f13')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f13.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f14-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f14'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f14')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f14.gif")

In [ ]:
# mat_file = io.loadmat('./sensors-19-04565-s001/eHomeSeniors dataset/melexis sensor/datos matlab/melexis-G2-1-f15-data.mat')
# fig, ax = plt.subplots()
# ims = []
# for i in range(len(mat_file.get('melexisG21f15'))):
#     im = ax.imshow(np.array(mat_file.get('melexisG21f15')[i]).reshape(24,32))
#     ims.append([im])

# ani = animation.ArtistAnimation(fig, ims, interval=50, blit=True, repeat_delay=1000)
# ani.save("melexisG21f15.gif")